<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vpx_util/vpx_thread.h' l='401' type='void (*)(VPxWorker *const)'/>
<offset>0</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vpx_util/vpx_thread.h' l='400'>// Must be called first, before any other method.</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/decoder/vp9_decodeframe.c' l='2294' u='r' c='init_mt'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/decoder/vp9_decoder.c' l='211' u='r' c='vp9_decoder_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/encoder/vp9_ethread.c' l='106' u='r' c='create_enc_workers'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vpx_util/vpx_thread.c' l='167' u='r' c='vpx_set_worker_interface'/>
<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/preprocs/nasm/nasm.h' l='96' type='void (*)(char *, efunc)'/>
<offset>0</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/preprocs/nasm/nasm.h' l='90'>/*
     * Called to initialise the listing file generator. Before this
     * is called, the other routines will silently do nothing when
     * called. The `char *&apos; parameter is the file name to write the
     * listing to.
     */</doc>
