<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/structs.h' l='70' type='opus_int32 [4]'/>
<offset>480</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/structs.h' l='70'>/* Noise energy level in each band                                      */</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/VAD.c' l='63' u='w' c='silk_VAD_Init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/VAD.c' l='64' u='r' c='silk_VAD_Init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/VAD.c' l='204' u='r' c='silk_VAD_GetSA_Q8_c'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/VAD.c' l='208' u='r' c='silk_VAD_GetSA_Q8_c'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/VAD.c' l='210' u='r' c='silk_VAD_GetSA_Q8_c'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/VAD.c' l='252' u='r' c='silk_VAD_GetSA_Q8_c'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/VAD.c' l='323' u='r' c='silk_VAD_GetNoiseLevels'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/silk/VAD.c' l='358' u='w' c='silk_VAD_GetNoiseLevels'/>
