<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/internal.h' l='85' type='fe'/>
<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/internal.h' l='92' type='fe_loose'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='545' u='a' c='x25519_ge_frombytes_vartime'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='559' u='a' c='ge_p3_0'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='587' u='a' c='x25519_ge_p3_to_cached'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='592' u='a' c='x25519_ge_p1p1_to_p2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='594' u='a' c='x25519_ge_p1p1_to_p2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='599' u='a' c='x25519_ge_p1p1_to_p3'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='601' u='a' c='x25519_ge_p1p1_to_p3'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='602' u='a' c='x25519_ge_p1p1_to_p3'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='628' u='a' c='ge_p2_dbl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='646' u='a' c='ge_madd'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='647' u='a' c='ge_madd'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='650' u='a' c='ge_madd'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='652' u='a' c='ge_madd'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='663' u='a' c='ge_msub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='664' u='a' c='ge_msub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='667' u='a' c='ge_msub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='669' u='a' c='ge_msub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='680' u='a' c='x25519_ge_add'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='682' u='a' c='x25519_ge_add'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='685' u='a' c='x25519_ge_add'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='687' u='a' c='x25519_ge_add'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='698' u='a' c='x25519_ge_sub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='700' u='a' c='x25519_ge_sub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='703' u='a' c='x25519_ge_sub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='705' u='a' c='x25519_ge_sub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='1935' u='a' c='ED25519_verify'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/curve25519/curve25519.c' l='1936' u='a' c='ED25519_verify'/>
<offset>960</offset>
