<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='547' type='uint16_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1407' u='r' c='_ZN5angle7L16A16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1416' u='w' c='_ZN5angle7L16A16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1422' u='w' c='_ZN5angle7L16A16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1422' u='r' c='_ZN5angle7L16A16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1422' u='r' c='_ZN5angle7L16A16F7averageEPS0_PKS0_S3_'/>
