<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='284' type='uint16_t'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='690' u='r' c='_ZN5angle12R16G16B16A169readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='698' u='r' c='_ZN5angle12R16G16B16A169readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='706' u='w' c='_ZN5angle12R16G16B16A1610writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='714' u='w' c='_ZN5angle12R16G16B16A1610writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='722' u='w' c='_ZN5angle12R16G16B16A167averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='722' u='r' c='_ZN5angle12R16G16B16A167averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='722' u='r' c='_ZN5angle12R16G16B16A167averageEPS0_PKS0_S3_'/>
