<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='270' type='uint16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='652' u='r' c='_ZN5angle9R16G16B169readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='660' u='r' c='_ZN5angle9R16G16B169readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='668' u='w' c='_ZN5angle9R16G16B1610writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='675' u='w' c='_ZN5angle9R16G16B1610writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='682' u='w' c='_ZN5angle9R16G16B167averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='682' u='r' c='_ZN5angle9R16G16B167averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='682' u='r' c='_ZN5angle9R16G16B167averageEPS0_PKS0_S3_'/>
