<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='650' type='float'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1617' u='r' c='_ZN5angle10R32G32B32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1625' u='w' c='_ZN5angle10R32G32B32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1632' u='w' c='_ZN5angle10R32G32B32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1632' u='r' c='_ZN5angle10R32G32B32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1632' u='r' c='_ZN5angle10R32G32B32F7averageEPS0_PKS0_S3_'/>
