<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='189' type='uint8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='436' u='r' c='_ZN5angle8B8G8R8X89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='444' u='r' c='_ZN5angle8B8G8R8X89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='452' u='w' c='_ZN5angle8B8G8R8X810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='460' u='w' c='_ZN5angle8B8G8R8X810writeColorEPS0_PKNS_5ColorIfEE'/>
