<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='778' type='float'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1885' u='r' c='_ZN5angle4D32F16ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1890' u='w' c='_ZN5angle4D32F17WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
