<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='795' type='uint32_t'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1907' u='r' c='_ZN5angle9D32FS8X2416ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1913' u='w' c='_ZN5angle9D32FS8X2417WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
