<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='136' type='uint8_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='288' u='r' c='_ZN5angle8A8R8G8B89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='296' u='r' c='_ZN5angle8A8R8G8B89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='304' u='w' c='_ZN5angle8A8R8G8B810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='312' u='w' c='_ZN5angle8A8R8G8B810writeColorEPS0_PKNS_5ColorIfEE'/>
