<use f='webkit/Source/ThirdParty/ANGLE/src/common/Color.h' l='23' u='a' c='_ZNK5angle5Color4dataEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/Color.h' l='24' u='a' c='_ZN5angle5Color3ptrEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/Color.h' l='29' u='r' c='_ZNK5angle5Color9writeDataEPT_'/>
<dec f='webkit/Source/ThirdParty/ANGLE/src/common/Color.h' l='35' type='T'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/Color.inc' l='18' u='w' c='_ZN5angle5ColorC1ET_S1_S1_S1_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='20' u='w' c='_ZN5angle2L89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='28' u='r' c='_ZN5angle2L810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='38' u='w' c='_ZN5angle2R89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='46' u='w' c='_ZN5angle2R89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='54' u='r' c='_ZN5angle2R810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='59' u='r' c='_ZN5angle2R810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='69' u='w' c='_ZN5angle2A89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='88' u='w' c='_ZN5angle4L8A89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='96' u='r' c='_ZN5angle4L8A810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='109' u='w' c='_ZN5angle4A8L89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='117' u='r' c='_ZN5angle4A8L810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='129' u='w' c='_ZN5angle4R8G89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='137' u='w' c='_ZN5angle4R8G89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='145' u='r' c='_ZN5angle4R8G810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='151' u='r' c='_ZN5angle4R8G810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='163' u='w' c='_ZN5angle6R8G8B89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='171' u='w' c='_ZN5angle6R8G8B89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='179' u='r' c='_ZN5angle6R8G8B810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='186' u='r' c='_ZN5angle6R8G8B810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='200' u='w' c='_ZN5angle6B8G8R89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='208' u='w' c='_ZN5angle6B8G8R89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='216' u='r' c='_ZN5angle6B8G8R810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='223' u='r' c='_ZN5angle6B8G8R810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='237' u='w' c='_ZN5angle6R5G6B59readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='245' u='r' c='_ZN5angle6R5G6B510writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='262' u='w' c='_ZN5angle6B5G6R59readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='272' u='r' c='_ZN5angle6B5G6R510writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='287' u='w' c='_ZN5angle8A8R8G8B89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='295' u='w' c='_ZN5angle8A8R8G8B89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='303' u='r' c='_ZN5angle8A8R8G8B810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='311' u='r' c='_ZN5angle8A8R8G8B810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='325' u='w' c='_ZN5angle8R8G8B8A89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='333' u='w' c='_ZN5angle8R8G8B8A89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='341' u='r' c='_ZN5angle8R8G8B8A810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='349' u='r' c='_ZN5angle8R8G8B8A810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='363' u='w' c='_ZN5angle12R8G8B8A8SRGB9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='371' u='r' c='_ZN5angle12R8G8B8A8SRGB10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='397' u='w' c='_ZN5angle8B8G8R8A89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='405' u='w' c='_ZN5angle8B8G8R8A89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='413' u='r' c='_ZN5angle8B8G8R8A810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='421' u='r' c='_ZN5angle8B8G8R8A810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='435' u='w' c='_ZN5angle8B8G8R8X89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='443' u='w' c='_ZN5angle8B8G8R8X89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='451' u='r' c='_ZN5angle8B8G8R8X810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='459' u='r' c='_ZN5angle8B8G8R8X810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='475' u='w' c='_ZN5angle8A1R5G5B59readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='483' u='r' c='_ZN5angle8A1R5G5B510writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='502' u='w' c='_ZN5angle8R5G5B5A19readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='510' u='r' c='_ZN5angle8R5G5B5A110writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='530' u='w' c='_ZN5angle8R4G4B4A49readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='538' u='r' c='_ZN5angle8R4G4B4A410writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='559' u='w' c='_ZN5angle8A4R4G4B49readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='567' u='r' c='_ZN5angle8A4R4G4B410writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='586' u='w' c='_ZN5angle3R169readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='594' u='w' c='_ZN5angle3R169readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='602' u='r' c='_ZN5angle3R1610writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='607' u='r' c='_ZN5angle3R1610writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='617' u='w' c='_ZN5angle6R16G169readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='625' u='w' c='_ZN5angle6R16G169readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='633' u='r' c='_ZN5angle6R16G1610writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='639' u='r' c='_ZN5angle6R16G1610writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='651' u='w' c='_ZN5angle9R16G16B169readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='659' u='w' c='_ZN5angle9R16G16B169readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='667' u='r' c='_ZN5angle9R16G16B1610writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='674' u='r' c='_ZN5angle9R16G16B1610writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='688' u='w' c='_ZN5angle12R16G16B16A169readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='696' u='w' c='_ZN5angle12R16G16B16A169readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='704' u='r' c='_ZN5angle12R16G16B16A1610writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='712' u='r' c='_ZN5angle12R16G16B16A1610writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='728' u='w' c='_ZN5angle3R329readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='736' u='w' c='_ZN5angle3R329readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='744' u='r' c='_ZN5angle3R3210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='749' u='r' c='_ZN5angle3R3210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='759' u='w' c='_ZN5angle6R32G329readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='767' u='w' c='_ZN5angle6R32G329readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='775' u='r' c='_ZN5angle6R32G3210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='781' u='r' c='_ZN5angle6R32G3210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='793' u='w' c='_ZN5angle9R32G32B329readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='801' u='w' c='_ZN5angle9R32G32B329readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='809' u='r' c='_ZN5angle9R32G32B3210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='816' u='r' c='_ZN5angle9R32G32B3210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='830' u='w' c='_ZN5angle12R32G32B32A329readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='838' u='w' c='_ZN5angle12R32G32B32A329readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='846' u='r' c='_ZN5angle12R32G32B32A3210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='854' u='r' c='_ZN5angle12R32G32B32A3210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='870' u='w' c='_ZN5angle3R8S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='878' u='w' c='_ZN5angle3R8S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='886' u='r' c='_ZN5angle3R8S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='891' u='r' c='_ZN5angle3R8S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='901' u='w' c='_ZN5angle5R8G8S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='909' u='w' c='_ZN5angle5R8G8S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='917' u='r' c='_ZN5angle5R8G8S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='923' u='r' c='_ZN5angle5R8G8S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='935' u='w' c='_ZN5angle7R8G8B8S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='943' u='w' c='_ZN5angle7R8G8B8S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='951' u='r' c='_ZN5angle7R8G8B8S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='958' u='r' c='_ZN5angle7R8G8B8S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='972' u='w' c='_ZN5angle9R8G8B8A8S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='980' u='w' c='_ZN5angle9R8G8B8A8S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='988' u='r' c='_ZN5angle9R8G8B8A8S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='996' u='r' c='_ZN5angle9R8G8B8A8S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1012' u='w' c='_ZN5angle4R16S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1020' u='w' c='_ZN5angle4R16S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1028' u='r' c='_ZN5angle4R16S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1033' u='r' c='_ZN5angle4R16S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1043' u='w' c='_ZN5angle7R16G16S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1051' u='w' c='_ZN5angle7R16G16S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1059' u='r' c='_ZN5angle7R16G16S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1065' u='r' c='_ZN5angle7R16G16S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1077' u='w' c='_ZN5angle10R16G16B16S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1085' u='w' c='_ZN5angle10R16G16B16S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1093' u='r' c='_ZN5angle10R16G16B16S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1100' u='r' c='_ZN5angle10R16G16B16S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1114' u='w' c='_ZN5angle13R16G16B16A16S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1122' u='w' c='_ZN5angle13R16G16B16A16S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1130' u='r' c='_ZN5angle13R16G16B16A16S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1138' u='r' c='_ZN5angle13R16G16B16A16S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1156' u='w' c='_ZN5angle4R32S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1164' u='w' c='_ZN5angle4R32S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1172' u='r' c='_ZN5angle4R32S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1177' u='r' c='_ZN5angle4R32S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1187' u='w' c='_ZN5angle7R32G32S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1195' u='w' c='_ZN5angle7R32G32S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1203' u='r' c='_ZN5angle7R32G32S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1209' u='r' c='_ZN5angle7R32G32S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1221' u='w' c='_ZN5angle10R32G32B32S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1229' u='w' c='_ZN5angle10R32G32B32S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1237' u='r' c='_ZN5angle10R32G32B32S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1244' u='r' c='_ZN5angle10R32G32B32S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1258' u='w' c='_ZN5angle13R32G32B32A32S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1266' u='w' c='_ZN5angle13R32G32B32A32S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1274' u='r' c='_ZN5angle13R32G32B32A32S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1282' u='r' c='_ZN5angle13R32G32B32A32S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1300' u='w' c='_ZN5angle13A16B16G16R16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1308' u='r' c='_ZN5angle13A16B16G16R16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1326' u='w' c='_ZN5angle13R16G16B16A16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1334' u='r' c='_ZN5angle13R16G16B16A16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1352' u='w' c='_ZN5angle4R16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1360' u='r' c='_ZN5angle4R16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1370' u='w' c='_ZN5angle4A16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1389' u='w' c='_ZN5angle4L16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1397' u='r' c='_ZN5angle4L16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1408' u='w' c='_ZN5angle7L16A16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1416' u='r' c='_ZN5angle7L16A16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1428' u='w' c='_ZN5angle7R16G16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1436' u='r' c='_ZN5angle7R16G16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1448' u='w' c='_ZN5angle10R16G16B16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1456' u='r' c='_ZN5angle10R16G16B16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1470' u='w' c='_ZN5angle13A32B32G32R32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1478' u='r' c='_ZN5angle13A32B32G32R32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1496' u='w' c='_ZN5angle13R32G32B32A32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1504' u='r' c='_ZN5angle13R32G32B32A32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1522' u='w' c='_ZN5angle4R32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1530' u='r' c='_ZN5angle4R32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1540' u='w' c='_ZN5angle4A32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1558' u='w' c='_ZN5angle4L32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1566' u='r' c='_ZN5angle4L32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1576' u='w' c='_ZN5angle7L32A32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1584' u='r' c='_ZN5angle7L32A32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1596' u='w' c='_ZN5angle7R32G32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1604' u='r' c='_ZN5angle7R32G32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1616' u='w' c='_ZN5angle10R32G32B32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1624' u='r' c='_ZN5angle10R32G32B32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1638' u='w' c='_ZN5angle11R10G10B10A29readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1646' u='w' c='_ZN5angle11R10G10B10A29readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1654' u='r' c='_ZN5angle11R10G10B10A210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1662' u='r' c='_ZN5angle11R10G10B10A210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1678' u='w' c='_ZN5angle12R10G10B10A2S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1686' u='w' c='_ZN5angle12R10G10B10A2S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1694' u='r' c='_ZN5angle12R10G10B10A2S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1702' u='r' c='_ZN5angle12R10G10B10A2S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1718' u='w' c='_ZN5angle11R10G10B10X29readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1726' u='w' c='_ZN5angle11R10G10B10X29readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1734' u='r' c='_ZN5angle11R10G10B10X210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1741' u='r' c='_ZN5angle11R10G10B10X210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1755' u='w' c='_ZN5angle11B10G10R10A29readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1763' u='w' c='_ZN5angle11B10G10R10A29readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1771' u='r' c='_ZN5angle11B10G10R10A210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1779' u='r' c='_ZN5angle11B10G10R10A210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1795' u='a' c='_ZN5angle8R9G9B9E59readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1802' u='r' c='_ZN5angle8R9G9B9E510writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1819' u='w' c='_ZN5angle10R11G11B10F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1827' u='r' c='_ZN5angle10R11G11B10F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/GLES1Renderer.cpp' l='168' u='r' c='_ZN2gl13GLES1Renderer14prepareForDrawENS_13PrimitiveModeEPNS_7ContextEPNS_5StateE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/GLES1Renderer.cpp' l='239' u='r' c='_ZN2gl13GLES1Renderer14prepareForDrawENS_13PrimitiveModeEPNS_7ContextEPNS_5StateE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='392' u='w' c='_ZN2gl5State10initializeEPNS_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='688' u='w' c='_ZN2gl5State18setColorClearValueEffff'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='880' u='w' c='_ZN2gl5State13setBlendColorEffff'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='2334' u='r' c='_ZNK2gl5State9getFloatvEjPf'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='2340' u='r' c='_ZNK2gl5State9getFloatvEjPf'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='2360' u='r' c='_ZNK2gl5State9getFloatvEjPf'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='100' u='r' c='_ZN2gl12_GLOBAL__N_116ConvertFromColorERKN5angle12ColorGenericEPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='108' u='r' c='_ZN2gl12_GLOBAL__N_116ConvertFromColorERKN5angle12ColorGenericEPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='121' u='r' c='_ZN2gl12_GLOBAL__N_116ConvertFromColorERKN5angle12ColorGenericEPj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/SamplerGL.cpp' l='34' u='a' c='_ZN12_GLOBAL__N_119SetSamplerParameterEPKN2rx11FunctionsGLEjjRKN5angle12ColorGenericE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/SamplerGL.cpp' l='37' u='a' c='_ZN12_GLOBAL__N_119SetSamplerParameterEPKN2rx11FunctionsGLEjjRKN5angle12ColorGenericE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/SamplerGL.cpp' l='40' u='a' c='_ZN12_GLOBAL__N_119SetSamplerParameterEPKN2rx11FunctionsGLEjjRKN5angle12ColorGenericE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='1145' u='r' c='_ZN2rx14StateManagerGL13setBlendColorERKN5angle5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='1680' u='r' c='_ZN2rx14StateManagerGL13setClearColorERKN5angle5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='1680' u='r' c='_ZN2rx14StateManagerGL13setClearColorERKN5angle5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='1698' u='r' c='_ZN2rx14StateManagerGL13setClearColorERKN5angle5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='1517' u='a' c='_ZN2rx9TextureGL9syncStateEPKN2gl7ContextERKN5angle7BitSetTILm24EjmEENS1_7CommandE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='1523' u='a' c='_ZN2rx9TextureGL9syncStateEPKN2gl7ContextERKN5angle7BitSetTILm24EjmEENS1_7CommandE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='1529' u='a' c='_ZN2rx9TextureGL9syncStateEPKN2gl7ContextERKN5angle7BitSetTILm24EjmEENS1_7CommandE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ContextMtl.mm' l='1115' u='r' c='_ZN2rx10ContextMtl9syncStateEPKN2gl7ContextERKN5angle14IterableBitSetILm63EEES9_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ContextMtl.mm' l='2201' u='r' c='_ZN2rx10ContextMtl9setupDrawEPKN2gl7ContextENS1_13PrimitiveModeEiiiNS1_16DrawElementsTypeEPKvb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='59' u='w' c='_ZN2rx12_GLOBAL__N_116PremultiplyAlphaEPN5angle5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='69' u='w' c='_ZN2rx12_GLOBAL__N_115UnmultiplyAlphaEPN5angle5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='100' u='w' c='_ZN2rx12_GLOBAL__N_117ClipChannelsAlphaEPN5angle5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='112' u='r' c='_ZN2rx12_GLOBAL__N_114WriteUintColorERKN5angle5ColorIfEEPFvPKhPhES8_'/>
