<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='509' type='uint16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1327' u='r' c='_ZN5angle13R16G16B16A16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1335' u='w' c='_ZN5angle13R16G16B16A16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1345' u='w' c='_ZN5angle13R16G16B16A16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1345' u='r' c='_ZN5angle13R16G16B16A16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1345' u='r' c='_ZN5angle13R16G16B16A16F7averageEPS0_PKS0_S3_'/>
