<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='761' type='uint16_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1864' u='r' c='_ZN5angle3D1616ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1870' u='w' c='_ZN5angle3D1617WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
