<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='744' type='uint32_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1842' u='r' c='_ZN5angle5D24S816ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1848' u='w' c='_ZN5angle5D24S817WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
