<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='662' type='uint32_t'/>
<offset>20</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1640' u='r' c='_ZN5angle11R10G10B10A29readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1648' u='r' c='_ZN5angle11R10G10B10A29readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1656' u='w' c='_ZN5angle11R10G10B10A210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1664' u='w' c='_ZN5angle11R10G10B10A210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1672' u='w' c='_ZN5angle11R10G10B10A27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1672' u='r' c='_ZN5angle11R10G10B10A27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1672' u='r' c='_ZN5angle11R10G10B10A27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage.cpp' l='942' u='r' c='_ZN5angle19LoadRGB10A2ToBGR5A1EmmmPKhmmPhmm'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage.cpp' l='975' u='r' c='_ZN5angle19LoadRGB10A2ToRGB5A1EmmmPKhmmPhmm'/>
