<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='174' type='uint8_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='399' u='r' c='_ZN5angle8B8G8R8A89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='407' u='r' c='_ZN5angle8B8G8R8A89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='415' u='w' c='_ZN5angle8B8G8R8A810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='423' u='w' c='_ZN5angle8B8G8R8A810writeColorEPS0_PKNS_5ColorIfEE'/>
