<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='471' type='int32_t'/>
<offset>64</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1223' u='r' c='_ZN5angle10R32G32B32S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1231' u='r' c='_ZN5angle10R32G32B32S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1239' u='w' c='_ZN5angle10R32G32B32S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1246' u='w' c='_ZN5angle10R32G32B32S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1253' u='w' c='_ZN5angle10R32G32B32S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1253' u='r' c='_ZN5angle10R32G32B32S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1253' u='r' c='_ZN5angle10R32G32B32S7averageEPS0_PKS0_S3_'/>
