<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='629' type='float'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1576' u='r' c='_ZN5angle7L32A32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1577' u='r' c='_ZN5angle7L32A32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1578' u='r' c='_ZN5angle7L32A32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1584' u='w' c='_ZN5angle7L32A32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1590' u='w' c='_ZN5angle7L32A32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1590' u='r' c='_ZN5angle7L32A32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1590' u='r' c='_ZN5angle7L32A32F7averageEPS0_PKS0_S3_'/>
