<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='370' type='int8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='936' u='r' c='_ZN5angle7R8G8B8S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='944' u='r' c='_ZN5angle7R8G8B8S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='952' u='w' c='_ZN5angle7R8G8B8S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='959' u='w' c='_ZN5angle7R8G8B8S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='966' u='w' c='_ZN5angle7R8G8B8S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='966' u='r' c='_ZN5angle7R8G8B8S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='966' u='r' c='_ZN5angle7R8G8B8S7averageEPS0_PKS0_S3_'/>
