<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='76' type='uint8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='130' u='r' c='_ZN5angle4R8G89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='138' u='r' c='_ZN5angle4R8G89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='146' u='w' c='_ZN5angle4R8G810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='152' u='w' c='_ZN5angle4R8G810writeColorEPS0_PKNS_5ColorIfEE'/>
