<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='745' type='uint32_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1841' u='r' c='_ZN5angle5D24S816ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1847' u='w' c='_ZN5angle5D24S817WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
