<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='769' type='uint32_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1875' u='r' c='_ZN5angle5D24X816ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1880' u='w' c='_ZN5angle5D24X817WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
