<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='89' type='uint8_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='173' u='r' c='_ZN5angle6R8G8B89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='181' u='w' c='_ZN5angle6R8G8B810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='188' u='w' c='_ZN5angle6R8G8B810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='195' u='w' c='_ZN5angle6R8G8B87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='195' u='r' c='_ZN5angle6R8G8B87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='195' u='r' c='_ZN5angle6R8G8B87averageEPS0_PKS0_S3_'/>
