<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='786' type='uint32_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1895' u='r' c='_ZN5angle3D3216ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1901' u='w' c='_ZN5angle3D3217WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
