<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='483' type='int32_t'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1259' u='r' c='_ZN5angle13R32G32B32A32S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1267' u='r' c='_ZN5angle13R32G32B32A32S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1275' u='w' c='_ZN5angle13R32G32B32A32S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1283' u='w' c='_ZN5angle13R32G32B32A32S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1293' u='w' c='_ZN5angle13R32G32B32A32S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1293' u='r' c='_ZN5angle13R32G32B32A32S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1293' u='r' c='_ZN5angle13R32G32B32A32S7averageEPS0_PKS0_S3_'/>
