<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='677' type='int32_t'/>
<offset>20</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1680' u='r' c='_ZN5angle12R10G10B10A2S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1688' u='r' c='_ZN5angle12R10G10B10A2S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1696' u='w' c='_ZN5angle12R10G10B10A2S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1704' u='w' c='_ZN5angle12R10G10B10A2S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1712' u='w' c='_ZN5angle12R10G10B10A2S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1712' u='r' c='_ZN5angle12R10G10B10A2S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1712' u='r' c='_ZN5angle12R10G10B10A2S7averageEPS0_PKS0_S3_'/>
