<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='163' type='uint8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='364' u='r' c='_ZN5angle12R8G8B8A8SRGB9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='372' u='w' c='_ZN5angle12R8G8B8A8SRGB10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='383' u='w' c='_ZN5angle12R8G8B8A8SRGB7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='384' u='r' c='_ZN5angle12R8G8B8A8SRGB7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='385' u='r' c='_ZN5angle12R8G8B8A8SRGB7averageEPS0_PKS0_S3_'/>
