<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='383' type='int8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='973' u='r' c='_ZN5angle9R8G8B8A8S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='981' u='r' c='_ZN5angle9R8G8B8A8S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='989' u='w' c='_ZN5angle9R8G8B8A8S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='997' u='w' c='_ZN5angle9R8G8B8A8S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1005' u='w' c='_ZN5angle9R8G8B8A8S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1005' u='r' c='_ZN5angle9R8G8B8A8S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1005' u='r' c='_ZN5angle9R8G8B8A8S7averageEPS0_PKS0_S3_'/>
