<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='149' type='uint8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='326' u='r' c='_ZN5angle8R8G8B8A89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='334' u='r' c='_ZN5angle8R8G8B8A89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='342' u='w' c='_ZN5angle8R8G8B8A810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='350' u='w' c='_ZN5angle8R8G8B8A810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage_etc.cpp' l='405' u='w' c='_ZN5angle12_GLOBAL__N_19ETC2Block10createRGBAEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage_etc.cpp' l='708' u='r' c='_ZNK5angle12_GLOBAL__N_19ETC2Block12RGB8ToRGB565ERKNS_8R8G8B8A8E'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage_etc.cpp' l='723' u='r' c='_ZNK5angle12_GLOBAL__N_19ETC2Block12matchBC1BitsEPKiS3_PKNS_8R8G8B8A8EmRS5_S7_b'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage_etc.cpp' l='724' u='r' c='_ZNK5angle12_GLOBAL__N_19ETC2Block12matchBC1BitsEPKiS3_PKNS_8R8G8B8A8EmRS5_S7_b'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage_etc.cpp' l='758' u='r' c='_ZNK5angle12_GLOBAL__N_19ETC2Block12matchBC1BitsEPKiS3_PKNS_8R8G8B8A8EmRS5_S7_b'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage_etc.cpp' l='793' u='r' c='_ZNK5angle12_GLOBAL__N_19ETC2Block12matchBC1BitsEPKiS3_PKNS_8R8G8B8A8EmRS5_S7_b'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage_etc.cpp' l='1029' u='r' c='_ZNK5angle12_GLOBAL__N_19ETC2Block17selectEndPointPCAEPKiPKNS_8R8G8B8A8EmPiS7_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/loadimage_etc.cpp' l='1107' u='r' c='_ZNK5angle12_GLOBAL__N_19ETC2Block17selectEndPointPCAEPKiPKNS_8R8G8B8A8EmPiS7_'/>
