<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='258' type='uint16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='618' u='r' c='_ZN5angle6R16G169readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='626' u='r' c='_ZN5angle6R16G169readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='634' u='w' c='_ZN5angle6R16G1610writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='640' u='w' c='_ZN5angle6R16G1610writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='646' u='w' c='_ZN5angle6R16G167averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='646' u='r' c='_ZN5angle6R16G167averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='646' u='r' c='_ZN5angle6R16G167averageEPS0_PKS0_S3_'/>
