<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='592' type='float'/>
<offset>64</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1498' u='r' c='_ZN5angle13R32G32B32A32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1506' u='w' c='_ZN5angle13R32G32B32A32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1516' u='w' c='_ZN5angle13R32G32B32A32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1516' u='r' c='_ZN5angle13R32G32B32A32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1516' u='r' c='_ZN5angle13R32G32B32A32F7averageEPS0_PKS0_S3_'/>
