<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='733' type='uint32_t'/>
<offset>11</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1820' u='r' c='_ZN5angle10R11G11B10F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1828' u='w' c='_ZN5angle10R11G11B10F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1835' u='w' c='_ZN5angle10R11G11B10F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1835' u='r' c='_ZN5angle10R11G11B10F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1835' u='r' c='_ZN5angle10R11G11B10F7averageEPS0_PKS0_S3_'/>
