<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='568' type='uint16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1449' u='r' c='_ZN5angle10R16G16B16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1457' u='w' c='_ZN5angle10R16G16B16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1464' u='w' c='_ZN5angle10R16G16B16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1464' u='r' c='_ZN5angle10R16G16B16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1464' u='r' c='_ZN5angle10R16G16B16F7averageEPS0_PKS0_S3_'/>
