<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='408' type='int16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1044' u='r' c='_ZN5angle7R16G16S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1052' u='r' c='_ZN5angle7R16G16S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1060' u='w' c='_ZN5angle7R16G16S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1066' u='w' c='_ZN5angle7R16G16S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1072' u='w' c='_ZN5angle7R16G16S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1072' u='r' c='_ZN5angle7R16G16S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1072' u='r' c='_ZN5angle7R16G16S7averageEPS0_PKS0_S3_'/>
