<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='101' type='uint8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='201' u='r' c='_ZN5angle6B8G8R89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='202' u='r' c='_ZN5angle6B8G8R89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='209' u='r' c='_ZN5angle6B8G8R89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='217' u='w' c='_ZN5angle6B8G8R810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='224' u='w' c='_ZN5angle6B8G8R810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='231' u='w' c='_ZN5angle6B8G8R87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='231' u='r' c='_ZN5angle6B8G8R87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='231' u='r' c='_ZN5angle6B8G8R87averageEPS0_PKS0_S3_'/>
