<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='333' type='uint32_t'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='831' u='r' c='_ZN5angle12R32G32B32A329readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='839' u='r' c='_ZN5angle12R32G32B32A329readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='847' u='w' c='_ZN5angle12R32G32B32A3210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='855' u='w' c='_ZN5angle12R32G32B32A3210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='863' u='w' c='_ZN5angle12R32G32B32A327averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='863' u='r' c='_ZN5angle12R32G32B32A327averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='863' u='r' c='_ZN5angle12R32G32B32A327averageEPS0_PKS0_S3_'/>
