<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='734' type='uint32_t'/>
<offset>22</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1821' u='r' c='_ZN5angle10R11G11B10F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1829' u='w' c='_ZN5angle10R11G11B10F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1836' u='w' c='_ZN5angle10R11G11B10F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1836' u='r' c='_ZN5angle10R11G11B10F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1836' u='r' c='_ZN5angle10R11G11B10F7averageEPS0_PKS0_S3_'/>
