<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='794' type='float'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1906' u='r' c='_ZN5angle9D32FS8X2416ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1912' u='w' c='_ZN5angle9D32FS8X2417WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
