<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='704' type='uint32_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1757' u='r' c='_ZN5angle11B10G10R10A29readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1765' u='r' c='_ZN5angle11B10G10R10A29readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1773' u='w' c='_ZN5angle11B10G10R10A210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1781' u='w' c='_ZN5angle11B10G10R10A210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1789' u='w' c='_ZN5angle11B10G10R10A27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1789' u='r' c='_ZN5angle11B10G10R10A27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1789' u='r' c='_ZN5angle11B10G10R10A27averageEPS0_PKS0_S3_'/>
