<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='458' type='int32_t'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1188' u='r' c='_ZN5angle7R32G32S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1196' u='r' c='_ZN5angle7R32G32S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1204' u='w' c='_ZN5angle7R32G32S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1210' u='w' c='_ZN5angle7R32G32S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1216' u='w' c='_ZN5angle7R32G32S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1216' u='r' c='_ZN5angle7R32G32S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1216' u='r' c='_ZN5angle7R32G32S7averageEPS0_PKS0_S3_'/>
