<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='580' type='float'/>
<offset>64</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1471' u='r' c='_ZN5angle13A32B32G32R32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1479' u='w' c='_ZN5angle13A32B32G32R32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1489' u='w' c='_ZN5angle13A32B32G32R32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1489' u='r' c='_ZN5angle13A32B32G32R32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1489' u='r' c='_ZN5angle13A32B32G32R32F7averageEPS0_PKS0_S3_'/>
