<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/bio.h' l='826' type='int'/>
<offset>64</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/bio.h' l='825'>// init is non-zero if this |BIO| has been initialised.</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/bio.c' l='129' u='r' c='BIO_read'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/bio.c' l='148' u='r' c='BIO_gets'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/bio.c' l='167' u='r' c='BIO_write'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/bio.c' l='691' u='w' c='BIO_set_init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/bio.c' l='693' u='r' c='BIO_get_init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/bio_mem.c' l='111' u='w' c='mem_new'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/bio_mem.c' l='125' u='r' c='mem_free'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/connect.c' l='320' u='w' c='conn_new'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/connect.c' l='428' u='w' c='conn_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/connect.c' l='450' u='r' c='conn_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/fd.c' l='154' u='r' c='fd_free'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/fd.c' l='157' u='w' c='fd_free'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/fd.c' l='198' u='r' c='fd_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/fd.c' l='205' u='r' c='fd_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/fd.c' l='213' u='w' c='fd_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/fd.c' l='216' u='r' c='fd_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/file.c' l='140' u='r' c='file_free'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/file.c' l='144' u='w' c='file_free'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/file.c' l='150' u='r' c='file_read'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/file.c' l='168' u='r' c='file_write'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/file.c' l='203' u='w' c='file_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/file.c' l='234' u='w' c='file_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/pair.c' l='117' u='w' c='bio_destroy_pair'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/pair.c' l='123' u='w' c='bio_destroy_pair'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/pair.c' l='156' u='r' c='bio_read'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/pair.c' l='239' u='r' c='bio_write'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/pair.c' l='352' u='w' c='bio_make_pair'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/pair.c' l='353' u='w' c='bio_make_pair'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/socket.c' l='85' u='w' c='sock_new'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/socket.c' l='98' u='r' c='sock_free'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/socket.c' l='101' u='w' c='sock_free'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/socket.c' l='156' u='w' c='sock_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/bio/socket.c' l='159' u='r' c='sock_ctrl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/bio_ssl.cc' l='114' u='w' c='_ZL8ssl_ctrlP6bio_stilPv'/>
