<use f='webkit/WebKitBuild/Debug/usr/local/include/bmalloc/Scavenger.h' l='56' u='r' c='_ZN7bmalloc9Scavenger7willRunEv'/>
<dec f='webkit/WebKitBuild/Debug/usr/local/include/bmalloc/Scavenger.h' l='81' type='1'/>
<use f='webkit/Source/bmalloc/bmalloc/Scavenger.h' l='56' u='r' c='_ZN7bmalloc9Scavenger7willRunEv'/>
<dec f='webkit/Source/bmalloc/bmalloc/Scavenger.h' l='81' type='1'/>
<use f='webkit/Source/bmalloc/bmalloc/Scavenger.cpp' l='105' u='r' c='_ZN7bmalloc9Scavenger3runERKNSt3__111scoped_lockIJNS_5MutexEEEE'/>
