<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/internal.h' l='2829' type='SSL *const'/>
<offset>0</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/internal.h' l='2828'>// ssl is a non-owning pointer to the parent |SSL| object.</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_cert.cc' l='667' u='r' c='_ZN4bssl18ssl_has_client_CAsEPKNS_10SSL_CONFIGE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='723' u='w' c='_ZN4bssl10SSL_CONFIGC1EP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='734' u='r' c='_ZN4bssl10SSL_CONFIGC1EP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='738' u='r' c='_ZN4bssl10SSL_CONFIGD1Ev'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='739' u='r' c='_ZN4bssl10SSL_CONFIGD1Ev'/>
