<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/internal.h' l='2637' type='UniquePtr&lt;bssl::SSL_HANDSHAKE&gt;'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/d1_both.cc' l='571' u='r' c='_ZN4bsslL12add_outgoingEP6ssl_stbNS_5ArrayIhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/d1_both.cc' l='572' u='m' c='_ZN4bsslL12add_outgoingEP6ssl_stbNS_5ArrayIhEE'/>
<offset>2176</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/internal.h' l='2635'>// hs is the handshake state for the current handshake or NULL if there isn&apos;t
  // one.</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='80' u='r' c='_ZN4bssl21SSL_serialize_handoffEPK6ssl_stP6cbb_stP22ssl_early_callback_ctx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='87' u='m' c='_ZN4bssl21SSL_serialize_handoffEPK6ssl_stP6cbb_stP22ssl_early_callback_ctx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='107' u='r' c='_ZN4bssl19SSL_decline_handoffEP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='112' u='m' c='_ZN4bssl19SSL_decline_handoffEP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='181' u='m' c='_ZN4bsslL21apply_remote_featuresEP6ssl_stP6cbs_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='271' u='m' c='_ZN4bssl17SSL_apply_handoffEP6ssl_stNS_4SpanIKhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='274' u='m' c='_ZN4bssl17SSL_apply_handoffEP6ssl_stNS_4SpanIKhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='284' u='m' c='_ZN4bssl22SSL_serialize_handbackEPK6ssl_stP6cbb_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='313' u='m' c='_ZN4bssl22SSL_serialize_handbackEPK6ssl_stP6cbb_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='368' u='m' c='_ZN4bssl22SSL_serialize_handbackEPK6ssl_stP6cbb_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='369' u='m' c='_ZN4bssl22SSL_serialize_handbackEPK6ssl_stP6cbb_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='370' u='m' c='_ZN4bssl22SSL_serialize_handbackEPK6ssl_stP6cbb_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='371' u='m' c='_ZN4bssl22SSL_serialize_handbackEPK6ssl_stP6cbb_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='372' u='m' c='_ZN4bssl22SSL_serialize_handbackEPK6ssl_stP6cbb_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='378' u='m' c='_ZN4bssl22SSL_serialize_handbackEPK6ssl_stP6cbb_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='483' u='w' c='_ZN4bssl18SSL_apply_handbackEP6ssl_stNS_4SpanIKhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='484' u='m' c='_ZN4bssl18SSL_apply_handbackEP6ssl_stNS_4SpanIKhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='765' u='m' c='SSL_request_handshake_hints'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='766' u='m' c='SSL_request_handshake_hints'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='808' u='m' c='SSL_serialize_handshake_hints'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handoff.cc' l='951' u='m' c='SSL_set_handshake_hints'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/handshake.cc' l='649' u='m' c='_ZN4bssl17ssl_run_handshakeEPNS_13SSL_HANDSHAKEEPb'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_both.cc' l='237' u='r' c='_ZN4bssl15tls_add_messageEP6ssl_stNS_5ArrayIhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_both.cc' l='238' u='m' c='_ZN4bssl15tls_add_messageEP6ssl_stNS_5ArrayIhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_both.cc' l='254' u='r' c='_ZN4bssl25tls_flush_pending_hs_dataEP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_both.cc' l='254' u='m' c='_ZN4bssl25tls_flush_pending_hs_dataEP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_both.cc' l='383' u='m' c='_ZN4bsslL20read_v2_client_helloEP6ssl_stPmNS_4SpanIKhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_lib.cc' l='195' u='w' c='_ZN4bssl7tls_newEP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_lib.cc' l='196' u='m' c='_ZN4bssl7tls_newEP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_pkt.cc' l='161' u='m' c='_ZN4bssl18tls_write_app_dataEP6ssl_stPbPKhi'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_pkt.cc' l='167' u='m' c='_ZN4bssl18tls_write_app_dataEP6ssl_stPbPKhi'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_pkt.cc' l='187' u='m' c='_ZN4bssl18tls_write_app_dataEP6ssl_stPbPKhi'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_pkt.cc' l='336' u='m' c='_ZN4bssl17tls_open_app_dataEP6ssl_stPNS_4SpanIhEEPmPhS3_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/s3_pkt.cc' l='342' u='m' c='_ZN4bssl17tls_open_app_dataEP6ssl_stPNS_4SpanIhEEPmPhS3_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_cert.cc' l='939' u='r' c='SSL_get0_server_requested_CAs'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_cert.cc' l='942' u='m' c='SSL_get0_server_requested_CAs'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='223' u='m' c='_ZN4bssl13ssl_can_writeEPK6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='227' u='m' c='_ZN4bssl12ssl_can_readEPK6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='491' u='r' c='_ZN4bsslL31ssl_maybe_shed_handshake_configEP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='715' u='m' c='SSL_new'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='884' u='m' c='SSL_do_handshake'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='896' u='m' c='SSL_do_handshake'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1023' u='m' c='_ZL13ssl_read_implP6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1264' u='r' c='SSL_in_early_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1267' u='m' c='SSL_in_early_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1275' u='m' c='SSL_reset_early_data_reject'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1742' u='r' c='SSL_get_extms_support'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1743' u='m' c='SSL_get_extms_support'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1804' u='r' c='SSL_renegotiate'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1808' u='w' c='SSL_renegotiate'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='1809' u='r' c='SSL_renegotiate'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2345' u='m' c='SSL_get0_alpn_selected'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2346' u='m' c='SSL_get0_alpn_selected'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2489' u='r' c='SSL_get0_certificate_types'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2490' u='m' c='SSL_get0_certificate_types'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2499' u='r' c='SSL_get0_peer_verify_algorithms'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2500' u='m' c='SSL_get0_peer_verify_algorithms'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2509' u='r' c='SSL_get0_peer_delegation_algorithms'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2510' u='m' c='SSL_get0_peer_delegation_algorithms'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2856' u='m' c='SSL_can_release_private_key'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2856' u='m' c='SSL_can_release_private_key'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2867' u='m' c='SSL_in_init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2872' u='r' c='SSL_in_false_start'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2875' u='m' c='SSL_in_false_start'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='2989' u='m' c='SSL_get_pending_cipher'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_lib.cc' l='3167' u='m' c='SSL_get_tlsext_status_type'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_session.cc' l='1085' u='m' c='SSL_get_session'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_session.cc' l='1174' u='r' c='SSL_set_session'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_session.cc' l='1175' u='m' c='SSL_set_session'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_stat.cc' l='92' u='r' c='SSL_state_string_long'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_stat.cc' l='96' u='m' c='SSL_state_string_long'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_stat.cc' l='97' u='m' c='SSL_state_string_long'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_versions.cc' l='246' u='m' c='_ZN4bsslL11ssl_versionEPK6ssl_st'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_x509.cc' l='1129' u='r' c='SSL_get_client_CA_list'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_x509.cc' l='1130' u='m' c='SSL_get_client_CA_list'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_x509.cc' l='1131' u='m' c='SSL_get_client_CA_list'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/ssl_x509.cc' l='1223' u='m' c='_ZL17do_client_cert_cbP6ssl_stPv'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/tls_method.cc' l='96' u='r' c='_ZN4bsslL18tls_set_read_stateEP6ssl_st22ssl_encryption_level_tNSt3__110unique_ptrINS_14SSLAEADContextENS_8internal7DeleterIS5_EEEENS_4SpanIKhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/tls_method.cc' l='96' u='m' c='_ZN4bsslL18tls_set_read_stateEP6ssl_st22ssl_encryption_level_tNSt3__110unique_ptrINS_14SSLAEADContextENS_8internal7DeleterIS5_EEEENS_4SpanIKhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/tls_method.cc' l='125' u='r' c='_ZN4bsslL19tls_set_write_stateEP6ssl_st22ssl_encryption_level_tNSt3__110unique_ptrINS_14SSLAEADContextENS_8internal7DeleterIS5_EEEENS_4SpanIKhEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/ssl/tls_method.cc' l='125' u='m' c='_ZN4bsslL19tls_set_write_stateEP6ssl_st22ssl_encryption_level_tNSt3__110unique_ptrINS_14SSLAEADContextENS_8internal7DeleterIS5_EEEENS_4SpanIKhEE'/>
