<def f='webkit/Source/WebCore/Modules/webauthn/WebAuthenticationConstants.h' l='32' type='const int64_t'/>
<use f='webkit/Source/WebCore/Modules/webauthn/WebAuthenticationUtils.cpp' l='55' u='r' c='_ZN7WebCore26encodeES256PublicKeyAsCBOREON3WTF6VectorIhLm0ENS0_15CrashOnOverflowELm16ENS0_10FastMallocEEES5_'/>
<doc f='webkit/Source/WebCore/Modules/webauthn/WebAuthenticationConstants.h' l='30'>// See RFC 8152 - CBOR Object Signing and Encryption &lt;https://tools.ietf.org/html/rfc8152&gt;
// Labels</doc>
<use f='webkit/Source/WebCore/Modules/webauthn/fido/Pin.cpp' l='158' u='r' c='_ZN4fido3pin20KeyAgreementResponse13parseFromCOSEERKNSt3__13mapIN4cbor9CBORValueES5_NS5_8CTAPLessEN3WTF13FastAllocatorINS2_4pairIKS5_S5_EEEEEE'/>
<use f='webkit/Source/WebCore/Modules/webauthn/fido/Pin.cpp' l='189' u='r' c='_ZN4fido3pin19encodeCOSEPublicKeyERKN3WTF6VectorIhLm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<def f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/WebAuthenticationConstants.h' l='32' type='const int64_t'/>
<doc f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/WebAuthenticationConstants.h' l='30'>// See RFC 8152 - CBOR Object Signing and Encryption &lt;https://tools.ietf.org/html/rfc8152&gt;
// Labels</doc>
