<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/ex_data.h' l='195' type='struct stack_st_void *'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='171' u='r' c='CRYPTO_set_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='172' u='w' c='CRYPTO_set_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='173' u='r' c='CRYPTO_set_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='179' u='r' c='CRYPTO_set_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='183' u='r' c='CRYPTO_set_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='189' u='r' c='CRYPTO_set_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='194' u='r' c='CRYPTO_get_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='194' u='r' c='CRYPTO_get_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='197' u='r' c='CRYPTO_get_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='229' u='w' c='CRYPTO_new_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='234' u='r' c='CRYPTO_free_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='257' u='r' c='CRYPTO_free_ex_data'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/ex_data.c' l='258' u='w' c='CRYPTO_free_ex_data'/>
