<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/ec_key.h' l='276' type='int (*)(EC_KEY *)'/>
<offset>128</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/ec/ec_key.c' l='129' u='r' c='EC_KEY_new_method'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/ec/ec_key.c' l='129' u='r' c='EC_KEY_new_method'/>
