<dec f='webkit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.h' l='145' type='0'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='511' u='r' c='_ZN2gl10FromGLenumEj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='525' c='_ZN2gl8ToGLenumENS_7FogModeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='541' c='_ZN2gllsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEENS_7FogModeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/GLES1State.cpp' l='153' u='r' c='_ZN2gl10GLES1State10initializeEPKNS_7ContextEPKNS_5StateE'/>
