<use f='webkit/Source/ThirdParty/ANGLE/src/common/PackedEnums.h' l='590'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ResourceManager.h' l='157' c='_ZNK2gl20ShaderProgramManager9getShaderENS_15ShaderProgramIDE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ResourceManager.h' l='168' c='_ZNK2gl20ShaderProgramManager20getShadersForCaptureEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ResourceManager.h' l='185'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.h' l='68' c='_ZN2gl13UniformLinker36flattenUniformsAndCheckCapsForShaderEPNS_6ShaderERKNS_4CapsERNSt3__16vectorINS_13LinkedUniformENS6_9allocatorIS8_EEEESC_SC_RNS76359670'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Shader.h' l='113'/>
<inh f='webkit/Source/ThirdParty/ANGLE/src/common/angleutils.h' l='43' c='angle::NonCopyable'/>
<inh f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Debug.h' l='25' c='gl::LabeledObject'/>
<def f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Shader.h' l='148' ll='260'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='211' c='_ZNK2gl12ProgramState17getAttachedShaderENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='212' c='_ZNK2gl12ProgramState18getAttachedShadersEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='393'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='481' c='_ZN2gl7Program12attachShaderEPKNS_7ContextEPNS_6ShaderE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='482' c='_ZN2gl7Program12detachShaderEPKNS_7ContextEPNS_6ShaderE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='485' c='_ZNK2gl7Program17getAttachedShaderENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.h' l='564' c='_ZNK2gl7Context9getShaderENS_15ShaderProgramIDE'/>
<size>456</size>
<fun r='_ZN2gl6ShaderC1EPNS_20ShaderProgramManagerEPN2rx13GLImplFactoryERKNS_11LimitationsENS_10ShaderTypeENS_15ShaderProgramIDE'/>
<fun r='_ZN2gl6Shader9onDestroyEPKNS_7ContextE'/>
<fun r='_ZN2gl6Shader8setLabelEPKNS_7ContextERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE'/>
<fun r='_ZNK2gl6Shader8getLabelEv'/>
<fun r='_ZNK2gl6Shader7getTypeEv'/>
<fun r='_ZNK2gl6Shader9getHandleEv'/>
<fun r='_ZNK2gl6Shader17getImplementationEv'/>
<fun r='_ZN2gl6Shader9setSourceEiPKPKcPKi'/>
<fun r='_ZN2gl6Shader16getInfoLogLengthEv'/>
<fun r='_ZN2gl6Shader10getInfoLogEiPiPc'/>
<fun r='_ZNK2gl6Shader16getInfoLogStringEv'/>
<fun r='_ZNK2gl6Shader15getSourceLengthEv'/>
<fun r='_ZNK2gl6Shader15getSourceStringEv'/>
<fun r='_ZNK2gl6Shader9getSourceEiPiPc'/>
<fun r='_ZN2gl6Shader25getTranslatedSourceLengthEv'/>
<fun r='_ZN2gl6Shader38getTranslatedSourceWithDebugInfoLengthEv'/>
<fun r='_ZN2gl6Shader19getTranslatedSourceEv'/>
<fun r='_ZN2gl6Shader19getTranslatedSourceEiPiPc'/>
<fun r='_ZN2gl6Shader32getTranslatedSourceWithDebugInfoEiPiPc'/>
<fun r='_ZN2gl6Shader7compileEPKNS_7ContextE'/>
<fun r='_ZN2gl6Shader10isCompiledEv'/>
<fun r='_ZN2gl6Shader11isCompletedEv'/>
<fun r='_ZN2gl6Shader6addRefEv'/>
<fun r='_ZN2gl6Shader7releaseEPKNS_7ContextE'/>
<fun r='_ZNK2gl6Shader11getRefCountEv'/>
<fun r='_ZNK2gl6Shader20isFlaggedForDeletionEv'/>
<fun r='_ZN2gl6Shader15flagForDeletionEv'/>
<fun r='_ZNK2gl6Shader33hasEarlyFragmentTestsOptimizationEv'/>
<fun r='_ZN2gl6Shader16getShaderVersionEv'/>
<fun r='_ZN2gl6Shader16getInputVaryingsEv'/>
<fun r='_ZN2gl6Shader17getOutputVaryingsEv'/>
<fun r='_ZN2gl6Shader11getUniformsEv'/>
<fun r='_ZN2gl6Shader16getUniformBlocksEv'/>
<fun r='_ZN2gl6Shader22getShaderStorageBlocksEv'/>
<fun r='_ZN2gl6Shader19getActiveAttributesEv'/>
<fun r='_ZN2gl6Shader16getAllAttributesEv'/>
<fun r='_ZN2gl6Shader24getActiveOutputVariablesEv'/>
<fun r='_ZN2gl6Shader37getTransformFeedbackVaryingMappedNameERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<fun r='_ZN2gl6Shader16getWorkGroupSizeEv'/>
<fun r='_ZN2gl6Shader11getNumViewsEv'/>
<fun r='_ZN2gl6Shader35getGeometryShaderInputPrimitiveTypeEv'/>
<fun r='_ZN2gl6Shader36getGeometryShaderOutputPrimitiveTypeEv'/>
<fun r='_ZN2gl6Shader28getGeometryShaderInvocationsEv'/>
<fun r='_ZN2gl6Shader28getGeometryShaderMaxVerticesEv'/>
<fun r='_ZNK2gl6Shader26getCompilerResourcesStringEv'/>
<fun r='_ZNK2gl6Shader8getStateEv'/>
<fun r='_ZNK2gl6Shader40getCurrentMaxComputeWorkGroupInvocationsEv'/>
<fun r='_ZNK2gl6Shader25getMaxComputeSharedMemoryEv'/>
<fun r='_ZNK2gl6Shader14hasBeenDeletedEv'/>
<fun r='_ZN2gl6ShaderD1Ev'/>
<fun r='_ZN2gl6Shader13GetSourceImplERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEiPiPc'/>
<fun r='_ZN2gl6Shader14resolveCompileEv'/>
<mbr r='gl::Shader::mState' o='64' t='gl::ShaderState'/>
<mbr r='gl::Shader::mImplementation' o='2624' t='std::unique_ptr&lt;rx::ShaderImpl&gt;'/>
<mbr r='gl::Shader::mRendererLimitations' o='2688' t='const gl::Limitations'/>
<mbr r='gl::Shader::mHandle' o='2784' t='const gl::ShaderProgramID'/>
<mbr r='gl::Shader::mType' o='2816' t='const gl::ShaderType'/>
<mbr r='gl::Shader::mRefCount' o='2848' t='unsigned int'/>
<mbr r='gl::Shader::mDeleteStatus' o='2880' t='bool'/>
<mbr r='gl::Shader::mInfoLog' o='2944' t='std::string'/>
<mbr r='gl::Shader::mBoundCompiler' o='3136' t='BindingPointer&lt;gl::Compiler&gt;'/>
<mbr r='gl::Shader::mCompilingState' o='3264' t='std::unique_ptr&lt;CompilingState&gt;'/>
<mbr r='gl::Shader::mCompilerResourcesString' o='3328' t='std::string'/>
<mbr r='gl::Shader::mResourceManager' o='3520' t='gl::ShaderProgramManager *'/>
<mbr r='gl::Shader::mCurrentMaxComputeWorkGroupInvocations' o='3584' t='GLuint'/>
<mbr r='gl::Shader::mMaxComputeSharedMemory' o='3616' t='unsigned int'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/GLES1Renderer.h' l='58' c='_ZNK2gl13GLES1Renderer9getShaderENS_15ShaderProgramIDE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.h' l='51' c='_ZN2gl13QueryShaderivEPKNS_7ContextEPNS_6ShaderEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES.h' l='101' c='_ZN2gl14GetValidShaderEPKNS_7ContextENS_15ShaderProgramIDE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='788' c='_ZN2gl7Context20createShaderProgramvENS_10ShaderTypeEiPKPKc'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='5651' c='_ZN2gl7Context12attachShaderENS_15ShaderProgramIDES1_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='6178' c='_ZN2gl7Context13compileShaderENS_15ShaderProgramIDE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='6229' c='_ZN2gl7Context12detachShaderENS_15ShaderProgramIDES1_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='6443' c='_ZN2gl7Context11getShaderivENS_15ShaderProgramIDEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='6466' c='_ZN2gl7Context16getShaderInfoLogENS_15ShaderProgramIDEiPiPc'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='6549' c='_ZN2gl7Context15getShaderSourceENS_15ShaderProgramIDEiPiPc'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='6721' c='_ZN2gl7Context12shaderSourceENS_15ShaderProgramIDEiPKPKcPKi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='7861' c='_ZN2gl7Context25getTranslatedShaderSourceENS_15ShaderProgramIDEiPiPc'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='8374' c='_ZNK2gl7Context9getShaderENS_15ShaderProgramIDE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/GLES1Renderer.cpp' l='506' c='_ZNK2gl13GLES1Renderer9getShaderENS_15ShaderProgramIDE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/GLES1Renderer.cpp' l='526' c='_ZN2gl13GLES1Renderer13compileShaderEPNS_7ContextENS_10ShaderTypeEPKcPNS_15ShaderProgramIDE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/MemoryProgramCache.cpp' l='51' c='_ZN2gl12_GLOBAL__N_1lsERNS0_10HashStreamEPKNS_6ShaderE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='388' c='_ZN2gl12_GLOBAL__N_122InitUniformBlockLinkerERKNS_12ProgramStateEPNS_18UniformBlockLinkerE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='400' c='_ZN2gl12_GLOBAL__N_128InitShaderStorageBlockLinkerERKNS_12ProgramStateEPNS_24ShaderStorageBlockLinkerE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1110' c='_ZNK2gl12ProgramState17getAttachedShaderENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1186' c='_ZNK2gl12ProgramState17hasAttachedShaderEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1284' c='_ZN2gl7Program12attachShaderEPKNS_7ContextEPNS_6ShaderE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1303' c='_ZN2gl7Program12detachShaderEPKNS_7ContextEPNS_6ShaderE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1329' c='_ZNK2gl7Program23getAttachedShadersCountEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1340' c='_ZNK2gl7Program17getAttachedShaderENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1568' c='_ZN2gl7Program8linkImplEPKNS_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1574' c='_ZN2gl7Program8linkImplEPKNS_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1680' c='_ZN2gl7Program24updateLinkedShaderStagesEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1740' c='_ZN2gl12ProgramState28updateProgramInterfaceInputsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1796' c='_ZN2gl12ProgramState29updateProgramInterfaceOutputsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='2037' c='_ZNK2gl7Program18getAttachedShadersEiPiPNS_15ShaderProgramIDE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3253' c='_ZN2gl7Program19linkValidateShadersERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3254' c='_ZN2gl7Program19linkValidateShadersERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3255' c='_ZN2gl7Program19linkValidateShadersERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3256' c='_ZN2gl7Program19linkValidateShadersERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3480' c='_ZNK2gl7Program12linkVaryingsERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3488' c='_ZNK2gl7Program12linkVaryingsERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3503' c='_ZNK2gl7Program12linkVaryingsERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3504' c='_ZNK2gl7Program12linkVaryingsERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3817' c='_ZN2gl7Program14linkAttributesEPKNS_7ContextERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3982' c='_ZN2gl7Program19linkInterfaceBlocksERKNS_4CapsERKNS_7VersionEbRNS_7InfoLogEPj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='4024' c='_ZN2gl7Program19linkInterfaceBlocksERKNS_4CapsERKNS_7VersionEbRNS_7InfoLogEPj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='4436' c='_ZNK2gl7Program17getMergedVaryingsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='4465' c='_ZNK2gl7Program17getMergedVaryingsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='4620' c='_ZN2gl7Program19linkOutputVariablesERKNS_4CapsERKNS_10ExtensionsERKNS_7VersionEjj'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.cpp' l='395' c='_ZNK2gl17ProgramExecutable23linkValidateGlobalNamesERNS_7InfoLogERKN5angle13PackedEnumMapINS_10ShaderTypeEPKNS_12ProgramStateELm4EEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.cpp' l='473' c='_ZNK2gl17ProgramExecutable23linkValidateGlobalNamesERNS_7InfoLogERKN5angle13PackedEnumMapINS_10ShaderTypeEPKNS_12ProgramStateELm4EEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.cpp' l='511' c='_ZN2gl17ProgramExecutable19saveLinkedStateInfoERKNS_12ProgramStateE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.cpp' l='90' c='_ZN2gl12_GLOBAL__N_133ValidateGraphicsUniformsPerShaderEPNS_6ShaderEbPNSt3__13mapINS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEENS3_4pa10189381'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.cpp' l='717' c='_ZNK2gl13UniformLinker24validateGraphicsUniformsERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.cpp' l='928' c='_ZN2gl13UniformLinker36flattenUniformsAndCheckCapsForShaderEPNS_6ShaderERKNS_4CapsERNSt3__16vectorINS_13LinkedUniformENS6_9allocatorIS8_EEEESC_SC_RNS76359670'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.cpp' l='1013' c='_ZN2gl13UniformLinker27flattenUniformsAndCheckCapsERKNS_4CapsERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.cpp' l='1275' c='_ZNK2gl28ProgramLinkedResourcesLinker13linkResourcesERKNS_12ProgramStateERKNS_22ProgramLinkedResourcesE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.cpp' l='1300' c='_ZNK2gl28ProgramLinkedResourcesLinker13linkResourcesERKNS_12ProgramStateERKNS_22ProgramLinkedResourcesE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramPipeline.cpp' l='462' c='_ZNK2gl15ProgramPipeline17getMergedVaryingsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramPipeline.cpp' l='491' c='_ZNK2gl15ProgramPipeline17getMergedVaryingsEv'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ResourceManager.cpp' l='168' c='_ZN2gl20ShaderProgramManager12createShaderEPN2rx13GLImplFactoryERKNS_11LimitationsENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ResourceManager.cpp' l='177' c='_ZNK2gl20ShaderProgramManager9getShaderENS_15ShaderProgramIDE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/frame_capture_utils.cpp' l='663' c='_ZN5angle12_GLOBAL__N_115SerializeShaderEPN2gl18BinaryOutputStreamEPNS1_6ShaderE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/frame_capture_utils.cpp' l='730' c='_ZN5angle12_GLOBAL__N_121SerializeProgramStateEPN2gl18BinaryOutputStreamERKNS1_12ProgramStateE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/frame_capture_utils.cpp' l='986' c='_ZN5angle16SerializeContextEPN2gl18BinaryOutputStreamEPKNS0_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/frame_capture_utils.cpp' l='990' c='_ZN5angle16SerializeContextEPN2gl18BinaryOutputStreamEPKNS0_7ContextE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='1418' c='_ZN2gl13QueryShaderivEPKNS_7ContextEPNS_6ShaderEjPi'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/ProgramGL.cpp' l='278' c='_ZN2rx9ProgramGL4linkEPKN2gl7ContextERKNS1_22ProgramLinkedResourcesERNS1_7InfoLogERKNSt3__16vectorINS1_17ProgramVaryingRefENSA_9allocatorISC_EEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/ProgramGL.cpp' l='302' c='_ZN2rx9ProgramGL4linkEPKN2gl7ContextERKNS1_22ProgramLinkedResourcesERNS1_7InfoLogERKNSt3__16vectorINS1_17ProgramVaryingRefENSA_9allocatorISC_EEEE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ProgramMtl.mm' l='72' c='_ZN2rx12_GLOBAL__N_123InitDefaultUniformBlockERKNSt3__16vectorIN2sh14ShaderVariableENS1_9allocatorIS4_EEEEPN2gl6ShaderEPNS1_3mapINS1_12basic_stringIcN16893'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ProgramMtl.mm' l='510' c='_ZN2rx10ProgramMtl24initDefaultUniformBlocksEPKN2gl7ContextE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_glslang_mtl_utils.mm' l='114' c='_ZN2rx3mtl18MSLGetShaderSourceERKN2gl12ProgramStateERKNS1_22ProgramLinkedResourcesEPN5angle13PackedEnumMapINS1_10ShaderTypeENSt3__112basic_stringIcNSB3387621'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_glslang_mtl_utils.mm' l='154' c='_ZN2rx3mtl23getReflectionFromShaderEPN2gl6ShaderE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_glslang_mtl_utils.mm' l='430' c='_ZN2rx3mtl13GlslangGetMSLEPKN2gl7ContextERKNS1_12ProgramStateERKNS1_4CapsERKN5angle13PackedEnumMapINS1_10ShaderTypeENSt3__112basic_stringIcNSE_11char_2384666'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES.cpp' l='1244' c='_ZN2gl14GetValidShaderEPKNS_7ContextENS_15ShaderProgramIDE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES.cpp' l='1248' c='_ZN2gl14GetValidShaderEPKNS_7ContextENS_15ShaderProgramIDE'/>
<size>456</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='3941' c='_ZN2gl20ValidateAttachShaderEPKNS_7ContextENS_15ShaderProgramIDES3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='4397' c='_ZN2gl20ValidateDetachShaderEPKNS_7ContextENS_15ShaderProgramIDES3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='4403' c='_ZN2gl20ValidateDetachShaderEPKNS_7ContextENS_15ShaderProgramIDES3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='4630' c='_ZN2gl24ValidateGetShaderInfoLogEPKNS_7ContextENS_15ShaderProgramIDEiPKiPKc'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='4688' c='_ZN2gl23ValidateGetShaderSourceEPKNS_7ContextENS_15ShaderProgramIDEiPKiPKc'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='4970' c='_ZN2gl20ValidateShaderSourceEPKNS_7ContextENS_15ShaderProgramIDEiPKPKcPKi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='6072' c='_ZN2gl38ValidateGetTranslatedShaderSourceANGLEEPKNS_7ContextENS_15ShaderProgramIDEiPKiPKc'/>
<size>456</size>
