<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='960' ll='993'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='964' c='_ZN9Inspector8Protocol10Automation16InputSourceState7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='966' c='_ZN9Inspector8Protocol10Automation16InputSourceState7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='977' c='_ZN9Inspector8Protocol10Automation16InputSourceState7Builder11setSourceIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='1001' c='_ZN9Inspector8Protocol10Automation16InputSourceState6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='1003' c='_ZN9Inspector8Protocol10Automation16InputSourceState6createEv'/>
<mbr r='Inspector::Protocol::Automation::InputSourceState::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation16InputSourceState7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation16InputSourceState7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation16InputSourceState7Builder11setSourceIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10Automation16InputSourceState7Builder7releaseEv'/>
