<dec f='webkit/Source/WebCore/inspector/InspectorDebuggableType.h' l='32' type='1'/>
<use f='webkit/Source/WebCore/inspector/InspectorDebuggableType.h' l='46'/>
<doc f='webkit/Source/WebCore/inspector/InspectorDebuggableType.h' l='32'>// JSC::JSGlobalObject</doc>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/InspectorDebuggableType.h' l='32' type='1'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/InspectorDebuggableType.h' l='46'/>
<doc f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/InspectorDebuggableType.h' l='32'>// JSC::JSGlobalObject</doc>
<use f='webkit/Source/WebCore/inspector/InspectorFrontendHost.cpp' l='344' c='_ZN7WebCoreL22debuggableTypeToStringEN9Inspector14DebuggableTypeE'/>
<use f='webkit/Source/WebCore/inspector/InspectorFrontendHost.cpp' l='361' u='r' c='_ZNK7WebCore21InspectorFrontendHost14debuggableInfoEv'/>
<use f='webkit/Source/WebKit/UIProcess/API/Cocoa/_WKInspectorDebuggableInfoInternal.h' l='51' u='r' c='_Z29fromWKInspectorDebuggableType26_WKInspectorDebuggableType'/>
<use f='webkit/Source/WebKit/UIProcess/API/Cocoa/_WKInspectorDebuggableInfoInternal.h' l='61' u='r' c='_Z29fromWKInspectorDebuggableType26_WKInspectorDebuggableType'/>
<use f='webkit/Source/WebKit/UIProcess/API/Cocoa/_WKInspectorDebuggableInfoInternal.h' l='69' c='_Z27toWKInspectorDebuggableTypeN9Inspector14DebuggableTypeE'/>
