<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7485' ll='7518'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7489' c='_ZN9Inspector8Protocol7Network9Initiator7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7491' c='_ZN9Inspector8Protocol7Network9Initiator7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7502' c='_ZN9Inspector8Protocol7Network9Initiator7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7526' c='_ZN9Inspector8Protocol7Network9Initiator6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7528' c='_ZN9Inspector8Protocol7Network9Initiator6createEv'/>
<mbr r='Inspector::Protocol::Network::Initiator::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network9Initiator7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network9Initiator7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network9Initiator7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol7Network9Initiator7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7485' ll='7518'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7489' c='_ZN9Inspector8Protocol7Network9Initiator7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7491' c='_ZN9Inspector8Protocol7Network9Initiator7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7502' c='_ZN9Inspector8Protocol7Network9Initiator7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7526' c='_ZN9Inspector8Protocol7Network9Initiator6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7528' c='_ZN9Inspector8Protocol7Network9Initiator6createEv'/>
<mbr r='Inspector::Protocol::Network::Initiator::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network9Initiator7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network9Initiator7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network9Initiator7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol7Network9Initiator7Builder7releaseEv'/>
