<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='600' ll='633'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='604' c='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='606' c='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='617' c='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9setOffsetEd'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='641' c='_ZN9Inspector8Protocol9Animation8Keyframe6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='643' c='_ZN9Inspector8Protocol9Animation8Keyframe6createEv'/>
<mbr r='Inspector::Protocol::Animation::Keyframe::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Animation8Keyframe7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9setOffsetEd'/>
<fun r='_ZN9Inspector8Protocol9Animation8Keyframe7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='600' ll='633'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='604' c='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='606' c='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='617' c='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9setOffsetEd'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='641' c='_ZN9Inspector8Protocol9Animation8Keyframe6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='643' c='_ZN9Inspector8Protocol9Animation8Keyframe6createEv'/>
<mbr r='Inspector::Protocol::Animation::Keyframe::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Animation8Keyframe7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Animation8Keyframe7Builder9setOffsetEd'/>
<fun r='_ZN9Inspector8Protocol9Animation8Keyframe7Builder7releaseEv'/>
