<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3350' ll='3411'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3354' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3356' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3367' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder15setFunctionNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3374' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder6setUrlERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3381' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder11setScriptIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3388' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder13setLineNumberEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3395' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder15setColumnNumberEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3423' c='_ZN9Inspector8Protocol7Console9CallFrame6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3425' c='_ZN9Inspector8Protocol7Console9CallFrame6createEv'/>
<mbr r='Inspector::Protocol::Console::CallFrame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder15setFunctionNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder11setScriptIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder13setLineNumberEi'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder15setColumnNumberEi'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3350' ll='3411'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3354' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3356' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3367' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder15setFunctionNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3374' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder6setUrlERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3381' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder11setScriptIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3388' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder13setLineNumberEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3395' c='_ZN9Inspector8Protocol7Console9CallFrame7Builder15setColumnNumberEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3423' c='_ZN9Inspector8Protocol7Console9CallFrame6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3425' c='_ZN9Inspector8Protocol7Console9CallFrame6createEv'/>
<mbr r='Inspector::Protocol::Console::CallFrame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder15setFunctionNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder11setScriptIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder13setLineNumberEi'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder15setColumnNumberEi'/>
<fun r='_ZN9Inspector8Protocol7Console9CallFrame7Builder7releaseEv'/>
