<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='107' ll='147'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='111' c='_ZN9Inspector8Protocol10Automation5Point7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='113' c='_ZN9Inspector8Protocol10Automation5Point7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='124' c='_ZN9Inspector8Protocol10Automation5Point7Builder4setXEd'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='131' c='_ZN9Inspector8Protocol10Automation5Point7Builder4setYEd'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='156' c='_ZN9Inspector8Protocol10Automation5Point6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='158' c='_ZN9Inspector8Protocol10Automation5Point6createEv'/>
<mbr r='Inspector::Protocol::Automation::Point::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation5Point7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation5Point7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation5Point7Builder4setXEd'/>
<fun r='_ZN9Inspector8Protocol10Automation5Point7Builder4setYEd'/>
<fun r='_ZN9Inspector8Protocol10Automation5Point7Builder7releaseEv'/>
