<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2471' ll='2511'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2475' c='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2477' c='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2488' c='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2495' c='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder8setValueERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2520' c='_ZN9Inspector8Protocol3CSS11CSSProperty6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2522' c='_ZN9Inspector8Protocol3CSS11CSSProperty6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSProperty::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2471' ll='2511'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2475' c='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2477' c='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2488' c='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2495' c='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder8setValueERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2520' c='_ZN9Inspector8Protocol3CSS11CSSProperty6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2522' c='_ZN9Inspector8Protocol3CSS11CSSProperty6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSProperty::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSProperty7Builder7releaseEv'/>
