<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8731' ll='8764'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8735' c='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8737' c='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8748' c='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder8setValueEON3WTF3RefINS1_13ObjectPreviewENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8772' c='_ZN9Inspector8Protocol7Runtime12EntryPreview6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8774' c='_ZN9Inspector8Protocol7Runtime12EntryPreview6createEv'/>
<mbr r='Inspector::Protocol::Runtime::EntryPreview::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime12EntryPreview7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder8setValueEON3WTF3RefINS1_13ObjectPreviewENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8731' ll='8764'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8735' c='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8737' c='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8748' c='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder8setValueEON3WTF3RefINS1_13ObjectPreviewENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8772' c='_ZN9Inspector8Protocol7Runtime12EntryPreview6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8774' c='_ZN9Inspector8Protocol7Runtime12EntryPreview6createEv'/>
<mbr r='Inspector::Protocol::Runtime::EntryPreview::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime12EntryPreview7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder8setValueEON3WTF3RefINS1_13ObjectPreviewENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12EntryPreview7Builder7releaseEv'/>
