<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='6564' type='55'/>
<dec f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='6564' type='55'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.cpp' l='835' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/inspector/agents/InspectorMemoryAgent.cpp' l='125' u='r' c='_ZN7WebCore20InspectorMemoryAgent13collectSampleERKNS_17ResourceUsageDataE'/>
