<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='172' ll='212'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='176' c='_ZN9Inspector8Protocol10Automation4Size7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='178' c='_ZN9Inspector8Protocol10Automation4Size7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='189' c='_ZN9Inspector8Protocol10Automation4Size7Builder8setWidthEd'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='196' c='_ZN9Inspector8Protocol10Automation4Size7Builder9setHeightEd'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='221' c='_ZN9Inspector8Protocol10Automation4Size6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='223' c='_ZN9Inspector8Protocol10Automation4Size6createEv'/>
<mbr r='Inspector::Protocol::Automation::Size::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation4Size7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation4Size7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation4Size7Builder8setWidthEd'/>
<fun r='_ZN9Inspector8Protocol10Automation4Size7Builder9setHeightEd'/>
<fun r='_ZN9Inspector8Protocol10Automation4Size7Builder7releaseEv'/>
