<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2822' type='50'/>
<dec f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2822' type='50'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.cpp' l='490' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/inspector/InspectorShaderProgram.cpp' l='244' u='a' c='_ZN7WebCore22InspectorShaderProgram27buildObjectForShaderProgramEv'/>
