<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8647' ll='8687'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8651' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8653' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8664' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8671' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8696' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8698' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview6createEv'/>
<mbr r='Inspector::Protocol::Runtime::PropertyPreview::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8647' ll='8687'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8651' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8653' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8664' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8671' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8696' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8698' c='_ZN9Inspector8Protocol7Runtime15PropertyPreview6createEv'/>
<mbr r='Inspector::Protocol::Runtime::PropertyPreview::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15PropertyPreview7Builder7releaseEv'/>
