<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1227' ll='1267'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1231' c='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1233' c='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1244' c='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1251' c='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder10setOrdinalEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1276' c='_ZN9Inspector8Protocol3CSS10CSSStyleId6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1278' c='_ZN9Inspector8Protocol3CSS10CSSStyleId6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyleId::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder10setOrdinalEi'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1227' ll='1267'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1231' c='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1233' c='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1244' c='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1251' c='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder10setOrdinalEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1276' c='_ZN9Inspector8Protocol3CSS10CSSStyleId6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1278' c='_ZN9Inspector8Protocol3CSS10CSSStyleId6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyleId::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder10setOrdinalEi'/>
<fun r='_ZN9Inspector8Protocol3CSS10CSSStyleId7Builder7releaseEv'/>
