<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='753' ll='800'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='757' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='759' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='770' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder6setUrlERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='777' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7setSizeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='784' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7setTypeERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='810' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='812' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource6createEv'/>
<mbr r='Inspector::Protocol::ApplicationCache::ApplicationCacheResource::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7setSizeEi'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7setTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='753' ll='800'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='757' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='759' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='770' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder6setUrlERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='777' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7setSizeEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='784' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7setTypeERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='810' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='812' c='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource6createEv'/>
<mbr r='Inspector::Protocol::ApplicationCache::ApplicationCacheResource::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7setSizeEi'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7setTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache24ApplicationCacheResource7Builder7releaseEv'/>
