<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2844' ll='2870'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2848' c='_ZN9Inspector8Protocol6Canvas17ContextAttributes7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2850' c='_ZN9Inspector8Protocol6Canvas17ContextAttributes7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2877' c='_ZN9Inspector8Protocol6Canvas17ContextAttributes6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2879' c='_ZN9Inspector8Protocol6Canvas17ContextAttributes6createEv'/>
<mbr r='Inspector::Protocol::Canvas::ContextAttributes::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Canvas17ContextAttributes7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Canvas17ContextAttributes7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Canvas17ContextAttributes7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2844' ll='2870'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2848' c='_ZN9Inspector8Protocol6Canvas17ContextAttributes7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2850' c='_ZN9Inspector8Protocol6Canvas17ContextAttributes7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2877' c='_ZN9Inspector8Protocol6Canvas17ContextAttributes6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2879' c='_ZN9Inspector8Protocol6Canvas17ContextAttributes6createEv'/>
<mbr r='Inspector::Protocol::Canvas::ContextAttributes::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Canvas17ContextAttributes7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Canvas17ContextAttributes7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Canvas17ContextAttributes7Builder7releaseEv'/>
