<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='10127' ll='10153'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='10131' c='_ZN9Inspector8Protocol8Security11Certificate7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='10133' c='_ZN9Inspector8Protocol8Security11Certificate7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='10160' c='_ZN9Inspector8Protocol8Security11Certificate6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='10162' c='_ZN9Inspector8Protocol8Security11Certificate6createEv'/>
<mbr r='Inspector::Protocol::Security::Certificate::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Security11Certificate7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Security11Certificate7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Security11Certificate7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='10127' ll='10153'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='10131' c='_ZN9Inspector8Protocol8Security11Certificate7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='10133' c='_ZN9Inspector8Protocol8Security11Certificate7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='10160' c='_ZN9Inspector8Protocol8Security11Certificate6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='10162' c='_ZN9Inspector8Protocol8Security11Certificate6createEv'/>
<mbr r='Inspector::Protocol::Security::Certificate::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Security11Certificate7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Security11Certificate7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Security11Certificate7Builder7releaseEv'/>
