<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='237' ll='277'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='241' c='_ZN9Inspector8Protocol10Automation4Rect7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='243' c='_ZN9Inspector8Protocol10Automation4Rect7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='254' c='_ZN9Inspector8Protocol10Automation4Rect7Builder9setOriginEON3WTF3RefINS1_5PointENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='261' c='_ZN9Inspector8Protocol10Automation4Rect7Builder7setSizeEON3WTF3RefINS1_4SizeENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='286' c='_ZN9Inspector8Protocol10Automation4Rect6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='288' c='_ZN9Inspector8Protocol10Automation4Rect6createEv'/>
<mbr r='Inspector::Protocol::Automation::Rect::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation4Rect7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation4Rect7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation4Rect7Builder9setOriginEON3WTF3RefINS1_5PointENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation4Rect7Builder7setSizeEON3WTF3RefINS1_4SizeENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation4Rect7Builder7releaseEv'/>
