<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5777' ll='5810'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5781' c='_ZN9Inspector8Protocol9IndexedDB3Key7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5783' c='_ZN9Inspector8Protocol9IndexedDB3Key7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5794' c='_ZN9Inspector8Protocol9IndexedDB3Key7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5818' c='_ZN9Inspector8Protocol9IndexedDB3Key6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5820' c='_ZN9Inspector8Protocol9IndexedDB3Key6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::Key::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB3Key7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB3Key7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB3Key7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB3Key7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5777' ll='5810'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5781' c='_ZN9Inspector8Protocol9IndexedDB3Key7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5783' c='_ZN9Inspector8Protocol9IndexedDB3Key7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5794' c='_ZN9Inspector8Protocol9IndexedDB3Key7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5818' c='_ZN9Inspector8Protocol9IndexedDB3Key6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5820' c='_ZN9Inspector8Protocol9IndexedDB3Key6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::Key::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB3Key7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB3Key7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB3Key7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB3Key7Builder7releaseEv'/>
