<dec f='webkit/Source/JavaScriptCore/parser/SourceProvider.h' l='46' type='1'/>
<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/SourceProvider.h' l='46' type='1'/>
<use f='webkit/Source/WebCore/dom/ScriptElement.cpp' l='366' u='r' c='_ZN7WebCore13ScriptElement19requestModuleScriptERKN3WTF12TextPositionE'/>
<use f='webkit/Source/WebCore/workers/WorkerThread.cpp' l='136' u='r' c='_ZN7WebCore12WorkerThread25evaluateScriptIfNecessaryERN3WTF6StringE'/>
<use f='webkit/Source/WebCore/bindings/js/ScriptModuleLoader.cpp' l='413' u='r' c='_ZN7WebCore18ScriptModuleLoader14notifyFinishedERNS_18ModuleScriptLoaderEON3WTF3URLENS3_3RefINS_15DeferredPromiseENS3_12RawPtrTraitsIS7_EEEE'/>
<use f='webkit/Source/WebCore/bindings/js/ScriptModuleLoader.cpp' l='461' u='r' c='_ZN7WebCore18ScriptModuleLoader14notifyFinishedERNS_18ModuleScriptLoaderEON3WTF3URLENS3_3RefINS_15DeferredPromiseENS3_12RawPtrTraitsIS7_EEEE'/>
