<dec f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='296' type='0'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='749' c='_ZN3JSC14ARM64Assembler3addENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='764' u='r' c='_ZN3JSC14ARM64Assembler3addENS_14ARM64Registers10RegisterIDES2_S2_NS0_9ShiftTypeEi'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='785' c='_ZN3JSC14ARM64Assembler4and_ENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='863' c='_ZN3JSC14ARM64Assembler3bicENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1070' c='_ZN3JSC14ARM64Assembler3eonENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1083' c='_ZN3JSC14ARM64Assembler3eorENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1651' c='_ZN3JSC14ARM64Assembler3ornENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1664' c='_ZN3JSC14ARM64Assembler3orrENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1983' c='_ZN3JSC14ARM64Assembler3subENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/MacroAssemblerARM64.h' l='1884' u='r' c='_ZN3JSC19MacroAssemblerARM6419getEffectiveAddressENS_22AbstractMacroAssemblerINS_14ARM64AssemblerEE9BaseIndexENS_14ARM64Registers10RegisterIDE'/>
<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='296' type='0'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='749' c='_ZN3JSC14ARM64Assembler3addENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='764' u='r' c='_ZN3JSC14ARM64Assembler3addENS_14ARM64Registers10RegisterIDES2_S2_NS0_9ShiftTypeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='785' c='_ZN3JSC14ARM64Assembler4and_ENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='863' c='_ZN3JSC14ARM64Assembler3bicENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1070' c='_ZN3JSC14ARM64Assembler3eonENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1083' c='_ZN3JSC14ARM64Assembler3eorENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1651' c='_ZN3JSC14ARM64Assembler3ornENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1664' c='_ZN3JSC14ARM64Assembler3orrENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1983' c='_ZN3JSC14ARM64Assembler3subENS_14ARM64Registers10RegisterIDES2_S2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/MacroAssemblerARM64.h' l='1884' u='r' c='_ZN3JSC19MacroAssemblerARM6419getEffectiveAddressENS_22AbstractMacroAssemblerINS_14ARM64AssemblerEE9BaseIndexENS_14ARM64Registers10RegisterIDE'/>
