<dec f='webkit/Source/JavaScriptCore/runtime/IntlObject.h' l='49' type='2'/>
<use f='webkit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='179' c='_ZN3JSC18IntlDateTimeFormat10localeDataERKN3WTF6StringENS_20RelevantExtensionKeyE'/>
<use f='webkit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='562' u='r' c='_ZN3JSC18IntlDateTimeFormat24initializeDateTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='webkit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='566' u='r' c='_ZN3JSC18IntlDateTimeFormat24initializeDateTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='webkit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='570' u='r' c='_ZN3JSC18IntlDateTimeFormat24initializeDateTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='webkit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='586' u='r' c='_ZN3JSC18IntlDateTimeFormat24initializeDateTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
