<dec f='webkit/Source/JavaScriptCore/b3/B3Opcode.h' l='90' type='18'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Kind.h' l='96' c='_ZNK3JSC2B34Kind10hasIsChillEv'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Value.h' l='437' c='_ZN3JSC2B35Value18adjacencyListSpaceENS0_4KindE'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Value.h' l='602' c='_ZN3JSC2B35Value18numChildrenForKindENS0_4KindEj'/>
<doc f='webkit/Source/JavaScriptCore/b3/B3Opcode.h' l='90'>// All bets are off as to what will happen when you execute this for -2^31%-1 and x%0.</doc>
<use f='webkit/Source/JavaScriptCore/b3/B3ValueInlines.h' l='90' c='_ZNK3JSC2B35Value19adjacencyListOffsetEv'/>
<use f='webkit/Source/JavaScriptCore/b3/B3ValueInlines.h' l='90' c='_ZNK3JSC2B35Value9cloneImplEv'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1711' u='r' c='_Z16testModArgDoubled'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1724' u='r' c='_Z17testModArgsDoubledd'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1737' u='r' c='_Z19testModArgImmDoubledd'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1750' u='r' c='_Z19testModImmArgDoubledd'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1763' u='r' c='_Z17testModImmsDoubledd'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1775' u='r' c='_Z15testModArgFloatf'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1793' u='r' c='_Z16testModArgsFloatff'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1808' u='r' c='_Z18testModArgImmFloatff'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1823' u='r' c='_Z18testModImmArgFloatff'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_2.cpp' l='1836' u='r' c='_Z16testModImmsFloatff'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2380' u='r' c='_Z10testModArgx'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2398' u='r' c='_Z11testModArgsxx'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2416' u='r' c='_Z11testModImmsxx'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2432' u='r' c='_Z12testModArg32i'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2452' u='r' c='_Z13testModArgs32ii'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2470' u='r' c='_Z13testModImms32ii'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2482' u='r' c='_Z15testChillModArgx'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2495' u='r' c='_Z16testChillModArgsxx'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2508' u='r' c='_Z16testChillModImmsxx'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2521' u='r' c='_Z17testChillModArg32i'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2536' u='r' c='_Z18testChillModArgs32ii'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_5.cpp' l='2549' u='r' c='_Z18testChillModImms32ii'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_6.cpp' l='2053' u='r' c='_Z30testEntrySwitchWithCommonPathsv'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_6.cpp' l='2170' u='r' c='_Z53testEntrySwitchWithCommonPathsAndNonTrivialEntrypointv'/>
