<dec f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='36' type='0'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='45' c='_ZN3JSC2B311forEachBankERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='55' u='r' c='_ZN3JSC2B311bankForTypeENS0_4TypeE'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='58' u='r' c='_ZN3JSC2B311bankForTypeENS0_4TypeE'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='64' u='r' c='_ZN3JSC2B311bankForTypeENS0_4TypeE'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='69' u='r' c='_ZN3JSC2B310bankForRegENS_3RegE'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Width.h' l='85' u='r' c='_ZN3JSC2B317conservativeWidthENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Width.h' l='90' u='r' c='_ZN3JSC2B312minimumWidthENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirTmp.h' l='81' u='r' c='_ZN3JSC2B33Air3Tmp11tmpForIndexENS0_4BankEj'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirTmp.h' l='102' u='r' c='_ZNK3JSC2B33Air3Tmp4bankEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirTmp.h' l='154' u='r' c='_ZNK3JSC2B33Air3Tmp8tmpIndexENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirArg.h' l='1092' u='r' c='_ZNK3JSC2B33Air3Arg4bankEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirArg.h' l='1098' c='_ZNK3JSC2B33Air3Arg6isBankENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirArg.h' l='1309' c='_ZN3JSC2B33Air3Arg10forEachTmpENS2_4RoleENS0_4BankENS0_5WidthERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirArg.h' l='1312' c='_ZN3JSC2B33Air3Arg10forEachTmpENS2_4RoleENS0_4BankENS0_5WidthERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirArg.h' l='1313' c='_ZN3JSC2B33Air3Arg10forEachTmpENS2_4RoleENS0_4BankENS0_5WidthERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCode.h' l='90' c='_ZNK3JSC2B33Air4Code19regsInPriorityOrderENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCode.h' l='125' c='_ZN3JSC2B33Air4Code6newTmpENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCode.h' l='136' c='_ZN3JSC2B33Air4Code7numTmpsENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCode.h' l='376' c='_ZN3JSC2B33Air4Code23regsInPriorityOrderImplENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='171' u='r' c='_ZN12_GLOBAL__N_121testShuffleSimpleSwapEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='206' u='r' c='_ZN12_GLOBAL__N_122testShuffleSimpleShiftEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='252' u='r' c='_ZN12_GLOBAL__N_120testShuffleLongShiftEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='304' u='r' c='_ZN12_GLOBAL__N_129testShuffleLongShiftBackwardsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='348' u='r' c='_ZN12_GLOBAL__N_123testShuffleSimpleRotateEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='384' u='r' c='_ZN12_GLOBAL__N_126testShuffleSimpleBroadcastEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='408' u='r' c='_ZN12_GLOBAL__N_127testShuffleBroadcastAllRegsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='428' u='r' c='_ZN12_GLOBAL__N_127testShuffleBroadcastAllRegsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='469' u='r' c='_ZN12_GLOBAL__N_120testShuffleTreeShiftEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='521' u='r' c='_ZN12_GLOBAL__N_128testShuffleTreeShiftBackwardEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='576' u='r' c='_ZN12_GLOBAL__N_133testShuffleTreeShiftOtherBackwardEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='623' u='r' c='_ZN12_GLOBAL__N_125testShuffleMultipleShiftsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='668' u='r' c='_ZN12_GLOBAL__N_127testShuffleRotateWithFringeEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='713' u='r' c='_ZN12_GLOBAL__N_139testShuffleRotateWithFringeInWeirdOrderEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='758' u='r' c='_ZN12_GLOBAL__N_131testShuffleRotateWithLongFringeEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='803' u='r' c='_ZN12_GLOBAL__N_126testShuffleMultipleRotatesEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='847' u='r' c='_ZN12_GLOBAL__N_125testShuffleShiftAndRotateEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='875' u='r' c='_ZN12_GLOBAL__N_123testShuffleShiftAllRegsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='889' u='r' c='_ZN12_GLOBAL__N_123testShuffleShiftAllRegsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='911' u='r' c='_ZN12_GLOBAL__N_124testShuffleRotateAllRegsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='926' u='r' c='_ZN12_GLOBAL__N_124testShuffleRotateAllRegsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='959' u='r' c='_ZN12_GLOBAL__N_123testShuffleSimpleSwap64Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='995' u='r' c='_ZN12_GLOBAL__N_124testShuffleSimpleShift64Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1032' u='r' c='_ZN12_GLOBAL__N_125testShuffleSwapMixedWidthEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1068' u='r' c='_ZN12_GLOBAL__N_126testShuffleShiftMixedWidthEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1109' u='r' c='_ZN12_GLOBAL__N_122testShuffleShiftMemoryEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1155' u='r' c='_ZN12_GLOBAL__N_126testShuffleShiftMemoryLongEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1183' u='r' c='_ZN12_GLOBAL__N_129testShuffleShiftMemoryAllRegsEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1233' u='r' c='_ZN12_GLOBAL__N_131testShuffleShiftMemoryAllRegs64Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1294' u='r' c='_ZN12_GLOBAL__N_139testShuffleShiftMemoryAllRegsMixedWidthEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1368' u='r' c='_ZN12_GLOBAL__N_123testShuffleRotateMemoryEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1413' u='r' c='_ZN12_GLOBAL__N_125testShuffleRotateMemory64Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1458' u='r' c='_ZN12_GLOBAL__N_133testShuffleRotateMemoryMixedWidthEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1484' u='r' c='_ZN12_GLOBAL__N_132testShuffleRotateMemoryAllRegs64Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1536' u='r' c='_ZN12_GLOBAL__N_140testShuffleRotateMemoryAllRegsMixedWidthEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1595' u='r' c='_ZN12_GLOBAL__N_121testShuffleSwapDoubleEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1629' u='r' c='_ZN12_GLOBAL__N_122testShuffleShiftDoubleEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1853' u='r' c='_ZN12_GLOBAL__N_133testInvalidateCachedTempRegistersEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1947' u='r' c='_ZN12_GLOBAL__N_121testArgumentRegPinnedEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1948' u='r' c='_ZN12_GLOBAL__N_121testArgumentRegPinnedEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1979' u='r' c='_ZN12_GLOBAL__N_122testArgumentRegPinned2Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='1980' u='r' c='_ZN12_GLOBAL__N_122testArgumentRegPinned2Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2017' u='r' c='_ZN12_GLOBAL__N_122testArgumentRegPinned3Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2018' u='r' c='_ZN12_GLOBAL__N_122testArgumentRegPinned3Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2019' u='r' c='_ZN12_GLOBAL__N_122testArgumentRegPinned3Ev'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2087' u='r' c='_ZN12_GLOBAL__N_119testElideSimpleMoveEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2090' u='r' c='_ZN12_GLOBAL__N_119testElideSimpleMoveEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2125' u='r' c='_ZN12_GLOBAL__N_128testElideHandlesEarlyClobberEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2158' u='r' c='_ZN12_GLOBAL__N_128testElideHandlesEarlyClobberEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2187' u='r' c='_ZN12_GLOBAL__N_124testElideMoveThenReallocEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2190' u='r' c='_ZN12_GLOBAL__N_124testElideMoveThenReallocEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2215' u='r' c='_ZN12_GLOBAL__N_124testElideMoveThenReallocEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2222' u='r' c='_ZN12_GLOBAL__N_124testElideMoveThenReallocEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2252' u='r' c='_ZN12_GLOBAL__N_132testLinearScanSpillRangesLateUseEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/testair.cpp' l='2305' u='r' c='_ZN12_GLOBAL__N_133testLinearScanSpillRangesEarlyDefEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCustom.h' l='65' u='a' c='_ZN3JSC2B33Air11PatchCustom10forEachArgERNS1_4InstEN3WTF12ScopedLambdaIFvRNS1_3ArgENS7_4RoleENS0_4BankENS0_5WidthEEEE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCustom.h' l='138' c='_ZN3JSC2B33Air11CCallCustom10forEachArgERNS1_4InstERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCustom.h' l='211' u='r' c='_ZN3JSC2B33Air13ShuffleCustom10forEachArgERNS1_4InstERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCustom.h' l='214' c='_ZN3JSC2B33Air13ShuffleCustom10forEachArgERNS1_4InstERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCustom.h' l='305' c='_ZN3JSC2B33Air21WasmBoundsCheckCustom10forEachArgERNS1_4InstERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCustom.h' l='306' c='_ZN3JSC2B33Air21WasmBoundsCheckCustom10forEachArgERNS1_4InstERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirInstInlines.h' l='88' u='r' c='_ZN3JSC2B33Air4Inst32forEachDefWithExtraClobberedRegsEPS2_S3_RKT0_'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='40'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='47'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='54'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='61'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='68'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='75'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='82'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='89'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_8.cpp' l='133' u='r' c='_Z17testAtomicWeakCASv'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_8.cpp' l='175' u='r' c='_Z17testAtomicWeakCASv'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_8.cpp' l='321' u='r' c='_Z19testAtomicStrongCASv'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_8.cpp' l='362' u='r' c='_Z19testAtomicStrongCASv'/>
<use f='webkit/Source/JavaScriptCore/b3/testb3_8.cpp' l='403' u='r' c='_Z19testAtomicStrongCASv'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='400' c='_ZN3JSC4Wasm14AirIRGenerator6newTmpENS_2B34BankE'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='412' u='r' c='_ZN3JSC4Wasm14AirIRGenerator3g32Ev'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='413' u='r' c='_ZN3JSC4Wasm14AirIRGenerator3g64Ev'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='414' u='r' c='_ZN3JSC4Wasm14AirIRGenerator10gExternrefEv'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='415' u='r' c='_ZN3JSC4Wasm14AirIRGenerator8gFuncrefEv'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='416' u='r' c='_ZN3JSC4Wasm14AirIRGenerator8gTypeIdxENS0_4TypeE'/>
