<dec f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/Layout.cpp' l='24' type='0'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/Layout.cpp' l='89' c='_ZL14ScalarLayoutOfRKN2sh5TTypeE8Language'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/Layout.cpp' l='148' u='r' c='_ZN2sh13MetalLayoutOfERKNS_5TTypeENS_19MetalLayoutOfConfigE'/>
