<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/block.h' l='80' type='search_site *'/>
<offset>68928</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/ethreading.c' l='322' u='w' c='setup_mbby_copy'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/ethreading.c' l='322' u='r' c='setup_mbby_copy'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='74' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='75' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='76' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='81' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='82' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='83' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='87' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='88' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='89' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='93' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='94' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='95' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='99' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='100' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='101' u='r' c='vp8_init_dsmotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='118' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='119' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='120' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='125' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='126' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='127' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='131' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='132' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='133' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='137' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='138' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='139' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='143' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='144' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='145' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='149' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='150' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='151' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='155' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='156' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='157' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='161' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='162' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='163' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='167' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='168' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='169' u='r' c='vp8_init3smotion_compensation'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/mcomp.c' l='1077' u='r' c='vp8_diamond_search_sad_c'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/onyx_if.c' l='1778' u='w' c='vp8_create_compressor'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/onyx_if.c' l='1778' u='r' c='vp8_create_compressor'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/onyx_if.c' l='2274' u='r' c='vp8_remove_compressor'/>
