<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/modes.h' l='53' type='opus_int32'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1556' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1571' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1571' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1571' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1571' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1571' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1571' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1571' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/celt_encoder.c' l='1571' u='r' c='celt_encode_with_ec'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/celt/modes.c' l='247' u='r' c='opus_custom_mode_create'/>
