<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/internal.h' l='32' type='crypto_word_t [11]'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='312' u='a' c='poly2_zero'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='352' u='r' c='poly2_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='354' u='w' c='poly2_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='356' u='w' c='poly2_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='364' u='w' c='poly2_reverse_700'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='364' u='r' c='poly2_reverse_700'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='369' u='w' c='poly2_reverse_700'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='369' u='r' c='poly2_reverse_700'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='370' u='w' c='poly2_reverse_700'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='370' u='r' c='poly2_reverse_700'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='372' u='w' c='poly2_reverse_700'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='372' u='r' c='poly2_reverse_700'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='378' u='r' c='poly2_cswap'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='378' u='r' c='poly2_cswap'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='379' u='w' c='poly2_cswap'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='380' u='w' c='poly2_cswap'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='389' u='w' c='poly2_fmadd'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='389' u='r' c='poly2_fmadd'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='397' u='r' c='poly2_lshift1'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='398' u='w' c='poly2_lshift1'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='399' u='w' c='poly2_lshift1'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='408' u='r' c='poly2_rshift1'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='409' u='w' c='poly2_rshift1'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='410' u='w' c='poly2_rshift1'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='418' u='w' c='poly2_clear_top_bits'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='424' u='r' c='poly2_top_bits_are_clear'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='468' u='w' c='poly3_print'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='469' u='w' c='poly3_print'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='476' u='r' c='poly3_print'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='483' u='r' c='poly3_print'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='533' u='a' c='poly3_mul_const'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='533' u='a' c='poly3_mul_const'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='533' u='r' c='poly3_mul_const'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='533' u='r' c='poly3_mul_const'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='543' u='r' c='poly3_fmsub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='543' u='r' c='poly3_fmsub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='544' u='a' c='poly3_fmsub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='544' u='a' c='poly3_fmsub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='544' u='r' c='poly3_fmsub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='544' u='r' c='poly3_fmsub'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='565' u='r' c='poly3_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='566' u='r' c='poly3_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='569' u='a' c='poly3_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='569' u='a' c='poly3_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='569' u='r' c='poly3_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='569' u='r' c='poly3_mod_phiN'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='717' u='r' c='HRSS_poly3_mul'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='718' u='r' c='HRSS_poly3_mul'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='719' u='r' c='HRSS_poly3_mul'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='720' u='r' c='HRSS_poly3_mul'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='734' u='a' c='HRSS_poly3_mul'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='734' u='a' c='HRSS_poly3_mul'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='859' u='w' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='863' u='w' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='874' u='r' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='879' u='r' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='879' u='r' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='879' u='r' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='879' u='r' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='895' u='r' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='895' u='r' c='HRSS_poly3_invert'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1343' u='r' c='poly2_from_poly'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1375' u='r' c='poly3_from_poly'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1376' u='r' c='poly3_from_poly'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1414' u='r' c='poly3_from_poly_checked'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1415' u='r' c='poly3_from_poly_checked'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1456' u='r' c='poly_from_poly2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1474' u='r' c='poly_from_poly3'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1475' u='r' c='poly_from_poly3'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1511' u='w' c='poly_invert_mod2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1514' u='w' c='poly_invert_mod2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1527' u='r' c='poly_invert_mod2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1531' u='r' c='poly_invert_mod2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1531' u='r' c='poly_invert_mod2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/hrss/hrss.c' l='1545' u='r' c='poly_invert_mod2'/>
<offset>0</offset>
