<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.h' l='40'/>
<inh f='webkit/Source/ThirdParty/ANGLE/src/common/angleutils.h' l='43' c='angle::NonCopyable'/>
<def f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.h' l='46' ll='96'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.h' l='72' c='_ZN2rx3mtl8ResourceC1EPS1_'/>
<ovr f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.h' l='98' c='rx::mtl::Texture'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.h' l='98'/>
<ovr f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.h' l='330' c='rx::mtl::Buffer'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.h' l='330'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_command_buffer.h' l='60' c='_ZN2rx3mtl12CommandQueue25ensureResourceReadyForCPUEPNS0_8ResourceE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_command_buffer.h' l='68' c='_ZNK2rx3mtl12CommandQueue24isResourceBeingUsedByGPUEPKNS0_8ResourceE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_command_buffer.h' l='71' c='_ZNK2rx3mtl12CommandQueue23resourceHasPendingWorksEPKNS0_8ResourceE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_command_buffer.h' l='122' c='_ZN2rx3mtl13CommandBuffer17setReadDependencyEPNS0_8ResourceE'/>
<size>24</size>
<fun r='_ZN2rx3mtl8ResourceD1Ev'/>
<fun r='_ZNK2rx3mtl8Resource16isBeingUsedByGPUEPNS0_7ContextE'/>
<fun r='_ZNK2rx3mtl8Resource15hasPendingWorksEPNS0_7ContextE'/>
<fun r='_ZN2rx3mtl8Resource37setUsedByCommandBufferWithQueueSerialEyb'/>
<fun r='_ZNK2rx3mtl8Resource27getCommandBufferQueueSerialEv'/>
<fun r='_ZNK2rx3mtl8Resource20isCPUReadMemNeedSyncEv'/>
<fun r='_ZN2rx3mtl8Resource23resetCPUReadMemNeedSyncEv'/>
<fun r='_ZNK2rx3mtl8Resource17isCPUReadMemDirtyEv'/>
<fun r='_ZN2rx3mtl8Resource20resetCPUReadMemDirtyEv'/>
<fun r='_ZN2rx3mtl8ResourceC1Ev'/>
<fun r='_ZN2rx3mtl8ResourceC1EPS1_'/>
<fun r='_ZN2rx3mtl8Resource5resetEv'/>
<mbr r='rx::mtl::Resource::mUsageRef' o='64' t='std::shared_ptr&lt;UsageRef&gt;'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_command_buffer.mm' l='458' c='_ZN2rx3mtl12CommandQueue25ensureResourceReadyForCPUEPNS0_8ResourceE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_command_buffer.mm' l='481' c='_ZNK2rx3mtl12CommandQueue24isResourceBeingUsedByGPUEPKNS0_8ResourceE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_command_buffer.mm' l='492' c='_ZNK2rx3mtl12CommandQueue23resourceHasPendingWorksEPKNS0_8ResourceE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_command_buffer.mm' l='628' c='_ZN2rx3mtl13CommandBuffer17setReadDependencyEPNS0_8ResourceE'/>
<size>24</size>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.mm' l='71' c='_ZN2rx3mtl8ResourceC1EPS1_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.mm' l='449' c='_ZN2rx3mtl7TextureC1EPS1_14MTLPixelFormat'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.mm' l='461' c='_ZN2rx3mtl7TextureC1EPS1_14MTLTextureType8_NSRangeS4_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_resources.mm' l='476' c='_ZN2rx3mtl7TextureC1EPS1_RK25MTLTextureSwizzleChannels'/>
<size>24</size>
<fun r='_ZN2rx3mtl8ResourceC1Ev'/>
<fun r='_ZN2rx3mtl8ResourceC1EPS1_'/>
<fun r='_ZN2rx3mtl8Resource5resetEv'/>
<fun r='_ZNK2rx3mtl8Resource16isBeingUsedByGPUEPNS0_7ContextE'/>
<fun r='_ZNK2rx3mtl8Resource15hasPendingWorksEPNS0_7ContextE'/>
<fun r='_ZN2rx3mtl8Resource37setUsedByCommandBufferWithQueueSerialEyb'/>
