<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/sha.h' l='258' type='uint64_t'/>
<offset>512</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/sha/sha512.c' l='85' u='w' c='SHA384_Init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/sha/sha512.c' l='103' u='w' c='SHA512_Init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/sha/sha512.c' l='120' u='w' c='SHA512_256_Init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/sha/sha512.c' l='198' u='r' c='SHA512_Update'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/sha/sha512.c' l='199' u='r' c='SHA512_Update'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/sha/sha512.c' l='205' u='w' c='SHA512_Update'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/sha/sha512.c' l='260' u='r' c='sha512_final_impl'/>
