<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/crypto/include/auth.h' l='127' type='srtp_auth_init_func'/>
<offset>128</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/crypto/hash/auth.c' l='120' macro='1' u='r' c='srtp_auth_type_test'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/srtp/srtp.c' l='1126' macro='1' u='r' c='srtp_stream_init_keys'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/srtp/srtp.c' l='1200' macro='1' u='r' c='srtp_stream_init_keys'/>
