<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vpx/internal/vpx_codec_internal.h' l='294' type='vpx_codec_init_fn_t'/>
<offset>192</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vpx/internal/vpx_codec_internal.h' l='294'>/**&lt; \copydoc ::vpx_codec_init_fn_t */</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vpx/src/vpx_decoder.c' l='55' u='r' c='vpx_codec_dec_init_ver'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vpx/src/vpx_encoder.c' l='54' u='r' c='vpx_codec_enc_init_ver'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vpx/src/vpx_encoder.c' l='112' u='r' c='vpx_codec_enc_init_multi_ver'/>
