<dec f='webkit/Source/WebCore/rendering/style/RenderStyleConstants.h' l='921' type='16'/>
<use f='webkit/Source/WebCore/rendering/style/RenderStyle.h' l='2358' u='r' c='_ZN7WebCore11RenderStyle20isDisplayFlexibleBoxENS_11DisplayTypeE'/>
<use f='webkit/Source/WebCore/layout/layouttree/LayoutBox.h' l='136' u='r' c='_ZNK7WebCore6Layout3Box9isFlexBoxEv'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/RenderStyleConstants.h' l='921' type='16'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/RenderStyle.h' l='2358' u='r' c='_ZN7WebCore11RenderStyle20isDisplayFlexibleBoxENS_11DisplayTypeE'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/LayoutBox.h' l='136' u='r' c='_ZNK7WebCore6Layout3Box9isFlexBoxEv'/>
<use f='webkit/Source/WebCore/css/CSSPrimitiveValueMappings.h' l='1387' c='_ZN7WebCore17CSSPrimitiveValueC1ET_'/>
<use f='webkit/Source/WebCore/html/HTMLButtonElement.cpp' l='67' u='r' c='_ZN7WebCore17HTMLButtonElement21createElementRendererEONS_11RenderStyleERKNS_18RenderTreePositionE'/>
<use f='webkit/Source/WebCore/layout/layouttree/LayoutBox.cpp' l='301' u='r' c='_ZNK7WebCore6Layout3Box15isBlockLevelBoxEv'/>
<use f='webkit/Source/WebCore/layout/layouttree/LayoutTreeBuilder.cpp' l='246' u='r' c='_ZN7WebCore6Layout11TreeBuilder15createLayoutBoxERKNS0_12ContainerBoxERKNS_12RenderObjectE'/>
<use f='webkit/Source/WebCore/rendering/RenderBlock.cpp' l='2882' u='r' c='_ZN7WebCore11RenderBlock39createAnonymousBlockWithStyleAndDisplayERNS_8DocumentERKNS_11RenderStyleENS_11DisplayTypeE'/>
<use f='webkit/Source/WebCore/rendering/RenderBlock.cpp' l='2883' u='r' c='_ZN7WebCore11RenderBlock39createAnonymousBlockWithStyleAndDisplayERNS_8DocumentERKNS_11RenderStyleENS_11DisplayTypeE'/>
<use f='webkit/Source/WebCore/rendering/RenderElement.cpp' l='178' c='_ZN7WebCore13RenderElement9createForERNS_7ElementEONS_11RenderStyleEN3WTF9OptionSetINS0_30ConstructBlockLevelRendererForEEE'/>
<use f='webkit/Source/WebCore/rendering/RenderFullScreen.cpp' l='75' u='r' c='_ZN7WebCoreL21createFullScreenStyleEv'/>
<use f='webkit/Source/WebCore/rendering/style/RenderStyleConstants.cpp' l='452' c='_ZN7WebCorelsERN3WTF10TextStreamENS_11DisplayTypeE'/>
<use f='webkit/Source/WebCore/style/StyleAdjuster.cpp' l='104' c='_ZN7WebCore5StyleL22equivalentBlockDisplayERKNS_11RenderStyleERKNS_8DocumentE'/>
<use f='webkit/Source/WebCore/style/StyleAdjuster.cpp' l='119' u='r' c='_ZN7WebCore5StyleL22equivalentBlockDisplayERKNS_11RenderStyleERKNS_8DocumentE'/>
<use f='webkit/Source/WebCore/style/StyleAdjuster.cpp' l='629' u='r' c='_ZNK7WebCore5Style8Adjuster27adjustForSiteSpecificQuirksERNS_11RenderStyleE'/>
