<dec f='webkit/Source/WebCore/testing/MockWebAuthenticationConfiguration.h' l='42' type='0'/>
<use f='webkit/Source/WebCore/testing/MockWebAuthenticationConfiguration.h' l='86'/>
<use f='webkit/Source/WebCore/testing/MockWebAuthenticationConfiguration.h' l='278'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMockWebAuthenticationConfiguration.cpp' l='146' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_34MockWebAuthenticationConfiguration11HidSubStageE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMockWebAuthenticationConfiguration.cpp' l='161' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMockWebAuthenticationConfiguration.cpp' l='539' u='r' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/MockWebAuthenticationConfiguration.h' l='42' type='0'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/MockWebAuthenticationConfiguration.h' l='86'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/MockWebAuthenticationConfiguration.h' l='278'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.h' l='68'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.cpp' l='139' u='r' c='_ZN6WebKit17MockHidConnection12parseRequestEv'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.cpp' l='192' u='r' c='_ZN6WebKit17MockHidConnection12parseRequestEv'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.cpp' l='207' u='r' c='_ZN6WebKit17MockHidConnection11feedReportsEv'/>
