<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/webxr/XRSessionEvent.h' l='38' ll='45'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRSessionEvent.h' l='47' c='_ZN7WebCore14XRSessionEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRSessionEvent.h' l='53' c='_ZN7WebCore14XRSessionEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
<fun r='_ZN7WebCore14XRSessionEvent4InitC1Ev'/>
<fun r='_ZN7WebCore14XRSessionEvent4InitC1EON3WTF6RefPtrINS_12WebXRSessionENS2_12RawPtrTraitsIS4_EENS2_21DefaultRefDerefTraitsIS4_EEEE'/>
<mbr r='WebCore::XRSessionEvent::Init::session' o='64' t='RefPtr&lt;WebCore::WebXRSession&gt;'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRSessionEvent.cpp' l='38' c='_ZN7WebCore14XRSessionEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRSessionEvent.cpp' l='43' c='_ZN7WebCore14XRSessionEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRSessionEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRSessionEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRSessionEvent.cpp' l='57' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRSessionEvent.cpp' l='57' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRSessionEvent.cpp' l='67' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRSessionEvent.cpp' l='176' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
