<def f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineLine.h' l='62' ll='128'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineLine.h' l='129'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineLineBox.h' l='153' c='_ZNK7WebCore6Layout7LineBox21logicalRectForTextRunERKNS0_4Line3RunE'/>
<size>96</size>
<fun r='_ZNK7WebCore6Layout4Line3Run6isTextEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run5isBoxEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run11isLineBreakEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run15isSoftLineBreakEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run15isHardLineBreakEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run22isWordBreakOpportunityEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run16isInlineBoxStartEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run14isInlineBoxEndEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run9layoutBoxEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run5styleEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run11textContentEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run12logicalWidthEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run11logicalLeftEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run12logicalRightEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run9expansionEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run23hasExpansionOpportunityEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run17expansionBehaviorEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run25expansionOpportunityCountEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run21hasTrailingWhitespaceEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run23trailingWhitespaceWidthEv'/>
<fun r='_ZN7WebCore6Layout4Line3RunC1ERKNS0_14InlineTextItemEff'/>
<fun r='_ZN7WebCore6Layout4Line3RunC1ERKNS0_23InlineSoftLineBreakItemEf'/>
<fun r='_ZN7WebCore6Layout4Line3RunC1ERKNS0_10InlineItemEff'/>
<fun r='_ZN7WebCore6Layout4Line3Run6expandERKNS0_14InlineTextItemEf'/>
<fun r='_ZN7WebCore6Layout4Line3Run16moveHorizontallyEf'/>
<fun r='_ZN7WebCore6Layout4Line3Run18shrinkHorizontallyEf'/>
<fun r='_ZN7WebCore6Layout4Line3Run20setExpansionBehaviorEj'/>
<fun r='_ZN7WebCore6Layout4Line3Run22setHorizontalExpansionEf'/>
<fun r='_ZN7WebCore6Layout4Line3Run14setNeedsHyphenEf'/>
<fun r='_ZNK7WebCore6Layout4Line3Run32hasCollapsibleTrailingWhitespaceEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run30hasCollapsedTrailingWhitespaceEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run22trailingWhitespaceTypeERKNS0_14InlineTextItemE'/>
<fun r='_ZN7WebCore6Layout4Line3Run24removeTrailingWhitespaceEv'/>
<fun r='_ZN7WebCore6Layout4Line3Run34visuallyCollapseTrailingWhitespaceEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run24hasTrailingLetterSpacingEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run21trailingLetterSpacingEv'/>
<fun r='_ZN7WebCore6Layout4Line3Run27removeTrailingLetterSpacingEv'/>
<mbr r='WebCore::Layout::Line::Run::m_type' o='0' t='InlineItem::Type'/>
<mbr r='WebCore::Layout::Line::Run::m_layoutBox' o='64' t='const WebCore::Layout::Box *'/>
<mbr r='WebCore::Layout::Line::Run::m_logicalLeft' o='128' t='WebCore::InlineLayoutUnit'/>
<mbr r='WebCore::Layout::Line::Run::m_logicalWidth' o='160' t='WebCore::InlineLayoutUnit'/>
<mbr r='WebCore::Layout::Line::Run::m_whitespaceIsExpansionOpportunity' o='192' t='bool'/>
<mbr r='WebCore::Layout::Line::Run::m_trailingWhitespaceType' o='224' t='WebCore::Layout::Line::Run::TrailingWhitespace'/>
<mbr r='WebCore::Layout::Line::Run::m_trailingWhitespaceWidth' o='256' t='WebCore::InlineLayoutUnit'/>
<mbr r='WebCore::Layout::Line::Run::m_textContent' o='320' t='std::optional&lt;LineRun::Text&gt;'/>
<mbr r='WebCore::Layout::Line::Run::m_expansion' o='640' t='LineRun::Expansion'/>
<mbr r='WebCore::Layout::Line::Run::m_expansionOpportunityCount' o='704' t='unsigned int'/>
<fun r='_ZNK7WebCore6Layout4Line3Run22trailingWhitespaceTypeERKNS0_14InlineTextItemE'/>
<fun r='_ZN7WebCore6Layout4Line3Run14setNeedsHyphenEf'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineLine.cpp' l='78' c='_ZN7WebCore6Layout4Line17applyRunExpansionEf'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineLineBox.cpp' l='102' c='_ZNK7WebCore6Layout7LineBox21logicalRectForTextRunERKNS0_4Line3RunE'/>
<size>96</size>
<fun r='_ZN7WebCore6Layout4Line3RunC1ERKNS0_10InlineItemEff'/>
<fun r='_ZN7WebCore6Layout4Line3RunC1ERKNS0_23InlineSoftLineBreakItemEf'/>
<fun r='_ZN7WebCore6Layout4Line3RunC1ERKNS0_14InlineTextItemEff'/>
<fun r='_ZN7WebCore6Layout4Line3Run6expandERKNS0_14InlineTextItemEf'/>
<fun r='_ZNK7WebCore6Layout4Line3Run24hasTrailingLetterSpacingEv'/>
<fun r='_ZNK7WebCore6Layout4Line3Run21trailingLetterSpacingEv'/>
<fun r='_ZN7WebCore6Layout4Line3Run27removeTrailingLetterSpacingEv'/>
<fun r='_ZN7WebCore6Layout4Line3Run24removeTrailingWhitespaceEv'/>
<fun r='_ZN7WebCore6Layout4Line3Run34visuallyCollapseTrailingWhitespaceEv'/>
<fun r='_ZN7WebCore6Layout4Line3Run20setExpansionBehaviorEj'/>
<fun r='_ZNK7WebCore6Layout4Line3Run17expansionBehaviorEv'/>
<fun r='_ZN7WebCore6Layout4Line3Run22setHorizontalExpansionEf'/>
