<dec f='webkit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='46' type='WebCore::ScriptBuffer'/>
<use f='webkit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='52' c='_ZNK7WebCore24ServiceWorkerContextData14ImportedScript6encodeERT_'/>
<use f='webkit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='79' u='m' c='_ZNK7WebCore24ServiceWorkerContextData14ImportedScript12isolatedCopyEv'/>
<offset>0</offset>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/ServiceWorkerContextData.h' l='46' type='WebCore::ScriptBuffer'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/ServiceWorkerContextData.h' l='52' c='_ZNK7WebCore24ServiceWorkerContextData14ImportedScript6encodeERT_'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/ServiceWorkerContextData.h' l='79' u='m' c='_ZNK7WebCore24ServiceWorkerContextData14ImportedScript12isolatedCopyEv'/>
<offset>0</offset>
<use f='webkit/Source/WebCore/workers/WorkerScriptLoader.cpp' l='67' u='r' c='_ZN7WebCore18WorkerScriptLoader17loadSynchronouslyEPNS_22ScriptExecutionContextERKN3WTF3URLENS_12FetchOptions4ModeENS7_5CacheENS_32ContentSecurityPoli6658778'/>
<use f='webkit/Source/WebCore/workers/service/ServiceWorkerGlobalScope.cpp' l='171' u='r' c='_ZN7WebCore24ServiceWorkerGlobalScope20didSaveScriptsToDiskEONS_12ScriptBufferEON3WTF7HashMapINS3_3URLES1_NS3_11DefaultHashIS5_EENS3_10HashTraitsIS5_E4516448'/>
<use f='webkit/Source/WebCore/workers/service/ServiceWorkerGlobalScope.cpp' l='172' u='w' c='_ZN7WebCore24ServiceWorkerGlobalScope20didSaveScriptsToDiskEONS_12ScriptBufferEON3WTF7HashMapINS3_3URLES1_NS3_11DefaultHashIS5_EENS3_10HashTraitsIS5_E4516448'/>
<use f='webkit/Source/WebCore/workers/service/server/RegistrationDatabase.cpp' l='478' u='r' c='_ZN7WebCore20RegistrationDatabase13doPushChangesERKN3WTF6VectorINS_24ServiceWorkerContextDataELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEERKNS2_7336411'/>
<use f='webkit/Source/WebCore/workers/service/server/SWServerWorker.cpp' l='268' u='r' c='_ZN7WebCore14SWServerWorker20didSaveScriptsToDiskEONS_12ScriptBufferEON3WTF7HashMapINS3_3URLES1_NS3_11DefaultHashIS5_EENS3_10HashTraitsIS5_EENS8_IS1_E13806154'/>
<use f='webkit/Source/WebCore/workers/service/server/SWServerWorker.cpp' l='269' u='w' c='_ZN7WebCore14SWServerWorker20didSaveScriptsToDiskEONS_12ScriptBufferEON3WTF7HashMapINS3_3URLES1_NS3_11DefaultHashIS5_EENS3_10HashTraitsIS5_EENS8_IS1_E13806154'/>
<use f='webkit/Source/WebCore/bindings/js/WorkerModuleScriptLoader.cpp' l='68' u='r' c='_ZN7WebCore24WorkerModuleScriptLoader4loadERNS_22ScriptExecutionContextEON3WTF3URLE'/>
