<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/css/MediaQueryListEvent.h' l='35' ll='38'/>
<use f='webkit/Source/WebCore/css/MediaQueryListEvent.h' l='41' c='_ZN7WebCore19MediaQueryListEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/css/MediaQueryListEvent.h' l='50' c='_ZN7WebCore19MediaQueryListEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaQueryListEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaQueryListEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaQueryListEvent.cpp' l='50' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaQueryListEvent.cpp' l='50' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaQueryListEvent.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaQueryListEvent.cpp' l='178' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
<mbr r='WebCore::MediaQueryListEvent::Init::media' o='64' t='WTF::String'/>
<mbr r='WebCore::MediaQueryListEvent::Init::matches' o='128' t='bool'/>
<use f='webkit/Source/WebCore/css/MediaQueryListEvent.cpp' l='42' c='_ZN7WebCore19MediaQueryListEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/css/MediaQueryListEvent.cpp' l='54' c='_ZN7WebCore19MediaQueryListEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>24</size>
