<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/webxr/XRReferenceSpaceEvent.h' l='41' ll='44'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRReferenceSpaceEvent.h' l='46' c='_ZN7WebCore21XRReferenceSpaceEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRReferenceSpaceEvent.h' l='53' c='_ZN7WebCore21XRReferenceSpaceEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRReferenceSpaceEvent.cpp' l='36' c='_ZN7WebCore21XRReferenceSpaceEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRReferenceSpaceEvent.cpp' l='41' c='_ZN7WebCore21XRReferenceSpaceEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>24</size>
<mbr r='WebCore::XRReferenceSpaceEvent::Init::referenceSpace' o='64' t='RefPtr&lt;WebCore::WebXRReferenceSpace&gt;'/>
<mbr r='WebCore::XRReferenceSpaceEvent::Init::transform' o='128' t='RefPtr&lt;WebCore::WebXRRigidTransform&gt;'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRReferenceSpaceEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRReferenceSpaceEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRReferenceSpaceEvent.cpp' l='58' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRReferenceSpaceEvent.cpp' l='58' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRReferenceSpaceEvent.cpp' l='68' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRReferenceSpaceEvent.cpp' l='189' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
