<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/encryptedmedia/legacy/WebKitMediaKeyNeededEvent.h' l='45' ll='47'/>
<use f='webkit/Source/WebCore/Modules/encryptedmedia/legacy/WebKitMediaKeyNeededEvent.h' l='49' c='_ZN7WebCore25WebKitMediaKeyNeededEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/encryptedmedia/legacy/WebKitMediaKeyNeededEvent.h' l='60' c='_ZN7WebCore25WebKitMediaKeyNeededEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/encryptedmedia/legacy/WebKitMediaKeyNeededEvent.cpp' l='44' c='_ZN7WebCore25WebKitMediaKeyNeededEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
<mbr r='WebCore::WebKitMediaKeyNeededEvent::Init::initData' o='64' t='RefPtr&lt;JSC::Uint8Array&gt;'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyNeededEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyNeededEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyNeededEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyNeededEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyNeededEvent.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyNeededEvent.cpp' l='171' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
