<dec f='webkit/Source/WebCore/platform/graphics/gpu/GPUBindGroupAllocator.h' l='46' type='std::optional&lt;PlatformGPUBufferOffset&gt;'/>
<offset>256</offset>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUBindGroupAllocatorMetal.mm' l='112' u='w' c='_ZN7WebCore21GPUBindGroupAllocator22allocateAndSetEncodersEPU29objcproto18MTLArgumentEncoder8NSObjectS3_S3_'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUBindGroupAllocatorMetal.mm' l='113' u='m' c='_ZN7WebCore21GPUBindGroupAllocator22allocateAndSetEncodersEPU29objcproto18MTLArgumentEncoder8NSObjectS3_S3_'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUProgrammablePassEncoderMetal.mm' l='66' u='m' c='_ZN7WebCore26GPUProgrammablePassEncoder12setBindGroupEjRNS_12GPUBindGroupE'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUProgrammablePassEncoderMetal.mm' l='67' u='m' c='_ZN7WebCore26GPUProgrammablePassEncoder12setBindGroupEjRNS_12GPUBindGroupE'/>
