<dec f='webkit/Source/WebCore/editing/EditingBehaviorType.h' l='39' type='0'/>
<use f='webkit/Source/WebCore/editing/EditingBehavior.h' l='47' u='r' c='_ZNK7WebCore15EditingBehavior36shouldConsiderSelectionAsDirectionalEv'/>
<use f='webkit/Source/WebCore/editing/EditingBehavior.h' l='51' u='r' c='_ZNK7WebCore15EditingBehavior40shouldCenterAlignWhenSelectionIsRevealedEv'/>
<use f='webkit/Source/WebCore/editing/EditingBehavior.h' l='55' u='r' c='_ZNK7WebCore15EditingBehavior40shouldToggleStyleBasedOnStartOfSelectionEv'/>
<use f='webkit/Source/WebCore/editing/EditingBehavior.h' l='59' u='r' c='_ZNK7WebCore15EditingBehavior48shouldAlwaysGrowSelectionWhenExtendingToBoundaryEv'/>
<use f='webkit/Source/WebCore/editing/EditingBehavior.h' l='62' u='r' c='_ZNK7WebCore15EditingBehavior33shouldSelectOnContextualMenuClickEv'/>
<use f='webkit/Source/WebCore/editing/EditingBehavior.h' l='79' u='r' c='_ZNK7WebCore15EditingBehavior44shouldExtendSelectionByWordOrLineAcrossCaretEv'/>
<use f='webkit/Source/WebCore/editing/EditingBehavior.h' l='90' u='r' c='_ZNK7WebCore15EditingBehavior35shouldSelectBasedOnDictionaryLookupEv'/>
<use f='webkit/Source/WebCore/editing/EditingBehavior.h' l='93' u='r' c='_ZNK7WebCore15EditingBehavior45shouldAlwaysExtendSelectionFromExtentEndpointEv'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehaviorType.h' l='39' type='0'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehavior.h' l='47' u='r' c='_ZNK7WebCore15EditingBehavior36shouldConsiderSelectionAsDirectionalEv'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehavior.h' l='51' u='r' c='_ZNK7WebCore15EditingBehavior40shouldCenterAlignWhenSelectionIsRevealedEv'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehavior.h' l='55' u='r' c='_ZNK7WebCore15EditingBehavior40shouldToggleStyleBasedOnStartOfSelectionEv'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehavior.h' l='59' u='r' c='_ZNK7WebCore15EditingBehavior48shouldAlwaysGrowSelectionWhenExtendingToBoundaryEv'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehavior.h' l='62' u='r' c='_ZNK7WebCore15EditingBehavior33shouldSelectOnContextualMenuClickEv'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehavior.h' l='79' u='r' c='_ZNK7WebCore15EditingBehavior44shouldExtendSelectionByWordOrLineAcrossCaretEv'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehavior.h' l='90' u='r' c='_ZNK7WebCore15EditingBehavior35shouldSelectBasedOnDictionaryLookupEv'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EditingBehavior.h' l='93' u='r' c='_ZNK7WebCore15EditingBehavior45shouldAlwaysExtendSelectionFromExtentEndpointEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInternalSettings.cpp' l='61' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_19EditingBehaviorTypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInternalSettings.cpp' l='78' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/Settings.cpp' l='187' u='r' c='_ZN7WebCore8Settings6Values10initializeEv'/>
