<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/mediastream/RTCPeerConnectionIceErrorEvent.h' l='41' ll='47'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCPeerConnectionIceErrorEvent.h' l='49' c='_ZN7WebCore30RTCPeerConnectionIceErrorEvent6createERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceErrorEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceErrorEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceErrorEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceErrorEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceErrorEvent.cpp' l='65' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceErrorEvent.cpp' l='220' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>48</size>
<mbr r='WebCore::RTCPeerConnectionIceErrorEvent::Init::address' o='64' t='WTF::String'/>
<mbr r='WebCore::RTCPeerConnectionIceErrorEvent::Init::port' o='128' t='std::optional&lt;uint16_t&gt;'/>
<mbr r='WebCore::RTCPeerConnectionIceErrorEvent::Init::url' o='192' t='WTF::String'/>
<mbr r='WebCore::RTCPeerConnectionIceErrorEvent::Init::errorCode' o='256' t='uint16_t'/>
<mbr r='WebCore::RTCPeerConnectionIceErrorEvent::Init::errorText' o='320' t='WTF::String'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCPeerConnectionIceErrorEvent.cpp' l='43' c='_ZN7WebCore30RTCPeerConnectionIceErrorEvent6createERKN3WTF10AtomStringEONS0_4InitE'/>
<size>48</size>
