<dec f='webkit/Source/WebCore/rendering/style/RenderStyleConstants.h' l='287' type='2'/>
<use f='webkit/Source/WebCore/accessibility/mac/WebAccessibilityObjectWrapperMac.mm' l='861' u='r' c='_ZL25AXAttributeStringSetStyleP25NSMutableAttributedStringPN7WebCore12RenderObjectE8_NSRange'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/RenderStyleConstants.h' l='287' type='2'/>
<use f='webkit/Source/WebCore/css/CSSPrimitiveValueMappings.h' l='2763' c='_ZN7WebCore17CSSPrimitiveValueC1ET_'/>
<use f='webkit/Source/WebCore/css/CSSPrimitiveValueMappings.h' l='2795' u='r' c='_ZNK7WebCore17CSSPrimitiveValuecvT_Ev'/>
<use f='webkit/Source/WebCore/rendering/RenderTableCell.h' l='303' u='r' c='_ZNK7WebCore15RenderTableCell17isBaselineAlignedEv'/>
<use f='webkit/Source/WebCore/editing/Editor.cpp' l='4052' c='_ZN7WebCore6Editor30fontAttributesAtSelectionStartEv'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationCoverage.cpp' l='630' c='_ZN7WebCore17LayoutIntegrationL14canUseForChildERKNS_15RenderBlockFlowERKNS_12RenderObjectENS0_14IncludeReasonsE'/>
<use f='webkit/Source/WebCore/rendering/LegacyRootInlineBox.cpp' l='941' u='r' c='_ZN7WebCore19LegacyRootInlineBox22verticalPositionForBoxEPNS_15LegacyInlineBoxERNS_21VerticalPositionCacheE'/>
<use f='webkit/Source/WebCore/rendering/RenderTableCell.cpp' l='213' c='_ZN7WebCore15RenderTableCell23computeIntrinsicPaddingENS_10LayoutUnitE'/>
<use f='webkit/Source/WebCore/rendering/style/RenderStyleConstants.cpp' l='1244' c='_ZN7WebCorelsERN3WTF10TextStreamENS_13VerticalAlignE'/>
<use f='webkit/Source/WebCore/css/CSSComputedStyleDeclaration.cpp' l='3266' c='_ZN7WebCore22ComputedStyleExtractor23valueForPropertyInStyleERKNS_11RenderStyleENS_13CSSPropertyIDEPNS_13RenderElementE'/>
