<dec f='webkit/Source/WebCore/platform/graphics/gpu/GPUBindGroupBinding.h' l='41' type='WebCore::GPUBindingResource'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUBindGroupMetal.mm' l='179' u='r' c='_ZN7WebCore12GPUBindGroup9tryCreateERKNS_22GPUBindGroupDescriptorERNS_21GPUBindGroupAllocatorE'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUBindGroupMetal.mm' l='197' u='r' c='_ZN7WebCore12GPUBindGroup9tryCreateERKNS_22GPUBindGroupDescriptorERNS_21GPUBindGroupAllocatorE'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUBindGroupMetal.mm' l='208' u='r' c='_ZN7WebCore12GPUBindGroup9tryCreateERKNS_22GPUBindGroupDescriptorERNS_21GPUBindGroupAllocatorE'/>
<offset>64</offset>
