<dec f='webkit/Source/WebCore/Modules/webgpu/WebGPUProgrammableStageDescriptor.h' l='39' type='RefPtr&lt;WebCore::WebGPUShaderModule&gt;'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebGPUProgrammableStageDescriptor.cpp' l='71' u='w' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<offset>64</offset>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUDevice.cpp' l='241' u='r' c='_ZN7WebCore12WebGPUDevice20createRenderPipelineERKNS_30WebGPURenderPipelineDescriptorE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUDevice.cpp' l='245' u='a' c='_ZN7WebCore12WebGPUDevice20createRenderPipelineERKNS_30WebGPURenderPipelineDescriptorE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUDevice.cpp' l='263' u='r' c='_ZN7WebCore12WebGPUDevice21createComputePipelineERKNS_31WebGPUComputePipelineDescriptorE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUProgrammableStageDescriptor.cpp' l='35' u='m' c='_ZNK7WebCore33WebGPUProgrammableStageDescriptor39tryCreateGPUProgrammableStageDescriptorEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUProgrammableStageDescriptor.cpp' l='35' u='m' c='_ZNK7WebCore33WebGPUProgrammableStageDescriptor39tryCreateGPUProgrammableStageDescriptorEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUProgrammableStageDescriptor.cpp' l='38' u='m' c='_ZNK7WebCore33WebGPUProgrammableStageDescriptor39tryCreateGPUProgrammableStageDescriptorEv'/>
