<dec f='webkit/Source/WebCore/rendering/style/SVGRenderStyleDefs.h' l='59' type='1'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/SVGRenderStyleDefs.h' l='59' type='1'/>
<use f='webkit/Source/WebCore/css/SVGCSSComputedStyleDeclaration.cpp' l='159' c='_ZN7WebCore22ComputedStyleExtractor16svgPropertyValueENS_13CSSPropertyIDE'/>
<use f='webkit/Source/WebCore/style/StyleBuilderCustom.h' l='1176' u='r' c='_ZN7WebCore5Style13BuilderCustom23applyValueBaselineShiftERNS0_12BuilderStateERNS_8CSSValueE'/>
<use f='webkit/Source/WebCore/rendering/style/SVGRenderStyleDefs.cpp' l='332' c='_ZN7WebCorelsERN3WTF10TextStreamENS_13BaselineShiftE'/>
<use f='webkit/Source/WebCore/rendering/svg/SVGTextLayoutEngineBaseline.cpp' l='50' c='_ZNK7WebCore27SVGTextLayoutEngineBaseline22calculateBaselineShiftERKNS_14SVGRenderStyleEPNS_10SVGElementE'/>
