<dec f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.h' l='755' type='1'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.h' l='761' u='r'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/GraphicsContextGL.h' l='755' type='1'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/GraphicsContextGL.h' l='761' u='r'/>
