<dec f='webkit/Source/WebCore/editing/InlineRunAndOffset.h' l='33' type='LayoutIntegration::RunIterator'/>
<use f='webkit/Source/WebCore/dom/Position.cpp' l='1077' u='a' c='_ZNK7WebCore8Position26rendersInDifferentPositionERKS0_'/>
<use f='webkit/Source/WebCore/dom/Position.cpp' l='1078' u='a' c='_ZNK7WebCore8Position26rendersInDifferentPositionERKS0_'/>
<offset>0</offset>
<use f='webkit/Source/WebCore/editing/FrameSelection.cpp' l='660' u='a' c='_ZN7WebCore14FrameSelection20directionOfSelectionEv'/>
<use f='webkit/Source/WebCore/editing/FrameSelection.cpp' l='661' u='a' c='_ZN7WebCore14FrameSelection20directionOfSelectionEv'/>
<use f='webkit/Source/WebCore/editing/RenderedPosition.cpp' l='90' u='r' c='_ZN7WebCore16RenderedPositionC1ERKNS_8PositionENS_8AffinityE'/>
<use f='webkit/Source/WebCore/editing/VisiblePosition.cpp' l='159' u='a' c='_ZNK7WebCore15VisiblePosition29leftVisuallyDistinctCandidateEv'/>
<use f='webkit/Source/WebCore/editing/VisiblePosition.cpp' l='321' u='a' c='_ZNK7WebCore15VisiblePosition30rightVisuallyDistinctCandidateEv'/>
<use f='webkit/Source/WebCore/editing/VisiblePosition.cpp' l='642' u='m' c='_ZNK7WebCore15VisiblePosition14localCaretRectEv'/>
<use f='webkit/Source/WebCore/editing/VisiblePosition.cpp' l='642' u='m' c='_ZNK7WebCore15VisiblePosition14localCaretRectEv'/>
<use f='webkit/Source/WebCore/editing/VisiblePosition.cpp' l='658' u='a' c='_ZNK7WebCore15VisiblePosition30absoluteSelectionBoundsForLineEv'/>
<use f='webkit/Source/WebCore/editing/VisibleUnits.cpp' l='963' u='a' c='_ZN7WebCore20previousLinePositionERKNS_15VisiblePositionEiNS_12EditableTypeE'/>
<use f='webkit/Source/WebCore/editing/VisibleUnits.cpp' l='1013' u='a' c='_ZN7WebCore16nextLinePositionERKNS_15VisiblePositionEiNS_12EditableTypeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='171' u='m' c='_ZN7WebCoreL23computeCaretRectForTextERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='174' u='r' c='_ZN7WebCoreL23computeCaretRectForTextERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='185' u='m' c='_ZN7WebCoreL28computeCaretRectForLineBreakERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='188' u='m' c='_ZN7WebCoreL28computeCaretRectForLineBreakERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='194' u='m' c='_ZN7WebCoreL32computeCaretRectForSVGInlineTextERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='194' u='m' c='_ZN7WebCoreL32computeCaretRectForSVGInlineTextERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='224' u='m' c='_ZN7WebCoreL22computeCaretRectForBoxERKNS_9RenderBoxERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='224' u='m' c='_ZN7WebCoreL22computeCaretRectForBoxERKNS_9RenderBoxERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='229' u='m' c='_ZN7WebCoreL22computeCaretRectForBoxERKNS_9RenderBoxERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/rendering/CaretRectComputation.cpp' l='230' u='m' c='_ZN7WebCoreL22computeCaretRectForBoxERKNS_9RenderBoxERKNS_18InlineRunAndOffsetENS_13CaretRectModeE'/>
<use f='webkit/Source/WebCore/accessibility/AXObjectCache.cpp' l='2968' u='m' c='_ZN7WebCore13AXObjectCache32localCaretRectForCharacterOffsetERPNS_12RenderObjectERKNS_15CharacterOffsetE'/>
<use f='webkit/Source/WebCore/accessibility/AXObjectCache.cpp' l='2969' u='m' c='_ZN7WebCore13AXObjectCache32localCaretRectForCharacterOffsetERPNS_12RenderObjectERKNS_15CharacterOffsetE'/>
<use f='webkit/Source/WebCore/accessibility/AXObjectCache.cpp' l='2971' u='r' c='_ZN7WebCore13AXObjectCache32localCaretRectForCharacterOffsetERPNS_12RenderObjectERKNS_15CharacterOffsetE'/>
