<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/mediastream/RTCDataChannelEvent.h' l='39' ll='41'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCDataChannelEvent.h' l='44' c='_ZN7WebCore19RTCDataChannelEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCDataChannelEvent.h' l='52' c='_ZN7WebCore19RTCDataChannelEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
<mbr r='WebCore::RTCDataChannelEvent::Init::channel' o='64' t='RefPtr&lt;WebCore::RTCDataChannel&gt;'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDataChannelEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDataChannelEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDataChannelEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDataChannelEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDataChannelEvent.cpp' l='65' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDataChannelEvent.cpp' l='172' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCDataChannelEvent.cpp' l='43' c='_ZN7WebCore19RTCDataChannelEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCDataChannelEvent.cpp' l='54' c='_ZN7WebCore19RTCDataChannelEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
