<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/airplay/WebKitPlaybackTargetAvailabilityEvent.h' l='43' ll='45'/>
<use f='webkit/Source/WebCore/Modules/airplay/WebKitPlaybackTargetAvailabilityEvent.h' l='47' c='_ZN7WebCore37WebKitPlaybackTargetAvailabilityEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/airplay/WebKitPlaybackTargetAvailabilityEvent.h' l='58' c='_ZN7WebCore37WebKitPlaybackTargetAvailabilityEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
<mbr r='WebCore::WebKitPlaybackTargetAvailabilityEvent::Init::availability' o='64' t='WTF::String'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitPlaybackTargetAvailabilityEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitPlaybackTargetAvailabilityEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitPlaybackTargetAvailabilityEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitPlaybackTargetAvailabilityEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitPlaybackTargetAvailabilityEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitPlaybackTargetAvailabilityEvent.cpp' l='168' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<use f='webkit/Source/WebCore/Modules/airplay/WebKitPlaybackTargetAvailabilityEvent.cpp' l='52' c='_ZN7WebCore37WebKitPlaybackTargetAvailabilityEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
