<dec f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.h' l='77' type='29'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='96' c='_ZN7WebCore5WHLSL5Token8typeNameENS1_4TypeE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='984' u='r' c='_ZN7WebCore5WHLSL5Lexer22consumeTokenFromStreamEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='992' u='r' c='_ZN7WebCore5WHLSL6Parser31parseComputeFunctionDeclarationEv'/>
