<inh f='webkit/Source/WebCore/dom/UIEventInit.h' l='34' c='WebCore::UIEventInit'/>
<def f='webkit/Source/WebCore/dom/InputEvent.h' l='39' ll='41'/>
<use f='webkit/Source/WebCore/dom/InputEvent.h' l='46' c='_ZN7WebCore10InputEvent6createERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='webkit/Source/WebCore/dom/InputEvent.h' l='60' c='_ZN7WebCore10InputEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<size>32</size>
<mbr r='WebCore::InputEvent::Init::data' o='192' t='WTF::String'/>
<use f='webkit/Source/WebCore/dom/InputEvent.cpp' l='53' c='_ZN7WebCore10InputEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<size>32</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInputEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInputEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>32</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInputEvent.cpp' l='59' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInputEvent.cpp' l='59' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInputEvent.cpp' l='69' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInputEvent.cpp' l='204' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>32</size>
