<use f='webkit/Source/WebCore/layout/FormattingState.h' l='61' u='r' c='_ZNK7WebCore6Layout15FormattingState21isFlexFormattingStateEv'/>
<dec f='webkit/Source/WebCore/layout/FormattingState.h' l='74' type='3'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/flex/FlexFormattingState.cpp' l='39' u='r' c='_ZN7WebCore6Layout19FlexFormattingStateC1EON3WTF3RefINS0_13FloatingStateENS2_12RawPtrTraitsIS4_EEEERNS0_11LayoutStateE'/>
