<def f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.h' l='390' type='const GCGLenum'/>
<def f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/GraphicsContextGL.h' l='390' type='const GCGLenum'/>
<use f='webkit/Source/WebCore/html/canvas/WebGL2RenderingContext.cpp' l='3136' u='r' c='_ZN7WebCore22WebGL2RenderingContext36baseInternalFormatFromInternalFormatEj'/>
<use f='webkit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='409'/>
<use f='webkit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5506' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='49' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='85' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='194' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='225' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='572' u='r' c='_ZN7WebCore17GraphicsContextGL30computeFormatAndTypeParametersEjjPjS1_'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='653' u='r' c='_ZN7WebCore24GraphicsContextGLCVANGLE24copyPixelBufferToTextureEP10__CVBufferjijjjNS_17GraphicsContextGL5FlipYE'/>
