<dec f='webkit/Source/WebCore/Modules/webgpu/WebGPUPipeline.h' l='55' type='RefPtr&lt;WebCore::WebGPUShaderModule&gt;'/>
<offset>0</offset>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUComputePipeline.h' l='51' u='r' c='_ZNK7WebCore21WebGPUComputePipeline13computeShaderEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.h' l='51' u='r' c='_ZNK7WebCore20WebGPURenderPipeline12vertexShaderEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.h' l='52' u='r' c='_ZNK7WebCore20WebGPURenderPipeline14fragmentShaderEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUComputePipeline.cpp' l='59' u='m' c='_ZN7WebCore21WebGPUComputePipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUComputePipeline.cpp' l='60' u='m' c='_ZN7WebCore21WebGPUComputePipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUComputePipeline.cpp' l='61' u='w' c='_ZN7WebCore21WebGPUComputePipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUComputePipeline.cpp' l='69' u='m' c='_ZN7WebCore21WebGPUComputePipeline9recompileERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUComputePipeline.cpp' l='70' u='m' c='_ZN7WebCore21WebGPUComputePipeline9recompileERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='60' u='m' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='61' u='r' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='61' u='r' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='63' u='m' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='64' u='w' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='66' u='m' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='68' u='w' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='68' u='r' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='70' u='m' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='71' u='w' c='_ZN7WebCore20WebGPURenderPipeline18cloneShaderModulesERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='82' u='m' c='_ZN7WebCore20WebGPURenderPipeline9recompileERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='83' u='m' c='_ZN7WebCore20WebGPURenderPipeline9recompileERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='86' u='m' c='_ZN7WebCore20WebGPURenderPipeline9recompileERKNS_12WebGPUDeviceE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPURenderPipeline.cpp' l='87' u='m' c='_ZN7WebCore20WebGPURenderPipeline9recompileERKNS_12WebGPUDeviceE'/>
