<def f='webkit/Source/WebCore/editing/Editor.h' l='280' ll='302'/>
<use f='webkit/Source/WebCore/editing/Editor.h' l='303' c='_ZN7WebCore6Editor7commandERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/editing/Editor.h' l='304' c='_ZN7WebCore6Editor7commandERKN3WTF6StringENS_19EditorCommandSourceE'/>
<size>32</size>
<fun r='_ZN7WebCore6Editor7CommandC1Ev'/>
<fun r='_ZN7WebCore6Editor7CommandC1EPKNS_21EditorInternalCommandENS_19EditorCommandSourceERNS_8DocumentE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeERKN3WTF6StringEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command11isSupportedEv'/>
<fun r='_ZNK7WebCore6Editor7Command9isEnabledEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5stateEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5valueEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command15isTextInsertionEv'/>
<fun r='_ZNK7WebCore6Editor7Command26allowExecutionWhenDisabledEv'/>
<mbr r='WebCore::Editor::Command::m_command' o='0' t='const WebCore::EditorInternalCommand *'/>
<mbr r='WebCore::Editor::Command::m_source' o='64' t='WebCore::EditorCommandSource'/>
<mbr r='WebCore::Editor::Command::m_document' o='128' t='RefPtr&lt;WebCore::Document&gt;'/>
<mbr r='WebCore::Editor::Command::m_frame' o='192' t='RefPtr&lt;WebCore::Frame&gt;'/>
<def f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/Editor.h' l='280' ll='302'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/Editor.h' l='303' c='_ZN7WebCore6Editor7commandERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/Editor.h' l='304' c='_ZN7WebCore6Editor7commandERKN3WTF6StringENS_19EditorCommandSourceE'/>
<use f='webkit/Source/WebKit/WebProcess/WebPage/WebPage.cpp' l='1467' c='_ZN6WebKit7WebPage23isEditingCommandEnabledERKN3WTF6StringE'/>
<use f='webkit/Source/WebKit/WebProcess/WebPage/WebPage.cpp' l='3110' c='_ZN6WebKit7WebPage15validateCommandERKN3WTF6StringEONS1_17CompletionHandlerIFvbiEEE'/>
<size>32</size>
<fun r='_ZN7WebCore6Editor7CommandC1Ev'/>
<fun r='_ZN7WebCore6Editor7CommandC1EPKNS_21EditorInternalCommandENS_19EditorCommandSourceERNS_8DocumentE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeERKN3WTF6StringEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command11isSupportedEv'/>
<fun r='_ZNK7WebCore6Editor7Command9isEnabledEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5stateEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5valueEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command15isTextInsertionEv'/>
<fun r='_ZNK7WebCore6Editor7Command26allowExecutionWhenDisabledEv'/>
<mbr r='WebCore::Editor::Command::m_command' o='0' t='const WebCore::EditorInternalCommand *'/>
<mbr r='WebCore::Editor::Command::m_source' o='64' t='WebCore::EditorCommandSource'/>
<mbr r='WebCore::Editor::Command::m_document' o='128' t='RefPtr&lt;WebCore::Document&gt;'/>
<mbr r='WebCore::Editor::Command::m_frame' o='192' t='RefPtr&lt;WebCore::Frame&gt;'/>
<use f='webkit/Source/WebCore/dom/Document.cpp' l='5741' c='_ZN7WebCoreL7commandEPNS_8DocumentERKN3WTF6StringEb'/>
<use f='webkit/Source/WebCore/dom/Document.cpp' l='5750' c='_ZN7WebCoreL7commandEPNS_8DocumentERKN3WTF6StringEb'/>
<size>32</size>
<use f='webkit/Source/WebCore/editing/EditorCommand.cpp' l='1820' c='_ZN7WebCore6Editor7commandERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/editing/EditorCommand.cpp' l='1822' c='_ZN7WebCore6Editor7commandERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/editing/EditorCommand.cpp' l='1825' c='_ZN7WebCore6Editor7commandERKN3WTF6StringENS_19EditorCommandSourceE'/>
<use f='webkit/Source/WebCore/editing/EditorCommand.cpp' l='1827' c='_ZN7WebCore6Editor7commandERKN3WTF6StringENS_19EditorCommandSourceE'/>
<size>32</size>
<fun r='_ZN7WebCore6Editor7CommandC1Ev'/>
<fun r='_ZN7WebCore6Editor7CommandC1EPKNS_21EditorInternalCommandENS_19EditorCommandSourceERNS_8DocumentE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeERKN3WTF6StringEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command11isSupportedEv'/>
<fun r='_ZNK7WebCore6Editor7Command9isEnabledEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5stateEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5valueEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command15isTextInsertionEv'/>
<fun r='_ZNK7WebCore6Editor7Command26allowExecutionWhenDisabledEv'/>
<use f='webkit/Source/WebCore/page/ContextMenuController.cpp' l='1236' c='_ZNK7WebCore21ContextMenuController21checkOrEnableIfNeededERNS_15ContextMenuItemE'/>
<use f='webkit/Source/WebCore/page/ContextMenuController.cpp' l='1242' c='_ZNK7WebCore21ContextMenuController21checkOrEnableIfNeededERNS_15ContextMenuItemE'/>
<use f='webkit/Source/WebCore/page/ContextMenuController.cpp' l='1248' c='_ZNK7WebCore21ContextMenuController21checkOrEnableIfNeededERNS_15ContextMenuItemE'/>
<size>32</size>
<use f='webkit/Source/WebKit/WebProcess/WebPage/mac/WebPageMac.mm' l='264' c='_ZN6WebKit7WebPage31executeKeypressCommandsInternalERKN3WTF6VectorIN7WebCore15KeypressCommandELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEEPNS3_13KeyboardEventE'/>
<size>32</size>
<use f='webkit/Source/WebKitLegacy/mac/WebView/WebHTMLView.mm' l='2681'/>
<use f='webkit/Source/WebKitLegacy/mac/WebView/WebHTMLView.mm' l='2685'/>
<use f='webkit/Source/WebKitLegacy/mac/WebView/WebHTMLView.mm' l='2689'/>
<use f='webkit/Source/WebKitLegacy/mac/WebView/WebHTMLView.mm' l='2693'/>
<use f='webkit/Source/WebKitLegacy/mac/WebView/WebHTMLView.mm' l='6618'/>
<size>32</size>
