<dec f='webkit/Source/WebCore/loader/ResourceLoadInfo.h' l='41' type='8'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/ResourceLoadInfo.h' l='41' type='8'/>
<use f='webkit/Source/WebCore/loader/ResourceLoadInfo.cpp' l='55' u='r' c='_ZN7WebCore17ContentExtensions14toResourceTypeENS_14CachedResource4TypeENS_19ResourceRequestBase9RequesterE'/>
<use f='webkit/Source/WebCore/loader/ResourceLoadInfo.cpp' l='97' u='a' c='_ZN7WebCore17ContentExtensions16readResourceTypeEN3WTF10StringViewE'/>
