<dec f='webkit/Source/WebCore/loader/appcache/ApplicationCacheHost.h' l='76' type='WTF::URL'/>
<offset>0</offset>
<use f='webkit/Source/WebCore/inspector/agents/InspectorApplicationCacheAgent.cpp' l='200' u='m' c='_ZN7WebCore30InspectorApplicationCacheAgent38buildObjectForApplicationCacheResourceERKNS_20ApplicationCacheHost12ResourceInfoE'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/ApplicationCacheHost.h' l='76' type='WTF::URL'/>
<offset>0</offset>
