<dec f='webkit/Source/WebCore/mathml/MathMLScriptsElement.h' l='39' type='0'/>
<use f='webkit/Source/WebCore/mathml/MathMLScriptsElement.cpp' l='44' u='r' c='_ZN7WebCoreL12scriptTypeOfERKNS_13QualifiedNameE'/>
<use f='webkit/Source/WebCore/rendering/mathml/RenderMathMLScripts.cpp' l='85' c='_ZN7WebCore19RenderMathMLScripts31validateAndGetReferenceChildrenEv'/>
<use f='webkit/Source/WebCore/rendering/mathml/RenderMathMLScripts.cpp' l='192' c='_ZN7WebCore19RenderMathMLScripts29computePreferredLogicalWidthsEv'/>
<use f='webkit/Source/WebCore/rendering/mathml/RenderMathMLScripts.cpp' l='264' u='r' c='_ZN7WebCore19RenderMathMLScripts15verticalMetricsERKNS0_17ReferenceChildrenE'/>
<use f='webkit/Source/WebCore/rendering/mathml/RenderMathMLScripts.cpp' l='284' c='_ZN7WebCore19RenderMathMLScripts15verticalMetricsERKNS0_17ReferenceChildrenE'/>
<use f='webkit/Source/WebCore/rendering/mathml/RenderMathMLScripts.cpp' l='381' c='_ZN7WebCore19RenderMathMLScripts11layoutBlockEbNS_10LayoutUnitE'/>
