<dec f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.h' l='149' type='101'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='240' c='_ZN7WebCore5WHLSL5Token8typeNameENS1_4TypeE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='1520' u='r' c='_ZN7WebCore5WHLSL5Lexer22consumeTokenFromStreamEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1865' u='m' c='_ZN7WebCore5WHLSL6Parser24completePossibleMultiplyEON3WTF9UniqueRefINS0_3AST10ExpressionEEE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1884' u='r' c='_ZN7WebCore5WHLSL6Parser24completePossibleMultiplyEON3WTF9UniqueRefINS0_3AST10ExpressionEEE'/>
