<dec f='webkit/Source/WebCore/Modules/mediasession/MediaSessionActionDetails.h' l='35' type='WebCore::MediaSessionAction'/>
<offset>0</offset>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaSessionActionDetails.cpp' l='66' u='w' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaSessionActionDetails.cpp' l='130' u='r' c='_ZN7WebCore21convertDictionaryToJSERN3JSC14JSGlobalObjectERNS_17JSDOMGlobalObjectERKNS_25MediaSessionActionDetailsE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1090' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1093' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1096' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1099' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1111' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1118' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1123' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1126' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/html/MediaElementSession.cpp' l='1129' u='w' c='_ZN7WebCore19MediaElementSession30didReceiveRemoteControlCommandENS_20PlatformMediaSession24RemoteControlCommandTypeERKNS1_21RemoteCommandArgumentE'/>
<use f='webkit/Source/WebCore/Modules/mediasession/MediaSession.cpp' l='87' u='r' c='_ZN7WebCoreL36platformCommandForMediaSessionActionERKNS_25MediaSessionActionDetailsE'/>
<use f='webkit/Source/WebCore/Modules/mediasession/MediaSession.cpp' l='271' u='r' c='_ZN7WebCore12MediaSession17callActionHandlerERKNS_25MediaSessionActionDetailsENS0_23TriggerGestureIndicatorE'/>
