<dec f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.h' l='65' type='17'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='72' c='_ZN7WebCore5WHLSL5Token8typeNameENS1_4TypeE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='1050' u='r' c='_ZN7WebCore5WHLSL5Lexer22consumeTokenFromStreamEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1231' u='r' c='_ZN7WebCore5WHLSL6Parser16parseDoWhileLoopEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1309' c='_ZN7WebCore5WHLSL6Parser14parseStatementEv'/>
