<dec f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.h' l='63' type='15'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='68' c='_ZN7WebCore5WHLSL5Token8typeNameENS1_4TypeE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='1095' u='r' c='_ZN7WebCore5WHLSL5Lexer22consumeTokenFromStreamEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1175' u='r' c='_ZN7WebCore5WHLSL6Parser12parseForLoopEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1301' c='_ZN7WebCore5WHLSL6Parser14parseStatementEv'/>
