<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/GraphicsLayerCA.h' l='514' type='0'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/GraphicsLayerCA.h' l='520' u='r' c='_ZN7WebCore15GraphicsLayerCA14moveAnimationsEPNS_15PlatformCALayerES2_'/>
<dec f='webkit/Source/WebCore/platform/graphics/ca/GraphicsLayerCA.h' l='514' type='0'/>
<use f='webkit/Source/WebCore/platform/graphics/ca/GraphicsLayerCA.h' l='520' u='r' c='_ZN7WebCore15GraphicsLayerCA14moveAnimationsEPNS_15PlatformCALayerES2_'/>
<use f='webkit/Source/WebCore/platform/graphics/ca/GraphicsLayerCA.cpp' l='697' c='_ZN7WebCore15GraphicsLayerCA24moveOrCopyLayerAnimationENS0_10MoveOrCopyERKN3WTF6StringENSt3__18optionalINS2_7SecondsEEEPNS_15PlatformCALayerESB_'/>
