<def f='webkit/Source/WebCore/page/EventSource.h' l='52' ll='54'/>
<use f='webkit/Source/WebCore/page/EventSource.h' l='55' c='_ZN7WebCore11EventSource6createERNS_22ScriptExecutionContextERKN3WTF6StringERKNS0_4InitE'/>
<use f='webkit/Source/WebCore/page/EventSource.h' l='74' c='_ZN7WebCore11EventSourceC1ERNS_22ScriptExecutionContextERKN3WTF3URLERKNS0_4InitE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEventSource.h' l='98' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEventSource.h' l='98' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>1</size>
<mbr r='WebCore::EventSource::Init::withCredentials' o='0' t='bool'/>
<use f='webkit/Source/WebCore/page/EventSource.cpp' l='57' c='_ZN7WebCore11EventSourceC1ERNS_22ScriptExecutionContextERKN3WTF3URLERKNS0_4InitE'/>
<use f='webkit/Source/WebCore/page/EventSource.cpp' l='67' c='_ZN7WebCore11EventSource6createERNS_22ScriptExecutionContextERKN3WTF6StringERKNS0_4InitE'/>
<size>1</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEventSource.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEventSource.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEventSource.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEventSource.cpp' l='151' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>1</size>
