<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/dom/TransitionEvent.h' l='41' ll='45'/>
<use f='webkit/Source/WebCore/dom/TransitionEvent.h' l='47' c='_ZN7WebCore15TransitionEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/dom/TransitionEvent.h' l='64' c='_ZN7WebCore15TransitionEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/dom/TransitionEvent.cpp' l='44' c='_ZN7WebCore15TransitionEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>32</size>
<mbr r='WebCore::TransitionEvent::Init::propertyName' o='64' t='WTF::String'/>
<mbr r='WebCore::TransitionEvent::Init::elapsedTime' o='128' t='double'/>
<mbr r='WebCore::TransitionEvent::Init::pseudoElement' o='192' t='WTF::String'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSTransitionEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSTransitionEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSTransitionEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSTransitionEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSTransitionEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSTransitionEvent.cpp' l='192' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>32</size>
