<dec f='webkit/Source/WebCore/bindings/js/ExceptionDetails.h' l='34' type='0'/>
<use f='webkit/Source/WebCore/bindings/js/ExceptionDetails.h' l='42'/>
<use f='webkit/Source/WebCore/bindings/js/ExceptionDetails.h' l='56'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/ExceptionDetails.h' l='34' type='0'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/ExceptionDetails.h' l='42'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/ExceptionDetails.h' l='56'/>
<use f='webkit/Source/WebKit/UIProcess/API/Cocoa/WKWebView.mm' l='212' c='_Z27nsErrorFromExceptionDetailsRKN7WebCore16ExceptionDetailsE'/>
