<dec f='webkit/Source/WebCore/Modules/webgpu/WHLSL/AST/WHLSLEntryPointType.h' l='41' type='2'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/AST/WHLSLEntryPointType.h' l='51' c='_ZN7WebCore5WHLSL3AST8toStringENS1_14EntryPointTypeE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLChecker.cpp' l='530' c='_ZN7WebCore5WHLSL7Checker15checkShaderTypeERKNS0_3AST18FunctionDefinitionE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLFunctionStageChecker.cpp' l='57' u='r' c='_ZN7WebCore5WHLSL20FunctionStageChecker5visitERNS0_3AST14CallExpressionE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLGatherEntryPointItems.cpp' l='180' u='r' c='_ZN7WebCore5WHLSL21gatherEntryPointItemsERKNS0_10IntrinsicsERNS0_3AST18FunctionDefinitionE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1001' u='a' c='_ZN7WebCore5WHLSL6Parser31parseComputeFunctionDeclarationEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/AST/WHLSLBuiltInSemantic.cpp' l='120' c='_ZNK7WebCore5WHLSL3AST15BuiltInSemantic34isAcceptableForShaderItemDirectionENS1_12BaseSemantic19ShaderItemDirectionERKNSt3__18optionalINS1_14EntryPointTypeEEE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/AST/WHLSLStageInOutSemantic.cpp' l='68' c='_ZNK7WebCore5WHLSL3AST18StageInOutSemantic34isAcceptableForShaderItemDirectionENS1_12BaseSemantic19ShaderItemDirectionERKNSt3__18optionalINS1_14EntryPointTypeEEE'/>
