<def f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineContentBreaker.h' l='90' ll='97'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineContentBreaker.h' l='92' c='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunC1ERKS3_'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineContentBreaker.h' l='93' c='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunaSERKS3_'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineContentBreaker.h' l='93' c='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunaSERKS3_'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineContentBreaker.h' l='98'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineContentBreaker.h' l='124' c='_ZNK7WebCore6Layout20InlineContentBreaker18tryBreakingTextRunERKNS1_17ContinuousContent3RunEfNSt3__18optionalIfEEb'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineContentBreaker.h' l='142' c='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunC1ERKS3_'/>
<size>16</size>
<fun r='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunC1ERKNS0_10InlineItemEf'/>
<fun r='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunC1ERKS3_'/>
<fun r='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunaSERKS3_'/>
<mbr r='WebCore::Layout::InlineContentBreaker::ContinuousContent::Run::inlineItem' o='0' t='const WebCore::Layout::InlineItem &amp;'/>
<mbr r='WebCore::Layout::InlineContentBreaker::ContinuousContent::Run::logicalWidth' o='64' t='WebCore::InlineLayoutUnit'/>
<fun r='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunC1ERKNS0_10InlineItemEf'/>
<fun r='_ZN7WebCore6Layout20InlineContentBreaker17ContinuousContent3RunC1ERKS3_'/>
<use f='webkit/Source/WebCore/layout/formattingContexts/inline/InlineContentBreaker.cpp' l='426' c='_ZNK7WebCore6Layout20InlineContentBreaker18tryBreakingTextRunERKNS1_17ContinuousContent3RunEfNSt3__18optionalIfEEb'/>
<size>16</size>
