<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/webgpu/GPUUncapturedErrorEvent.h' l='39' ll='41'/>
<use f='webkit/Source/WebCore/Modules/webgpu/GPUUncapturedErrorEvent.h' l='43' c='_ZN7WebCore23GPUUncapturedErrorEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/GPUUncapturedErrorEvent.h' l='49' c='_ZN7WebCore23GPUUncapturedErrorEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSGPUUncapturedErrorEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSGPUUncapturedErrorEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>24</size>
<mbr r='WebCore::GPUUncapturedErrorEvent::Init::error' o='64' t='WebCore::GPUError'/>
<use f='webkit/Source/WebCore/Modules/webgpu/GPUUncapturedErrorEvent.cpp' l='37' c='_ZN7WebCore23GPUUncapturedErrorEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/GPUUncapturedErrorEvent.cpp' l='47' c='_ZN7WebCore23GPUUncapturedErrorEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>24</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSGPUUncapturedErrorEvent.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSGPUUncapturedErrorEvent.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSGPUUncapturedErrorEvent.cpp' l='70' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSGPUUncapturedErrorEvent.cpp' l='179' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
