<dec f='webkit/Source/WebCore/rendering/HitTestRequest.h' l='35' type='4'/>
<use f='webkit/Source/WebCore/rendering/HitTestRequest.h' l='63' u='r' c='_ZNK7WebCore14HitTestRequest4moveEv'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/HitTestRequest.h' l='35' type='4'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/HitTestRequest.h' l='63' u='r' c='_ZNK7WebCore14HitTestRequest4moveEv'/>
<use f='webkit/Source/WebCore/page/EventHandler.cpp' l='935' u='r' c='_ZN7WebCore12EventHandler27updateSelectionForMouseDragEv'/>
<use f='webkit/Source/WebCore/page/EventHandler.cpp' l='1964' u='r' c='_ZN7WebCore12EventHandler20handleMouseMoveEventERKNS_18PlatformMouseEventEPNS_13HitTestResultEb'/>
<use f='webkit/Source/WebCore/page/EventHandler.cpp' l='3392' u='r' c='_ZN7WebCore12EventHandler15hoverTimerFiredEv'/>
