<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/encryptedmedia/legacy/WebKitMediaKeyMessageEvent.h' l='46' ll='49'/>
<use f='webkit/Source/WebCore/Modules/encryptedmedia/legacy/WebKitMediaKeyMessageEvent.h' l='51' c='_ZN7WebCore26WebKitMediaKeyMessageEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/encryptedmedia/legacy/WebKitMediaKeyMessageEvent.h' l='63' c='_ZN7WebCore26WebKitMediaKeyMessageEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/encryptedmedia/legacy/WebKitMediaKeyMessageEvent.cpp' l='46' c='_ZN7WebCore26WebKitMediaKeyMessageEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>24</size>
<mbr r='WebCore::WebKitMediaKeyMessageEvent::Init::message' o='64' t='RefPtr&lt;JSC::Uint8Array&gt;'/>
<mbr r='WebCore::WebKitMediaKeyMessageEvent::Init::destinationURL' o='128' t='WTF::String'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyMessageEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyMessageEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyMessageEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyMessageEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyMessageEvent.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebKitMediaKeyMessageEvent.cpp' l='184' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
