<def f='webkit/Source/WebKit/Platform/Module.h' l='46' ll='76'/>
<use f='webkit/Source/WebKit/Platform/Module.h' l='48' c='_ZN6WebKit6ModuleC1ERKS0_'/>
<use f='webkit/Source/WebKit/Platform/Module.h' l='48' c='_ZN6WebKit6ModuleaSERKS0_'/>
<use f='webkit/Source/WebKit/Platform/Module.h' l='48' c='_ZN6WebKit6ModuleaSERKS0_'/>
<size>16</size>
<fun r='_ZN6WebKit6ModuleC1ERKS0_'/>
<fun r='_ZN6WebKit6ModuleC1ERKN3WTF6StringE'/>
<fun r='_ZN6WebKit6ModuleD1Ev'/>
<fun r='_ZN6WebKit6Module4loadEv'/>
<fun r='_ZN6WebKit6Module6unloadEv'/>
<fun r='_ZNK6WebKit6Module16bundleIdentifierEv'/>
<fun r='_ZNK6WebKit6Module15functionPointerEPKc'/>
<fun r='_ZNK6WebKit6Module23platformFunctionPointerEPKc'/>
<mbr r='WebKit::Module::m_path' o='0' t='WTF::String'/>
<mbr r='WebKit::Module::m_bundle' o='64' t='RetainPtr&lt;CFBundleRef&gt;'/>
<fun r='_ZNK6WebKit6Module15functionPointerEPKc'/>
<fun r='_ZN6WebKit6ModuleC1ERKN3WTF6StringE'/>
<fun r='_ZN6WebKit6ModuleD1Ev'/>
<use f='webkit/Source/WebKit/Shared/Plugins/Netscape/NetscapePluginModule.h' l='66' c='_ZNK6WebKit20NetscapePluginModule6moduleEv'/>
<use f='webkit/Source/WebKit/Shared/Plugins/Netscape/NetscapePluginModule.h' l='101'/>
<size>16</size>
<use f='webkit/Source/WebKit/Shared/Plugins/Netscape/NetscapePluginModule.cpp' l='209' c='_ZN6WebKit20NetscapePluginModule7tryLoadEv'/>
<size>16</size>
