<dec f='webkit/Source/WebKit/Shared/ResourceLoadInfo.h' l='53' type='14'/>
<use f='webkit/Source/WebKit/Shared/ResourceLoadInfo.h' l='153'/>
<use f='webkit/Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp' l='424' u='r' c='_ZN6WebKit21NetworkResourceLoader16resourceLoadInfoEv'/>
<use f='webkit/Source/WebKit/UIProcess/API/Cocoa/_WKResourceLoadInfo.mm' l='68' c='_ZL32toWKResourceLoadInfoResourceTypeN6WebKit16ResourceLoadInfo4TypeE'/>
