<dec f='webkit/Source/WebKit/Shared/ResourceLoadInfo.h' l='50' type='11'/>
<use f='webkit/Source/WebKit/Shared/ResourceLoadInfo.h' l='150'/>
<use f='webkit/Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp' l='410' u='r' c='_ZN6WebKit21NetworkResourceLoader16resourceLoadInfoEv'/>
<use f='webkit/Source/WebKit/UIProcess/API/Cocoa/_WKResourceLoadInfo.mm' l='62' c='_ZL32toWKResourceLoadInfoResourceTypeN6WebKit16ResourceLoadInfo4TypeE'/>
