<def f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libwebm/webm_parser/include/webm/dom_types.h' l='1756' ll='1773'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libwebm/webm_parser/include/webm/dom_types.h' l='1770' c='_ZNK4webm3TageqERKS0_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libwebm/webm_parser/include/webm/callback.h' l='327' c='_ZN4webm8Callback5OnTagERKNS_15ElementMetadataERKNS_3TagE'/>
<size>104</size>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libwebm/webm_parser/include/webm/dom_types.h' l='1753'>/**
 A parsed \WebMID{Tag} element.
 */</doc>
<mbr r='webm::Tag::targets' o='0' t='Element&lt;webm::Targets&gt;'/>
<mbr r='webm::Tag::tags' o='640' t='std::vector&lt;Element&lt;SimpleTag&gt;&gt;'/>
<fun r='_ZNK4webm3TageqERKS0_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libwebm/webm_parser/src/callback.cc' l='130' c='_ZN4webm8Callback5OnTagERKNS_15ElementMetadataERKNS_3TagE'/>
<size>104</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libwebm/webm_parser/src/tag_parser.h' l='22'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libwebm/webm_parser/src/tag_parser.h' l='25' c='_ZN4webm9TagParserC1Ev'/>
<size>104</size>
<def f='webkit/WebKitBuild/Debug/usr/local/include/webm/dom_types.h' l='1756' ll='1773'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webm/dom_types.h' l='1770' c='_ZNK4webm3TageqERKS0_'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webm/callback.h' l='327' c='_ZN4webm8Callback5OnTagERKNS_15ElementMetadataERKNS_3TagE'/>
<size>104</size>
<doc f='webkit/WebKitBuild/Debug/usr/local/include/webm/dom_types.h' l='1753'>/**
 A parsed \WebMID{Tag} element.
 */</doc>
<mbr r='webm::Tag::targets' o='0' t='Element&lt;webm::Targets&gt;'/>
<mbr r='webm::Tag::tags' o='640' t='std::vector&lt;Element&lt;SimpleTag&gt;&gt;'/>
<fun r='_ZNK4webm3TageqERKS0_'/>
