<def f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_processing/agc/agc.h' l='22' ll='47'/>
<size>6120</size>
<fun r='_ZN6webrtc3AgcC1Ev'/>
<fun r='_ZN6webrtc3AgcD1Ev'/>
<fun r='_ZN6webrtc3Agc7ProcessEPKsmi'/>
<fun r='_ZN6webrtc3Agc13GetRmsErrorDbEPi'/>
<fun r='_ZN6webrtc3Agc5ResetEv'/>
<fun r='_ZN6webrtc3Agc21set_target_level_dbfsEi'/>
<fun r='_ZNK6webrtc3Agc17target_level_dbfsEv'/>
<fun r='_ZNK6webrtc3Agc17voice_probabilityEv'/>
<mbr r='webrtc::Agc::target_level_loudness_' o='64' t='double'/>
<mbr r='webrtc::Agc::target_level_dbfs_' o='128' t='int'/>
<mbr r='webrtc::Agc::histogram_' o='192' t='std::unique_ptr&lt;LoudnessHistogram&gt;'/>
<mbr r='webrtc::Agc::inactive_histogram_' o='256' t='std::unique_ptr&lt;LoudnessHistogram&gt;'/>
<mbr r='webrtc::Agc::vad_' o='320' t='webrtc::VoiceActivityDetector'/>
<fun r='_ZN6webrtc3AgcC1Ev'/>
<fun r='_ZN6webrtc3AgcD1Ev'/>
<fun r='_ZN6webrtc3Agc7ProcessEPKsmi'/>
<fun r='_ZN6webrtc3Agc13GetRmsErrorDbEPi'/>
<fun r='_ZN6webrtc3Agc5ResetEv'/>
<fun r='_ZN6webrtc3Agc21set_target_level_dbfsEi'/>
<fun r='_ZNK6webrtc3Agc17target_level_dbfsEv'/>
<fun r='_ZNK6webrtc3Agc17voice_probabilityEv'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_processing/agc/agc_manager_direct.h' l='87' c='_ZN6webrtc16AgcManagerDirectC1EPNS_3AgcEiii'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_processing/agc/agc_manager_direct.h' l='141' c='_ZN6webrtc7MonoAgc7set_agcEPNS_3AgcE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_processing/agc/agc_manager_direct.h' l='161'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_processing/agc/agc_manager_direct.cc' l='144' c='_ZN6webrtc7MonoAgcC1EPNS_13ApmDataDumperEiibi'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_processing/agc/agc_manager_direct.cc' l='404' c='_ZN6webrtc16AgcManagerDirectC1EPNS_3AgcEiii'/>
<size>6120</size>
