<dec f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/audio/channel_layout.h' l='132' type='3'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/audio/utility/channel_mixing_matrix.cc' l='263' u='r' c='_ZN6webrtc19ChannelMixingMatrix26CreateTransformationMatrixEPNSt3__16vectorINS2_IfNS1_9allocatorIfEEEENS3_IS5_EEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/audio/utility/channel_mixing_matrix.cc' l='266' u='r' c='_ZN6webrtc19ChannelMixingMatrix26CreateTransformationMatrixEPNSt3__16vectorINS2_IfNS1_9allocatorIfEEEENS3_IS5_EEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/audio/utility/channel_mixing_matrix.cc' l='267' u='r' c='_ZN6webrtc19ChannelMixingMatrix26CreateTransformationMatrixEPNSt3__16vectorINS2_IfNS1_9allocatorIfEEEENS3_IS5_EEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/audio/utility/channel_mixing_matrix.cc' l='270' u='r' c='_ZN6webrtc19ChannelMixingMatrix26CreateTransformationMatrixEPNSt3__16vectorINS2_IfNS1_9allocatorIfEEEENS3_IS5_EEEE'/>
<dec f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/audio/channel_layout.h' l='132' type='3'/>
