<inh f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet.h' l='50' c='webrtc::rtcp::RtcpPacket'/>
<def f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/app.h' l='24' ll='63'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/app.h' l='28' c='_ZN6webrtc4rtcp3AppC1EOS1_'/>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.h' l='38' c='webrtc::rtcp::RemoteEstimate'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.h' l='38'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.h' l='41' c='_ZN6webrtc4rtcp14RemoteEstimateC1EONS0_3AppE'/>
<size>48</size>
<smbr r='webrtc::rtcp::App::kPacketType' t='const uint8_t'/>
<fun r='_ZN6webrtc4rtcp3AppC1Ev'/>
<fun r='_ZN6webrtc4rtcp3AppC1EOS1_'/>
<fun r='_ZN6webrtc4rtcp3AppD1Ev'/>
<fun r='_ZN6webrtc4rtcp3App5ParseERKNS0_12CommonHeaderE'/>
<fun r='_ZN6webrtc4rtcp3App10SetSubTypeEh'/>
<fun r='_ZN6webrtc4rtcp3App7SetNameEj'/>
<fun r='_ZN6webrtc4rtcp3App7SetDataEPKhm'/>
<fun r='_ZNK6webrtc4rtcp3App8sub_typeEv'/>
<fun r='_ZNK6webrtc4rtcp3App4nameEv'/>
<fun r='_ZNK6webrtc4rtcp3App9data_sizeEv'/>
<fun r='_ZNK6webrtc4rtcp3App4dataEv'/>
<fun r='_ZNK6webrtc4rtcp3App11BlockLengthEv'/>
<fun r='_ZNK6webrtc4rtcp3App6CreateEPhPmmN3rtc12FunctionViewIFvNS4_9ArrayViewIKhLln4711EEEEEE'/>
<fun r='_ZN6webrtc4rtcp3App9NameToIntEPKc'/>
<smbr r='webrtc::rtcp::App::kAppBaseLength' t='const size_t'/>
<smbr r='webrtc::rtcp::App::kMaxDataSize' t='const size_t'/>
<mbr r='webrtc::rtcp::App::sub_type_' o='96' t='uint8_t'/>
<mbr r='webrtc::rtcp::App::name_' o='128' t='uint32_t'/>
<mbr r='webrtc::rtcp::App::data_' o='192' t='rtc::Buffer'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.cc' l='134' c='_ZN6webrtc4rtcp14RemoteEstimateC1EONS0_3AppE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.cc' l='135' c='_ZN6webrtc4rtcp14RemoteEstimateC1EONS0_3AppE'/>
<size>48</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_receiver.cc' l='716' c='_ZN6webrtc12RTCPReceiver9HandleAppERKNS_4rtcp12CommonHeaderEPNS0_17PacketInformationE'/>
<size>48</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_sender.cc' l='544' c='_ZN6webrtc10RTCPSender8BuildAPPERKNS0_11RtcpContextERNS0_12PacketSenderE'/>
<size>48</size>
<inh f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/rtp_rtcp/source/rtcp_packet.h' l='50' c='webrtc::rtcp::RtcpPacket'/>
<def f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/rtp_rtcp/source/rtcp_packet/app.h' l='24' ll='63'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/rtp_rtcp/source/rtcp_packet/app.h' l='28' c='_ZN6webrtc4rtcp3AppC1EOS1_'/>
<ovr f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.h' l='38' c='webrtc::rtcp::RemoteEstimate'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.h' l='38'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/rtp_rtcp/source/rtcp_packet/remote_estimate.h' l='41' c='_ZN6webrtc4rtcp14RemoteEstimateC1EONS0_3AppE'/>
<size>48</size>
<smbr r='webrtc::rtcp::App::kPacketType' t='const uint8_t'/>
<fun r='_ZN6webrtc4rtcp3AppC1Ev'/>
<fun r='_ZN6webrtc4rtcp3AppC1EOS1_'/>
<fun r='_ZN6webrtc4rtcp3AppD1Ev'/>
<fun r='_ZN6webrtc4rtcp3App5ParseERKNS0_12CommonHeaderE'/>
<fun r='_ZN6webrtc4rtcp3App10SetSubTypeEh'/>
<fun r='_ZN6webrtc4rtcp3App7SetNameEj'/>
<fun r='_ZN6webrtc4rtcp3App7SetDataEPKhm'/>
<fun r='_ZNK6webrtc4rtcp3App8sub_typeEv'/>
<fun r='_ZNK6webrtc4rtcp3App4nameEv'/>
<fun r='_ZNK6webrtc4rtcp3App9data_sizeEv'/>
<fun r='_ZNK6webrtc4rtcp3App4dataEv'/>
<fun r='_ZNK6webrtc4rtcp3App11BlockLengthEv'/>
<fun r='_ZNK6webrtc4rtcp3App6CreateEPhPmmN3rtc12FunctionViewIFvNS4_9ArrayViewIKhLln4711EEEEEE'/>
<fun r='_ZN6webrtc4rtcp3App9NameToIntEPKc'/>
<smbr r='webrtc::rtcp::App::kAppBaseLength' t='const size_t'/>
<smbr r='webrtc::rtcp::App::kMaxDataSize' t='const size_t'/>
<mbr r='webrtc::rtcp::App::sub_type_' o='96' t='uint8_t'/>
<mbr r='webrtc::rtcp::App::name_' o='128' t='uint32_t'/>
<mbr r='webrtc::rtcp::App::data_' o='192' t='rtc::Buffer'/>
