<def f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='82' ll='111'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='88' c='_ZN6webrtc10VideoFrame7Builder22set_video_frame_bufferERKN3rtc13scoped_refptrINS_16VideoFrameBufferEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='90' c='_ZN6webrtc10VideoFrame7Builder16set_timestamp_msEx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='91' c='_ZN6webrtc10VideoFrame7Builder16set_timestamp_usEx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='92' c='_ZN6webrtc10VideoFrame7Builder17set_timestamp_rtpEj'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='93' c='_ZN6webrtc10VideoFrame7Builder15set_ntp_time_msEx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='94' c='_ZN6webrtc10VideoFrame7Builder12set_rotationENS_13VideoRotationE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='95' c='_ZN6webrtc10VideoFrame7Builder15set_color_spaceERKNSt3__18optionalINS_10ColorSpaceEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='96' c='_ZN6webrtc10VideoFrame7Builder15set_color_spaceEPKNS_10ColorSpaceE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='97' c='_ZN6webrtc10VideoFrame7Builder6set_idEt'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='98' c='_ZN6webrtc10VideoFrame7Builder15set_update_rectERKNSt3__18optionalINS0_10UpdateRectEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='99' c='_ZN6webrtc10VideoFrame7Builder16set_packet_infosENS_14RtpPacketInfosE'/>
<size>144</size>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.h' l='81'>// Preferred way of building VideoFrame objects.</doc>
<fun r='_ZN6webrtc10VideoFrame7BuilderC1Ev'/>
<fun r='_ZN6webrtc10VideoFrame7BuilderD1Ev'/>
<fun r='_ZN6webrtc10VideoFrame7Builder5buildEv'/>
<fun r='_ZN6webrtc10VideoFrame7Builder22set_video_frame_bufferERKN3rtc13scoped_refptrINS_16VideoFrameBufferEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_timestamp_msEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_timestamp_usEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder17set_timestamp_rtpEj'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_ntp_time_msEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder12set_rotationENS_13VideoRotationE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_color_spaceERKNSt3__18optionalINS_10ColorSpaceEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_color_spaceEPKNS_10ColorSpaceE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder6set_idEt'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_update_rectERKNSt3__18optionalINS0_10UpdateRectEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_packet_infosENS_14RtpPacketInfosE'/>
<mbr r='webrtc::VideoFrame::Builder::id_' o='0' t='uint16_t'/>
<mbr r='webrtc::VideoFrame::Builder::video_frame_buffer_' o='64' t='rtc::scoped_refptr&lt;webrtc::VideoFrameBuffer&gt;'/>
<mbr r='webrtc::VideoFrame::Builder::timestamp_us_' o='128' t='int64_t'/>
<mbr r='webrtc::VideoFrame::Builder::timestamp_rtp_' o='192' t='uint32_t'/>
<mbr r='webrtc::VideoFrame::Builder::ntp_time_ms_' o='256' t='int64_t'/>
<mbr r='webrtc::VideoFrame::Builder::rotation_' o='320' t='webrtc::VideoRotation'/>
<mbr r='webrtc::VideoFrame::Builder::color_space_' o='352' t='absl::optional&lt;ColorSpace&gt;'/>
<mbr r='webrtc::VideoFrame::Builder::update_rect_' o='928' t='absl::optional&lt;UpdateRect&gt;'/>
<mbr r='webrtc::VideoFrame::Builder::packet_infos_' o='1088' t='webrtc::RtpPacketInfos'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='171' c='_ZN6webrtc10VideoFrame7Builder22set_video_frame_bufferERKN3rtc13scoped_refptrINS_16VideoFrameBufferEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='177' c='_ZN6webrtc10VideoFrame7Builder16set_timestamp_msEx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='183' c='_ZN6webrtc10VideoFrame7Builder16set_timestamp_usEx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='189' c='_ZN6webrtc10VideoFrame7Builder17set_timestamp_rtpEj'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='195' c='_ZN6webrtc10VideoFrame7Builder15set_ntp_time_msEx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='200' c='_ZN6webrtc10VideoFrame7Builder12set_rotationENS_13VideoRotationE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='205' c='_ZN6webrtc10VideoFrame7Builder15set_color_spaceERKNSt3__18optionalINS_10ColorSpaceEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='211' c='_ZN6webrtc10VideoFrame7Builder15set_color_spaceEPKNS_10ColorSpaceE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='218' c='_ZN6webrtc10VideoFrame7Builder6set_idEt'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='223' c='_ZN6webrtc10VideoFrame7Builder15set_update_rectERKNSt3__18optionalINS0_10UpdateRectEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/video/video_frame.cc' l='229' c='_ZN6webrtc10VideoFrame7Builder16set_packet_infosENS_14RtpPacketInfosE'/>
<size>144</size>
<fun r='_ZN6webrtc10VideoFrame7BuilderC1Ev'/>
<fun r='_ZN6webrtc10VideoFrame7BuilderD1Ev'/>
<fun r='_ZN6webrtc10VideoFrame7Builder5buildEv'/>
<fun r='_ZN6webrtc10VideoFrame7Builder22set_video_frame_bufferERKN3rtc13scoped_refptrINS_16VideoFrameBufferEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_timestamp_msEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_timestamp_usEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder17set_timestamp_rtpEj'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_ntp_time_msEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder12set_rotationENS_13VideoRotationE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_color_spaceERKNSt3__18optionalINS_10ColorSpaceEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_color_spaceEPKNS_10ColorSpaceE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder6set_idEt'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_update_rectERKNSt3__18optionalINS0_10UpdateRectEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_packet_infosENS_14RtpPacketInfosE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/media/base/video_broadcaster.cc' l='75' c='_ZN3rtc16VideoBroadcaster7OnFrameERKN6webrtc10VideoFrameE'/>
<size>144</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/video_coding/codecs/vp8/libvpx_vp8_decoder.cc' l='363' c='_ZN6webrtc16LibvpxVp8Decoder11ReturnFrameEPK9vpx_imagejiPKNS_10ColorSpaceE'/>
<size>144</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/video_coding/codecs/vp9/libvpx_vp9_decoder.cc' l='349' c='_ZN6webrtc16LibvpxVp9Decoder11ReturnFrameEPK9vpx_imagejiPKNS_10ColorSpaceE'/>
<size>144</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/sdk/WebKit/WebKitDecoder.mm' l='173' c='_ZN6webrtc24videoDecoderTaskCompleteEPvjP10__CVBufferj'/>
<size>144</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/sdk/objc/native/src/objc_video_decoder_factory.mm' l='60' c='_ZN6webrtc12_GLOBAL__N_116ObjCVideoDecoder30RegisterDecodeCompleteCallbackEPNS_20DecodedImageCallbackE'/>
<size>144</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/video/video_stream_encoder.cc' l='1786' c='_ZN6webrtc18VideoStreamEncoder12SendKeyFrameEv'/>
<size>144</size>
<def f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='82' ll='111'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='88' c='_ZN6webrtc10VideoFrame7Builder22set_video_frame_bufferERKN3rtc13scoped_refptrINS_16VideoFrameBufferEEE'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='90' c='_ZN6webrtc10VideoFrame7Builder16set_timestamp_msEx'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='91' c='_ZN6webrtc10VideoFrame7Builder16set_timestamp_usEx'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='92' c='_ZN6webrtc10VideoFrame7Builder17set_timestamp_rtpEj'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='93' c='_ZN6webrtc10VideoFrame7Builder15set_ntp_time_msEx'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='94' c='_ZN6webrtc10VideoFrame7Builder12set_rotationENS_13VideoRotationE'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='95' c='_ZN6webrtc10VideoFrame7Builder15set_color_spaceERKNSt3__18optionalINS_10ColorSpaceEEE'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='96' c='_ZN6webrtc10VideoFrame7Builder15set_color_spaceEPKNS_10ColorSpaceE'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='97' c='_ZN6webrtc10VideoFrame7Builder6set_idEt'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='98' c='_ZN6webrtc10VideoFrame7Builder15set_update_rectERKNSt3__18optionalINS0_10UpdateRectEEE'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='99' c='_ZN6webrtc10VideoFrame7Builder16set_packet_infosENS_14RtpPacketInfosE'/>
<size>144</size>
<doc f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/video/video_frame.h' l='81'>// Preferred way of building VideoFrame objects.</doc>
<fun r='_ZN6webrtc10VideoFrame7BuilderC1Ev'/>
<fun r='_ZN6webrtc10VideoFrame7BuilderD1Ev'/>
<fun r='_ZN6webrtc10VideoFrame7Builder5buildEv'/>
<fun r='_ZN6webrtc10VideoFrame7Builder22set_video_frame_bufferERKN3rtc13scoped_refptrINS_16VideoFrameBufferEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_timestamp_msEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_timestamp_usEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder17set_timestamp_rtpEj'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_ntp_time_msEx'/>
<fun r='_ZN6webrtc10VideoFrame7Builder12set_rotationENS_13VideoRotationE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_color_spaceERKNSt3__18optionalINS_10ColorSpaceEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_color_spaceEPKNS_10ColorSpaceE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder6set_idEt'/>
<fun r='_ZN6webrtc10VideoFrame7Builder15set_update_rectERKNSt3__18optionalINS0_10UpdateRectEEE'/>
<fun r='_ZN6webrtc10VideoFrame7Builder16set_packet_infosENS_14RtpPacketInfosE'/>
<mbr r='webrtc::VideoFrame::Builder::id_' o='0' t='uint16_t'/>
<mbr r='webrtc::VideoFrame::Builder::video_frame_buffer_' o='64' t='rtc::scoped_refptr&lt;webrtc::VideoFrameBuffer&gt;'/>
<mbr r='webrtc::VideoFrame::Builder::timestamp_us_' o='128' t='int64_t'/>
<mbr r='webrtc::VideoFrame::Builder::timestamp_rtp_' o='192' t='uint32_t'/>
<mbr r='webrtc::VideoFrame::Builder::ntp_time_ms_' o='256' t='int64_t'/>
<mbr r='webrtc::VideoFrame::Builder::rotation_' o='320' t='webrtc::VideoRotation'/>
<mbr r='webrtc::VideoFrame::Builder::color_space_' o='352' t='absl::optional&lt;ColorSpace&gt;'/>
<mbr r='webrtc::VideoFrame::Builder::update_rect_' o='928' t='absl::optional&lt;UpdateRect&gt;'/>
<mbr r='webrtc::VideoFrame::Builder::packet_infos_' o='1088' t='webrtc::RtpPacketInfos'/>
