<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='56' u='w' c='_ZN6webrtc17ProcessThreadImpl14ModuleCallbackC1EPNS_6ModuleERKN3rtc8LocationE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='58' u='r' c='_ZNK6webrtc17ProcessThreadImpl14ModuleCallbackeqERKS1_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='58' u='r' c='_ZNK6webrtc17ProcessThreadImpl14ModuleCallbackeqERKS1_'/>
<dec f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='61' type='webrtc::Module *const'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='81' u='r' c='_ZN6webrtc17ProcessThreadImpl5StartEv'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='116' u='r' c='_ZN6webrtc17ProcessThreadImpl11StopNoLocksEv'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='147' u='r' c='_ZN6webrtc17ProcessThreadImpl14WakeUpInternalEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='191' u='r' c='_ZN6webrtc17ProcessThreadImpl14RegisterModuleEPNS_6ModuleERKN3rtc8LocationE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='224' u='r' c='_ZN6webrtc17ProcessThreadImpl16DeRegisterModuleEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='246' u='r' c='_ZN6webrtc17ProcessThreadImpl7ProcessEv'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='256' u='r' c='_ZN6webrtc17ProcessThreadImpl7ProcessEv'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='262' u='r' c='_ZN6webrtc17ProcessThreadImpl7ProcessEv'/>
<offset>0</offset>
