<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/x509_vfy.h' l='124' type='int (*)(X509_LOOKUP *)'/>
<offset>192</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/x509/x509_lu.c' l='101' u='r' c='X509_LOOKUP_init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/x509/x509_lu.c' l='102' u='r' c='X509_LOOKUP_init'/>
