<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/listfmt.h' l='39' type='const struct yasm_listfmt_module *'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='570' macro='1' u='r' c='do_assemble'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='791' macro='1' u='r' c='cleanup'/>
<offset>0</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/listfmt.h' l='38'>/** #yasm_listfmt_module implementation for this list format. */</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/listfmts/nasm/nasm-listfmt.c' l='70' u='w' c='nasm_listfmt_create'/>
