<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/preproc.h' l='39' type='const struct yasm_preproc_module *'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='310' macro='1' u='r' c='do_preproc_only'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='323' macro='1' u='r' c='do_preproc_only'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='793' macro='1' u='r' c='cleanup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='1224' macro='1' u='r' c='apply_preproc_builtins'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='1244' macro='1' u='r' c='apply_preproc_standard_macros'/>
<offset>0</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/preproc.h' l='38'>/** #yasm_preproc_module implementation for this preprocessor. */</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/gas-token.c' l='64' macro='1' u='r' c='preproc_input'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/parsers/gas/gas-parser.c' l='79' u='r' c='gas_parser_do_parse'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/parsers/gas/gas-parser.c' l='81' u='r' c='gas_parser_do_parse'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/parsers/nasm/nasm-parse.c' l='219' macro='1' u='r' c='nasm_parser_parse'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/preprocs/gas/gas-preproc.c' l='1244' u='w' c='gas_preproc_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/preprocs/nasm/nasm-preproc.c' l='140' u='w' c='nasm_preproc_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/preprocs/raw/raw-preproc.c' l='59' u='w' c='raw_preproc_create'/>
