<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.h' l='50' type='opus_int32'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.c' l='221' u='w' c='tonality_analysis_init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.c' l='254' u='r' c='tonality_get_info'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.c' l='264' u='r' c='tonality_get_info'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.c' l='504' u='r' c='tonality_analysis'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.c' l='509' u='r' c='tonality_analysis'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.c' l='517' u='r' c='tonality_analysis'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.c' l='548' u='r' c='tonality_analysis'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/analysis.c' l='825' u='r' c='tonality_analysis'/>
<offset>64</offset>
