<dec f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/structs.h' l='153' type='int16_t'/>
<offset>12912</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode.c' l='124' u='r' c='WebRtcIsacfix_DecodeImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='406' u='w' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='415' u='w' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='422' u='a' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='430' u='a' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='443' u='r' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='463' u='r' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='671' u='r' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='673' u='r' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/decode_plc.c' l='673' u='r' c='WebRtcIsacfix_DecodePlcImpl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/codecs/isac/fix/source/initialize.c' l='167' u='w' c='WebRtcIsacfix_InitPlc'/>
