<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='175' type='uint8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='398' u='r' c='_ZN5angle8B8G8R8A89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='406' u='r' c='_ZN5angle8B8G8R8A89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='414' u='w' c='_ZN5angle8B8G8R8A810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='422' u='w' c='_ZN5angle8B8G8R8A810writeColorEPS0_PKNS_5ColorIfEE'/>
