<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='88' type='uint8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='164' u='r' c='_ZN5angle6R8G8B89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='165' u='r' c='_ZN5angle6R8G8B89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='172' u='r' c='_ZN5angle6R8G8B89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='180' u='w' c='_ZN5angle6R8G8B810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='187' u='w' c='_ZN5angle6R8G8B810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='194' u='w' c='_ZN5angle6R8G8B87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='194' u='r' c='_ZN5angle6R8G8B87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='194' u='r' c='_ZN5angle6R8G8B87averageEPS0_PKS0_S3_'/>
