<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='188' type='uint8_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='437' u='r' c='_ZN5angle8B8G8R8X89readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='445' u='r' c='_ZN5angle8B8G8R8X89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='453' u='w' c='_ZN5angle8B8G8R8X810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='461' u='w' c='_ZN5angle8B8G8R8X810writeColorEPS0_PKNS_5ColorIfEE'/>
