<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='384' type='int8_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='974' u='r' c='_ZN5angle9R8G8B8A8S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='982' u='r' c='_ZN5angle9R8G8B8A8S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='990' u='w' c='_ZN5angle9R8G8B8A8S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='998' u='w' c='_ZN5angle9R8G8B8A8S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1006' u='w' c='_ZN5angle9R8G8B8A8S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1006' u='r' c='_ZN5angle9R8G8B8A8S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1006' u='r' c='_ZN5angle9R8G8B8A8S7averageEPS0_PKS0_S3_'/>
