<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='434' type='int16_t'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1116' u='r' c='_ZN5angle13R16G16B16A16S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1124' u='r' c='_ZN5angle13R16G16B16A16S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1132' u='w' c='_ZN5angle13R16G16B16A16S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1140' u='w' c='_ZN5angle13R16G16B16A16S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1150' u='w' c='_ZN5angle13R16G16B16A16S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1150' u='r' c='_ZN5angle13R16G16B16A16S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1150' u='r' c='_ZN5angle13R16G16B16A16S7averageEPS0_PKS0_S3_'/>
