<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='100' type='uint8_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='210' u='r' c='_ZN5angle6B8G8R89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='218' u='w' c='_ZN5angle6B8G8R810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='225' u='w' c='_ZN5angle6B8G8R810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='232' u='w' c='_ZN5angle6B8G8R87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='232' u='r' c='_ZN5angle6B8G8R87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='232' u='r' c='_ZN5angle6B8G8R87averageEPS0_PKS0_S3_'/>
