<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='538' type='uint16_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1388' u='r' c='_ZN5angle4L16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1397' u='w' c='_ZN5angle4L16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1402' u='w' c='_ZN5angle4L16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1402' u='r' c='_ZN5angle4L16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1402' u='r' c='_ZN5angle4L16F7averageEPS0_PKS0_S3_'/>
