<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='753' type='uint8_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1854' u='r' c='_ZN5angle2S816ReadDepthStencilEPNS_12DepthStencilEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1859' u='w' c='_ZN5angle2S817WriteDepthStencilEPS0_PKNS_12DepthStencilE'/>
