<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='420' type='int16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1078' u='r' c='_ZN5angle10R16G16B16S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1086' u='r' c='_ZN5angle10R16G16B16S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1094' u='w' c='_ZN5angle10R16G16B16S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1101' u='w' c='_ZN5angle10R16G16B16S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1108' u='w' c='_ZN5angle10R16G16B16S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1108' u='r' c='_ZN5angle10R16G16B16S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1108' u='r' c='_ZN5angle10R16G16B16S7averageEPS0_PKS0_S3_'/>
