<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='691' type='uint32_t'/>
<offset>10</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1719' u='r' c='_ZN5angle11R10G10B10X29readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1727' u='r' c='_ZN5angle11R10G10B10X29readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1735' u='w' c='_ZN5angle11R10G10B10X210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1742' u='w' c='_ZN5angle11R10G10B10X210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1749' u='w' c='_ZN5angle11R10G10B10X27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1749' u='r' c='_ZN5angle11R10G10B10X27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1749' u='r' c='_ZN5angle11R10G10B10X27averageEPS0_PKS0_S3_'/>
