<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='283' type='uint16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='689' u='r' c='_ZN5angle12R16G16B16A169readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='697' u='r' c='_ZN5angle12R16G16B16A169readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='705' u='w' c='_ZN5angle12R16G16B16A1610writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='713' u='w' c='_ZN5angle12R16G16B16A1610writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='721' u='w' c='_ZN5angle12R16G16B16A167averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='721' u='r' c='_ZN5angle12R16G16B16A167averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='721' u='r' c='_ZN5angle12R16G16B16A167averageEPS0_PKS0_S3_'/>
