<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='705' type='uint32_t'/>
<offset>10</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1756' u='r' c='_ZN5angle11B10G10R10A29readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1764' u='r' c='_ZN5angle11B10G10R10A29readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1772' u='w' c='_ZN5angle11B10G10R10A210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1780' u='w' c='_ZN5angle11B10G10R10A210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1788' u='w' c='_ZN5angle11B10G10R10A27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1788' u='r' c='_ZN5angle11B10G10R10A27averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1788' u='r' c='_ZN5angle11B10G10R10A27averageEPS0_PKS0_S3_'/>
