<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='433' type='int16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1115' u='r' c='_ZN5angle13R16G16B16A16S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1123' u='r' c='_ZN5angle13R16G16B16A16S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1131' u='w' c='_ZN5angle13R16G16B16A16S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1139' u='w' c='_ZN5angle13R16G16B16A16S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1149' u='w' c='_ZN5angle13R16G16B16A16S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1149' u='r' c='_ZN5angle13R16G16B16A16S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1149' u='r' c='_ZN5angle13R16G16B16A16S7averageEPS0_PKS0_S3_'/>
