<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='640' type='float'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1597' u='r' c='_ZN5angle7R32G32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1605' u='w' c='_ZN5angle7R32G32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1611' u='w' c='_ZN5angle7R32G32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1611' u='r' c='_ZN5angle7R32G32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1611' u='r' c='_ZN5angle7R32G32F7averageEPS0_PKS0_S3_'/>
