<use f='webkit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='110'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='111'/>
<def f='webkit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='113' ll='141'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='115' c='_ZN5angle7FeatureC1ERKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='143' c='_ZN5angle7FeatureC1ERKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='26'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='34'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='42'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='48'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='54'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='60'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='65'/>
<size>48</size>
<fun r='_ZN5angle7FeatureC1ERKS0_'/>
<fun r='_ZN5angle7FeatureC1EPKcRKNS_15FeatureCategoryES2_PNSt3__13mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEPS0_NS6_4lessISD_EENSB_INS62769771'/>
<fun r='_ZN5angle7FeatureD1Ev'/>
<mbr r='angle::Feature::name' o='0' t='const char *const'/>
<mbr r='angle::Feature::category' o='64' t='const angle::FeatureCategory'/>
<mbr r='angle::Feature::description' o='128' t='const char *const'/>
<mbr r='angle::Feature::bug' o='192' t='const char *const'/>
<mbr r='angle::Feature::enabled' o='256' t='bool'/>
<mbr r='angle::Feature::condition' o='320' t='const char *'/>
<fun r='_ZN5angle7FeatureC1ERKS0_'/>
<fun r='_ZN5angle7FeatureC1EPKcRKNS_15FeatureCategoryES2_PNSt3__13mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEPS0_NS6_4lessISD_EENSB_INS62769771'/>
<fun r='_ZN5angle7FeatureD1Ev'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='29'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='36'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='44'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='56'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='64'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='71'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='79'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='86'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='92'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='99'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='106'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='112'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='128'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='134'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='142'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='150'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='155'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='162'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='168'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='176'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='185'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='192'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='199'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='207'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='214'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='221'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='229'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='239'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='246'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='254'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='262'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='268'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='275'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='283'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='293'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='301'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='307'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='315'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='322'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='330'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='337'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='343'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='349'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='355'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='361'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='367'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='374'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='380'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='390'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='398'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='408'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='416'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='425'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='431'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='436'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='441'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='447'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='452'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='457'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='463'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='468'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='474'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='481'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='490'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='498'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='504'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesGL.h' l='511'/>
<size>48</size>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='20'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='25'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='30'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='34'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='38'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='43'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='48'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='51'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='55'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='59'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='62'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='68'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='74'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='78'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='82'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='85'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='89'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='93'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='97'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='100'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='103'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='109'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='115'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='119'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='124'/>
<use f='webkit/Source/ThirdParty/ANGLE/include/platform/FeaturesMtl.h' l='129'/>
<size>48</size>
