<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='358' type='int8_t'/>
<offset>8</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='902' u='r' c='_ZN5angle5R8G8S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='910' u='r' c='_ZN5angle5R8G8S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='918' u='w' c='_ZN5angle5R8G8S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='924' u='w' c='_ZN5angle5R8G8S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='930' u='w' c='_ZN5angle5R8G8S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='930' u='r' c='_ZN5angle5R8G8S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='930' u='r' c='_ZN5angle5R8G8S7averageEPS0_PKS0_S3_'/>
