<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='569' type='uint16_t'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1450' u='r' c='_ZN5angle10R16G16B16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1458' u='w' c='_ZN5angle10R16G16B16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1465' u='w' c='_ZN5angle10R16G16B16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1465' u='r' c='_ZN5angle10R16G16B16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1465' u='r' c='_ZN5angle10R16G16B16F7averageEPS0_PKS0_S3_'/>
