<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='558' type='uint16_t'/>
<offset>16</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1429' u='r' c='_ZN5angle7R16G16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1437' u='w' c='_ZN5angle7R16G16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1443' u='w' c='_ZN5angle7R16G16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1443' u='r' c='_ZN5angle7R16G16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1443' u='r' c='_ZN5angle7R16G16F7averageEPS0_PKS0_S3_'/>
