<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='191' type='uint8_t'/>
<offset>24</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='454' u='w' c='_ZN5angle8B8G8R8X810writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='462' u='w' c='_ZN5angle8B8G8R8X810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='469' u='w' c='_ZN5angle8B8G8R8X87averageEPS0_PKS0_S3_'/>
