<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='26' type='uint8_t'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='19' u='r' c='_ZN5angle2L89readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='28' u='w' c='_ZN5angle2L810writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='33' u='w' c='_ZN5angle2L87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='33' u='r' c='_ZN5angle2L87averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='33' u='r' c='_ZN5angle2L87averageEPS0_PKS0_S3_'/>
