<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='334' type='uint32_t'/>
<offset>64</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='832' u='r' c='_ZN5angle12R32G32B32A329readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='840' u='r' c='_ZN5angle12R32G32B32A329readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='848' u='w' c='_ZN5angle12R32G32B32A3210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='856' u='w' c='_ZN5angle12R32G32B32A3210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='864' u='w' c='_ZN5angle12R32G32B32A327averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='864' u='r' c='_ZN5angle12R32G32B32A327averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='864' u='r' c='_ZN5angle12R32G32B32A327averageEPS0_PKS0_S3_'/>
