<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='581' type='float'/>
<offset>96</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1472' u='r' c='_ZN5angle13A32B32G32R32F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1480' u='w' c='_ZN5angle13A32B32G32R32F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1490' u='w' c='_ZN5angle13A32B32G32R32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1490' u='r' c='_ZN5angle13A32B32G32R32F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1490' u='r' c='_ZN5angle13A32B32G32R32F7averageEPS0_PKS0_S3_'/>
