<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='676' type='int32_t'/>
<offset>10</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1679' u='r' c='_ZN5angle12R10G10B10A2S9readColorEPNS_5ColorIiEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1687' u='r' c='_ZN5angle12R10G10B10A2S9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1695' u='w' c='_ZN5angle12R10G10B10A2S10writeColorEPS0_PKNS_5ColorIiEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1703' u='w' c='_ZN5angle12R10G10B10A2S10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1711' u='w' c='_ZN5angle12R10G10B10A2S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1711' u='r' c='_ZN5angle12R10G10B10A2S7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1711' u='r' c='_ZN5angle12R10G10B10A2S7averageEPS0_PKS0_S3_'/>
