<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='321' type='uint32_t'/>
<offset>64</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='795' u='r' c='_ZN5angle9R32G32B329readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='803' u='r' c='_ZN5angle9R32G32B329readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='811' u='w' c='_ZN5angle9R32G32B3210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='818' u='w' c='_ZN5angle9R32G32B3210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='825' u='w' c='_ZN5angle9R32G32B327averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='825' u='r' c='_ZN5angle9R32G32B327averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='825' u='r' c='_ZN5angle9R32G32B327averageEPS0_PKS0_S3_'/>
