<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='499' type='uint16_t'/>
<offset>48</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1302' u='r' c='_ZN5angle13A16B16G16R16F9readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1310' u='w' c='_ZN5angle13A16B16G16R16F10writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1320' u='w' c='_ZN5angle13A16B16G16R16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1320' u='r' c='_ZN5angle13A16B16G16R16F7averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='1320' u='r' c='_ZN5angle13A16B16G16R16F7averageEPS0_PKS0_S3_'/>
