<dec f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.h' l='308' type='uint32_t'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='760' u='r' c='_ZN5angle6R32G329readColorEPNS_5ColorIjEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='768' u='r' c='_ZN5angle6R32G329readColorEPNS_5ColorIfEEPKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='776' u='w' c='_ZN5angle6R32G3210writeColorEPS0_PKNS_5ColorIjEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='782' u='w' c='_ZN5angle6R32G3210writeColorEPS0_PKNS_5ColorIfEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='788' u='w' c='_ZN5angle6R32G327averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='788' u='r' c='_ZN5angle6R32G327averageEPS0_PKS0_S3_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/image_util/imageformats.cpp' l='788' u='r' c='_ZN5angle6R32G327averageEPS0_PKS0_S3_'/>
