<dec f='webkit/WebKitBuild/Debug/usr/local/include/bmalloc/IsoAllocator.h' l='35' type='0'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/bmalloc/IsoHeapImpl.h' l='95'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/bmalloc/IsoHeapImplInlines.h' l='295' c='_ZN7bmalloc11IsoHeapImpl20updateAllocationModeEv'/>
<dec f='webkit/Source/bmalloc/bmalloc/IsoAllocator.h' l='35' type='0'/>
<use f='webkit/Source/bmalloc/bmalloc/IsoHeapImpl.h' l='95'/>
<use f='webkit/Source/bmalloc/bmalloc/IsoHeapImplInlines.h' l='295' c='_ZN7bmalloc11IsoHeapImpl20updateAllocationModeEv'/>
