<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/dsa.h' l='415' type='BIGNUM *'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='118' u='r' c='DSA_free'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='139' u='r' c='DSA_get0_q'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='159' u='r' c='DSA_get0_pqg'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='185' u='r' c='DSA_set0_pqg'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='195' u='r' c='DSA_set0_pqg'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='196' u='w' c='DSA_set0_pqg'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='437' u='r' c='DSA_generate_parameters_ex'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='440' u='w' c='DSA_generate_parameters_ex'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='442' u='r' c='DSA_generate_parameters_ex'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='470' u='w' c='DSAparams_dup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='470' u='r' c='DSAparams_dup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='472' u='r' c='DSAparams_dup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='497' u='r' c='DSA_generate_key'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='596' u='r' c='DSA_do_sign'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='600' u='r' c='DSA_do_sign'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='611' u='r' c='DSA_do_sign'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='616' u='r' c='DSA_do_sign'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='622' u='r' c='DSA_do_sign'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='680' u='r' c='DSA_do_check_signature'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='685' u='r' c='DSA_do_check_signature'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='692' u='r' c='DSA_do_check_signature'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='697' u='r' c='DSA_do_check_signature'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='710' u='r' c='DSA_do_check_signature'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='715' u='r' c='DSA_do_check_signature'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='732' u='r' c='DSA_do_check_signature'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='824' u='r' c='DSA_size'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='846' u='r' c='dsa_sign_setup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='858' u='r' c='dsa_sign_setup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='863' u='r' c='dsa_sign_setup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='875' u='r' c='dsa_sign_setup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='878' u='r' c='dsa_sign_setup'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='927' u='r' c='DSA_dup_DH'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='928' u='r' c='DSA_dup_DH'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa.c' l='929' u='r' c='DSA_dup_DH'/>
<offset>128</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/dsa.h' l='415'>// == 20</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='74' u='r' c='dsa_check_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='81' u='r' c='dsa_check_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='87' u='r' c='dsa_check_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='159' u='a' c='DSA_parse_public_key'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='180' u='r' c='DSA_marshal_public_key'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='197' u='a' c='DSA_parse_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='217' u='r' c='DSA_marshal_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='246' u='a' c='DSA_parse_private_key'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/dsa/dsa_asn1.c' l='269' u='r' c='DSA_marshal_private_key'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/p_dsa_asn1.c' l='106' u='r' c='dsa_pub_encode'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/p_dsa_asn1.c' l='150' u='r' c='dsa_priv_decode'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/p_dsa_asn1.c' l='209' u='r' c='dsa_missing_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/p_dsa_asn1.c' l='230' u='a' c='dsa_copy_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/p_dsa_asn1.c' l='230' u='r' c='dsa_copy_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/p_dsa_asn1.c' l='240' u='r' c='dsa_cmp_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/p_dsa_asn1.c' l='240' u='r' c='dsa_cmp_parameters'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/print.c' l='243' u='r' c='do_dsa_print'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/evp/print.c' l='264' u='r' c='do_dsa_print'/>
