<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/encoder/vp9_encodemb.h' l='25' type='ENTROPY_CONTEXT *'/>
<offset>192</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/encoder/vp9_encodemb.c' l='600' u='r' c='encode_block'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/encoder/vp9_encodemb.c' l='800' u='w' c='vp9_encode_sb'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/encoder/vp9_encodemb.c' l='837' u='r' c='vp9_encode_block_intra'/>
