<dec f='webkit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.h' l='365' type='3'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/PackedEnums.h' l='201'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='1400' u='r' c='_ZN2gl10FromGLenumEj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='1416' c='_ZN2gl8ToGLenumENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='1437' c='_ZN2gllsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/common/utilities.cpp' l='1091' c='_ZN2gl15GetPipelineTypeENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorVulkan.cpp' l='173' u='r'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.h' l='124' u='r' c='_ZN2gl17ProgramExecutable21setLinkedShaderStagesENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.h' l='126' u='r' c='_ZN2gl17ProgramExecutable21setLinkedShaderStagesENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.h' l='138' u='r' c='_ZNK2gl17ProgramExecutable20hasLinkedShaderStageENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='339' u='r' c='_ZNK2gl12ProgramState9isComputeEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Caps.cpp' l='1286' u='r' c='_ZN2gl19GenerateMinimumCapsERKNS_7VersionERKNS_10ExtensionsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Caps.cpp' l='1287' u='r' c='_ZN2gl19GenerateMinimumCapsERKNS_7VersionERKNS_10ExtensionsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Caps.cpp' l='1289' u='r' c='_ZN2gl19GenerateMinimumCapsERKNS_7VersionERKNS_10ExtensionsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Caps.cpp' l='1290' u='r' c='_ZN2gl19GenerateMinimumCapsERKNS_7VersionERKNS_10ExtensionsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Caps.cpp' l='1291' u='r' c='_ZN2gl19GenerateMinimumCapsERKNS_7VersionERKNS_10ExtensionsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Caps.cpp' l='1292' u='r' c='_ZN2gl19GenerateMinimumCapsERKNS_7VersionERKNS_10ExtensionsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Caps.cpp' l='1293' u='r' c='_ZN2gl19GenerateMinimumCapsERKNS_7VersionERKNS_10ExtensionsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Compiler.cpp' l='164' u='r' c='_ZN2gl8CompilerC1EPN2rx13GLImplFactoryERKNS_5StateEPN3egl7DisplayE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Compiler.cpp' l='175' u='r' c='_ZN2gl8CompilerC1EPN2rx13GLImplFactoryERKNS_5StateEPN3egl7DisplayE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Compiler.cpp' l='176' u='r' c='_ZN2gl8CompilerC1EPN2rx13GLImplFactoryERKNS_5StateEPN3egl7DisplayE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Compiler.cpp' l='178' u='r' c='_ZN2gl8CompilerC1EPN2rx13GLImplFactoryERKNS_5StateEPN3egl7DisplayE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Compiler.cpp' l='180' u='r' c='_ZN2gl8CompilerC1EPN2rx13GLImplFactoryERKNS_5StateEPN3egl7DisplayE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='1703' u='r' c='_ZNK2gl7Context15getIntegervImplEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='1706' u='r' c='_ZNK2gl7Context15getIntegervImplEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='1712' u='r' c='_ZNK2gl7Context15getIntegervImplEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='1715' u='r' c='_ZNK2gl7Context15getIntegervImplEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='1718' u='r' c='_ZNK2gl7Context15getIntegervImplEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='1721' u='r' c='_ZNK2gl7Context15getIntegervImplEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='1725' u='r' c='_ZNK2gl7Context15getIntegervImplEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='1728' u='r' c='_ZNK2gl7Context15getIntegervImplEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='3455' u='r' c='_ZN2gl7Context8initCapsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp' l='3455' u='r' c='_ZN2gl7Context8initCapsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='623' u='r' c='_ZN2gl12_GLOBAL__N_128ValidateInterfaceBlocksMatchEjRKN5angle13PackedEnumMapINS_10ShaderTypeEPKNSt3__16vectorIN2sh14InterfaceBlockENS4_9allocatorIS7_E11748219'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1218' u='r' c='_ZNK2gl12ProgramState30getLastAttachedShaderStageTypeEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1220' u='r' c='_ZNK2gl12ProgramState30getLastAttachedShaderStageTypeEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1464' u='r' c='_ZN2gl7Program8linkImplEPKNS_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1688' u='r' c='_ZN2gl7Program24updateLinkedShaderStagesEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1744' u='r' c='_ZN2gl12ProgramState28updateProgramInterfaceInputsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='1790' u='r' c='_ZN2gl12ProgramState29updateProgramInterfaceOutputsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3255' u='r' c='_ZN2gl7Program19linkValidateShadersERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3277' u='r' c='_ZN2gl7Program19linkValidateShadersERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='3706' u='r' c='_ZN2gl7Program27linkSamplerAndImageBindingsEPj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='4405' u='r' c='_ZNK2gl7Program17getMergedVaryingsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Program.cpp' l='5560' u='r' c='_ZN2gl7Program11deserializeEPKNS_7ContextERNS_17BinaryInputStreamERNS_7InfoLogE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.cpp' l='329' u='r' c='_ZN2gl17ProgramExecutable18updateActiveImagesERKS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.cpp' l='132' c='_ZN2gl12_GLOBAL__N_130GetMaximumShaderUniformVectorsENS_10ShaderTypeERKNS_4CapsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.cpp' l='683' u='r' c='_ZN2gl13UniformLinker4linkERKNS_4CapsERNS_7InfoLogERKNS_22ProgramAliasedBindingsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramPipeline.cpp' l='125' u='r' c='_ZN2gl20ProgramPipelineState16useProgramStagesEPKNS_7ContextEjPNS_7ProgramEPNSt3__16vectorIN5angle15ObserverBindingENS6_9allocatorIS9_EEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramPipeline.cpp' l='127' u='r' c='_ZN2gl20ProgramPipelineState16useProgramStagesEPKNS_7ContextEjPNS_7ProgramEPNSt3__16vectorIN5angle15ObserverBindingENS6_9allocatorIS9_EEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramPipeline.cpp' l='295' u='r' c='_ZN2gl15ProgramPipeline25updateShaderStorageBlocksEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramPipeline.cpp' l='329' u='r' c='_ZN2gl15ProgramPipeline19updateImageBindingsEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramPipeline.cpp' l='376' u='r' c='_ZN2gl15ProgramPipeline17updateHasBooleansEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Shader.cpp' l='89' c='_ZN2gl19GetShaderTypeStringENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Shader.cpp' l='438' c='_ZN2gl6Shader14resolveCompileEv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='731' u='r' c='_ZN2gl12_GLOBAL__N_124GetInputResourcePropertyEPKNS_7ProgramEjj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='774' u='r' c='_ZN2gl12_GLOBAL__N_125GetOutputResourcePropertyEPKNS_7ProgramEjj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='1000' u='r' c='_ZN2gl12_GLOBAL__N_139GetShaderVariableBufferResourcePropertyERKNS_20ShaderVariableBufferEjPiiS4_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='1860' u='r' c='_ZN2gl26GetUniformResourcePropertyEPKNS_7ProgramEjj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='1906' u='r' c='_ZN2gl33GetBufferVariableResourcePropertyEPKNS_7ProgramEjj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='3841' u='r' c='_ZN2gl22QueryProgramPipelineivEPKNS_7ContextEPNS_15ProgramPipelineEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/ProgramGL.cpp' l='231' u='r' c='_ZN2rx9ProgramGL4linkEPKN2gl7ContextERKNS1_22ProgramLinkedResourcesERNS1_7InfoLogERKNSt3__16vectorINS1_17ProgramVaryingRefENSA_9allocatorISC_EEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/ProgramGL.cpp' l='234' u='r' c='_ZN2rx9ProgramGL4linkEPKN2gl7ContextERKNS1_22ProgramLinkedResourcesERNS1_7InfoLogERKNSt3__16vectorINS1_17ProgramVaryingRefENSA_9allocatorISC_EEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/ProgramGL.cpp' l='440' u='r' c='_ZN2rx9ProgramGL4linkEPKN2gl7ContextERKNS1_22ProgramLinkedResourcesERNS1_7InfoLogERKNSt3__16vectorINS1_17ProgramVaryingRefENSA_9allocatorISC_EEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/ProgramGL.cpp' l='443' u='r' c='_ZN2rx9ProgramGL4linkEPKN2gl7ContextERKNS1_22ProgramLinkedResourcesERNS1_7InfoLogERKNSt3__16vectorINS1_17ProgramVaryingRefENSA_9allocatorISC_EEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/ShaderGL.cpp' l='250' u='r' c='_ZN2rx8ShaderGL7compileEPKN2gl7ContextEPNS1_18ShCompilerInstanceEy'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='2000' u='r' c='_ZN2rx14StateManagerGL9syncStateEPKN2gl7ContextERKN5angle14IterableBitSetILm63EEES9_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/renderergl_utils.cpp' l='1039' u='r' c='_ZN2rx11nativegl_gl12GenerateCapsEPKNS_11FunctionsGLERKN5angle10FeaturesGLEPN2gl4CapsEPNS8_14TextureCapsMapEPNS8_10ExtensionsEPNS8_7VersionEPNS_29Mult5829215'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/renderergl_utils.cpp' l='1041' u='r' c='_ZN2rx11nativegl_gl12GenerateCapsEPKNS_11FunctionsGLERKN5angle10FeaturesGLEPN2gl4CapsEPNS8_14TextureCapsMapEPNS8_10ExtensionsEPNS8_7VersionEPNS_29Mult5829215'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/renderergl_utils.cpp' l='1045' u='r' c='_ZN2rx11nativegl_gl12GenerateCapsEPKNS_11FunctionsGLERKN5angle10FeaturesGLEPN2gl4CapsEPNS8_14TextureCapsMapEPNS8_10ExtensionsEPNS8_7VersionEPNS_29Mult5829215'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/renderergl_utils.cpp' l='1047' u='r' c='_ZN2rx11nativegl_gl12GenerateCapsEPKNS_11FunctionsGLERKN5angle10FeaturesGLEPN2gl4CapsEPNS8_14TextureCapsMapEPNS8_10ExtensionsEPNS8_7VersionEPNS_29Mult5829215'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/renderergl_utils.cpp' l='1049' u='r' c='_ZN2rx11nativegl_gl12GenerateCapsEPKNS_11FunctionsGLERKN5angle10FeaturesGLEPN2gl4CapsEPNS8_14TextureCapsMapEPNS8_10ExtensionsEPNS8_7VersionEPNS_29Mult5829215'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/renderergl_utils.cpp' l='1051' u='r' c='_ZN2rx11nativegl_gl12GenerateCapsEPKNS_11FunctionsGLERKN5angle10FeaturesGLEPN2gl4CapsEPNS8_14TextureCapsMapEPNS8_10ExtensionsEPNS8_7VersionEPNS_29Mult5829215'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/renderergl_utils.cpp' l='1053' u='r' c='_ZN2rx11nativegl_gl12GenerateCapsEPKNS_11FunctionsGLERKN5angle10FeaturesGLEPN2gl4CapsEPNS8_14TextureCapsMapEPNS8_10ExtensionsEPNS8_7VersionEPNS_29Mult5829215'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/renderergl_utils.cpp' l='1055' u='r' c='_ZN2rx11nativegl_gl12GenerateCapsEPKNS_11FunctionsGLERKN5angle10FeaturesGLEPN2gl4CapsEPNS8_14TextureCapsMapEPNS8_10ExtensionsEPNS8_7VersionEPNS_29Mult5829215'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/glslang_wrapper_utils.h' l='28' u='r'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ShaderMtl.mm' l='127' u='r' c='_ZN2rx9ShaderMtl7compileEPKN2gl7ContextEPNS1_18ShCompilerInstanceEy'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_state_cache.mm' l='1211' u='r' c='_ZN2rx3mtl35ProvokingVertexComputePipelineCache26createComputePipelineStateEPNS0_7ContextERKNS0_34ProvokingVertexComputePipelineDescE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_state_cache.mm' l='1214' u='r' c='_ZN2rx3mtl35ProvokingVertexComputePipelineCache26createComputePipelineStateEPNS0_7ContextERKNS0_34ProvokingVertexComputePipelineDescE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES.cpp' l='5156' u='r' c='_ZN2gl24ValidateGetProgramivBaseEPKNS_7ContextENS_15ShaderProgramIDEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='3721' c='_ZN2gl20ValidateCreateShaderEPKNS_7ContextENS_10ShaderTypeE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES31.cpp' l='1369' u='r' c='_ZN2gl23ValidateDispatchComputeEPKNS_7ContextEjjj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES31.cpp' l='1406' u='r' c='_ZN2gl31ValidateDispatchComputeIndirectEPKNS_7ContextEl'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES31.cpp' l='1857' u='r' c='_ZN2gl28ValidateCreateShaderProgramvEPKNS_7ContextENS_10ShaderTypeEiPKPKc'/>
