<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='54' u='w' c='_ZN2gl9RectangleC1Ev'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='56' u='w' c='_ZN2gl9RectangleC1Eiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='60' u='r' c='_ZNK2gl9Rectangle2y0Ev'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='62' u='r' c='_ZNK2gl9Rectangle2y1Ev'/>
<dec f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='78' type='int'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.inc' l='15' u='r' c='_ZN2gleqERKNS_9RectangleES2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.inc' l='15' u='r' c='_ZN2gleqERKNS_9RectangleES2_'/>
<offset>32</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/GLES1Renderer.cpp' l='136' u='r' c='_ZN2gl13GLES1Renderer14prepareForDrawENS_13PrimitiveModeEPNS_7ContextEPNS_5StateE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='388' u='w' c='_ZN2gl5State10initializeEPNS_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='415' u='w' c='_ZN2gl5State10initializeEPNS_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='1074' u='r' c='_ZN2gl5State16setScissorParamsEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='1077' u='w' c='_ZN2gl5State16setScissorParamsEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='1448' u='r' c='_ZN2gl5State17setViewportParamsEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='1452' u='w' c='_ZN2gl5State17setViewportParamsEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='2626' u='r' c='_ZNK2gl5State11getIntegervEPKNS_7ContextEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='2632' u='r' c='_ZNK2gl5State11getIntegervEPKNS_7ContextEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1263' u='r' c='_ZN2gl7Texture9copyImageEPNS_7ContextENS_13TextureTargetEiRKNS_9RectangleEjPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1265' u='r' c='_ZN2gl7Texture9copyImageEPNS_7ContextENS_13TextureTargetEiRKNS_9RectangleEjPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1270' u='r' c='_ZN2gl7Texture9copyImageEPNS_7ContextENS_13TextureTargetEiRKNS_9RectangleEjPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1270' u='r' c='_ZN2gl7Texture9copyImageEPNS_7ContextENS_13TextureTargetEiRKNS_9RectangleEjPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1330' u='r' c='_ZN2gl7Texture12copySubImageEPNS_7ContextERKNS_10ImageIndexERKNS_6OffsetERKNS_9RectangleEPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1330' u='r' c='_ZN2gl7Texture12copySubImageEPNS_7ContextERKNS_10ImageIndexERKNS_6OffsetERKNS_9RectangleEPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='579' u='w' c='_ZNK2gl9Rectangle4flipEbb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='579' u='r' c='_ZNK2gl9Rectangle4flipEbb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='603' u='r' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='612' u='r' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='620' u='r' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='629' u='r' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='645' u='w' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='659' u='r' c='_ZN2gl21GetEnclosingRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='661' u='r' c='_ZN2gl21GetEnclosingRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='692' u='w' c='_ZN2gl21GetEnclosingRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='704' u='r' c='_ZN2gl15ExtendRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='706' u='r' c='_ZN2gl15ExtendRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='758' u='w' c='_ZN2gl15ExtendRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/frame_capture_utils.cpp' l='233' u='r' c='_ZN5angle12_GLOBAL__N_118SerializeRectangleEPN2gl18BinaryOutputStreamERKNS1_9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='335' c='_ZN2gl12_GLOBAL__N_121QueryTexParameterBaseEPKNS_7ContextEPKNS_7TextureEjPT1_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='323' u='r' c='_ZN2rx6BlitGL35copySubImageToLUMAWorkaroundTextureEPKN2gl7ContextEjNS1_11TextureTypeENS1_13TextureTargetEjmRKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='493' u='r' c='_ZN2rx6BlitGL25blitColorBufferWithShaderEPKN2gl7ContextEPKNS1_11FramebufferEjRKNS1_9RectangleESA_jb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='498' u='w' c='_ZN2rx6BlitGL25blitColorBufferWithShaderEPKN2gl7ContextEPKNS1_11FramebufferEjRKNS1_9RectangleESA_jb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='498' u='r' c='_ZN2rx6BlitGL25blitColorBufferWithShaderEPKN2gl7ContextEPKNS1_11FramebufferEjRKNS1_9RectangleESA_jb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='510' u='r' c='_ZN2rx6BlitGL25blitColorBufferWithShaderEPKN2gl7ContextEPKNS1_11FramebufferEjRKNS1_9RectangleESA_jb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='634' u='r' c='_ZN2rx6BlitGL14copySubTextureEPKN2gl7ContextEPNS_9TextureGLEmjjNS1_13TextureTargetEmjRKNS1_7ExtentsERKNS1_9RectangleERKNS1_6OffsetEbjbbbPb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='746' u='w' c='_ZN2rx6BlitGL25copySubTextureCPUReadbackEPKN2gl7ContextEPNS_9TextureGLEmjS6_NS1_13TextureTargetEmjjRKNS1_7ExtentsERKNS1_9RectangleERKNS1_6OffsetEbjbbb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='784' u='r' c='_ZN2rx6BlitGL25copySubTextureCPUReadbackEPKN2gl7ContextEPNS_9TextureGLEmjS6_NS1_13TextureTargetEmjjRKNS1_7ExtentsERKNS1_9RectangleERKNS1_6OffsetEbjbbb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='844' u='r' c='_ZN2rx6BlitGL15copyTexSubImageEPKN2gl7ContextEPNS_9TextureGLEmS6_NS1_13TextureTargetEmRKNS1_9RectangleERKNS1_6OffsetEPb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='473' u='r' c='_ZN2rx13FramebufferGL13invalidateSubEPKN2gl7ContextEmPKjRKNS1_9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='660' u='r' c='_ZN2rx13FramebufferGL10readPixelsEPKN2gl7ContextERKNS1_9RectangleEjjRKNS1_14PixelPackStateEPNS1_6BufferEPv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='660' u='r' c='_ZN2rx13FramebufferGL10readPixelsEPKN2gl7ContextERKNS1_9RectangleEjjRKNS1_14PixelPackStateEPNS1_6BufferEPv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='825' u='r' c='_ZN2rx13FramebufferGL4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='826' u='r' c='_ZN2rx13FramebufferGL4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='863' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='911' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='922' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='931' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='959' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='987' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1035' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1046' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1056' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1085' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1125' u='r' c='_ZN2rx13FramebufferGL13clipSrcRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1125' u='r' c='_ZN2rx13FramebufferGL13clipSrcRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1150' u='r' c='_ZN2rx13FramebufferGL13clipSrcRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1155' u='r' c='_ZN2rx13FramebufferGL13clipSrcRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1478' u='r' c='_ZNK2rx13FramebufferGL18readPixelsRowByRowEPKN2gl7ContextERKNS1_9RectangleEjjjRKNS1_14PixelPackStateEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1478' u='r' c='_ZNK2rx13FramebufferGL18readPixelsRowByRowEPKN2gl7ContextERKNS1_9RectangleEjjjRKNS1_14PixelPackStateEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1531' u='r' c='_ZNK2rx13FramebufferGL19readPixelsAllAtOnceEPKN2gl7ContextERKNS1_9RectangleEjjjRKNS1_14PixelPackStateEPhb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1543' u='r' c='_ZNK2rx13FramebufferGL19readPixelsAllAtOnceEPKN2gl7ContextERKNS1_9RectangleEjjjRKNS1_14PixelPackStateEPhb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='1030' u='r' c='_ZN2rx14StateManagerGL10setScissorERKN2gl9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='1041' u='r' c='_ZN2rx14StateManagerGL11setViewportERKN2gl9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='651' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='653' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='713' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='713' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='751' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='759' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='797' u='r' c='_ZN2rx9TextureGL12copySubImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='797' u='r' c='_ZN2rx9TextureGL12copySubImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='831' u='r' c='_ZN2rx9TextureGL12copySubImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='840' u='r' c='_ZN2rx9TextureGL12copySubImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ContextMtl.mm' l='1867' u='w' c='_ZN2rx10ContextMtl13updateScissorERKN2gl5StateE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ContextMtl.mm' l='1867' u='r' c='_ZN2rx10ContextMtl13updateScissorERKN2gl5StateE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ContextMtl.mm' l='2316' u='r' c='_ZN2rx10ContextMtl25handleDirtyDriverUniformsEPKN2gl7ContextEij'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='241' u='r' c='_ZN2rx14FramebufferMtl10readPixelsEPKN2gl7ContextERKNS1_9RectangleEjjRKNS1_14PixelPackStateEPNS1_6BufferEPv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='241' u='r' c='_ZN2rx14FramebufferMtl10readPixelsEPKN2gl7ContextERKNS1_9RectangleEjjRKNS1_14PixelPackStateEPNS1_6BufferEPv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='329' u='r' c='_ZN2rx14FramebufferMtl4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='329' u='r' c='_ZN2rx14FramebufferMtl4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='346' u='w' c='_ZN2rx14FramebufferMtl4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='351' u='r' c='_ZN2rx14FramebufferMtl4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='913' u='r' c='_ZN2rx14FramebufferMtl30getReadableViewForRenderTargetEPKN2gl7ContextERKNS_15RenderTargetMtlERKNS1_9RectangleEPNSt3__110shared_ptrINS_3mtl7TextureEEESG_PjSH_PS8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1322' u='w' c='_ZNK2rx14FramebufferMtl25getCorrectFlippedReadAreaEPKN2gl7ContextERKNS1_9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1324' u='r' c='_ZNK2rx14FramebufferMtl25getCorrectFlippedReadAreaEPKN2gl7ContextERKNS1_9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1373' u='r' c='_ZNK2rx14FramebufferMtl14readPixelsImplEPKN2gl7ContextERKNS1_9RectangleERKNS_16PackPixelsParamsEPKNS_15RenderTargetMtlEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1376' u='r' c='_ZNK2rx14FramebufferMtl14readPixelsImplEPKN2gl7ContextERKNS1_9RectangleERKNS_16PackPixelsParamsEPKNS_15RenderTargetMtlEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1384' u='w' c='_ZNK2rx14FramebufferMtl14readPixelsImplEPKN2gl7ContextERKNS1_9RectangleERKNS_16PackPixelsParamsEPKNS_15RenderTargetMtlEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1385' u='w' c='_ZNK2rx14FramebufferMtl14readPixelsImplEPKN2gl7ContextERKNS1_9RectangleERKNS_16PackPixelsParamsEPKNS_15RenderTargetMtlEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1385' u='r' c='_ZNK2rx14FramebufferMtl14readPixelsImplEPKN2gl7ContextERKNS1_9RectangleERKNS_16PackPixelsParamsEPKNS_15RenderTargetMtlEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1503' u='r' c='_ZNK2rx14FramebufferMtl18readPixelsToBufferEPKN2gl7ContextERKNS1_9RectangleEPKNS_15RenderTargetMtlEbRKN5angle6FormatEjjPKNSt3__110shared_ptrINS_3mtl6BufferEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1512' u='w' c='_ZNK2rx14FramebufferMtl18readPixelsToBufferEPKN2gl7ContextERKNS1_9RectangleEPKNS_15RenderTargetMtlEbRKN5angle6FormatEjjPKNSt3__110shared_ptrINS_3mtl6BufferEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/TextureMtl.mm' l='2105' u='r' c='_ZN2rx10TextureMtl16copySubImageImplEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleERKNS1_14InternalFormatEPKNS_14FramebufferMtlEPKNS_15RenderTargetMtlE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/TextureMtl.mm' l='2105' u='r' c='_ZN2rx10TextureMtl16copySubImageImplEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleERKNS1_14InternalFormatEPKNS_14FramebufferMtlEPKNS_15RenderTargetMtlE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/TextureMtl.mm' l='2198' u='w' c='_ZN2rx10TextureMtl15copySubImageCPUEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleERKNS1_14InternalFormatEPKNS_14FramebufferMtlEPKNS_15RenderTargetMtlE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/TextureMtl.mm' l='2198' u='r' c='_ZN2rx10TextureMtl15copySubImageCPUEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleERKNS1_14InternalFormatEPKNS_14FramebufferMtlEPKNS_15RenderTargetMtlE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_render_utils.mm' l='2784' u='r' c='_ZN2rx3mtl15CopyPixelsUtils29packPixelsFromTextureToBufferEPNS_10ContextMtlERKN5angle6FormatERKNS0_24CopyPixelsToBufferParamsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='374' u='r' c='_ZN2rx3mtl24ReadTexturePerSliceBytesEPKN2gl7ContextERKNSt3__110shared_ptrINS0_7TextureEEEmRKNS1_9RectangleERKNS1_17LevelIndexWrapperIjEEjPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='408' u='r' c='_ZN2rx3mtl32ReadTexturePerSliceBytesToBufferEPKN2gl7ContextERKNSt3__110shared_ptrINS0_7TextureEEEmRKNS1_9RectangleERKNS1_17LevelIndexWrapperIjEEjjRKNS6_INS0_6BufferEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='423' u='r' c='_ZN2rx3mtl11GetViewportERKN2gl9RectangleEdd'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='468' u='r' c='_ZN2rx3mtl14GetScissorRectERKN2gl9RectangleEmb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='224' u='w' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='224' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='224' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='230' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='231' u='w' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='238' u='w' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='238' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='238' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='244' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='245' u='w' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='899' u='w' c='_ZN2rx17ClipRectToScissorERKN2gl5StateERKNS0_9RectangleEb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='899' u='r' c='_ZN2rx17ClipRectToScissorERKN2gl5StateERKNS0_9RectangleEb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='63' u='r' c='_ZN2gl12_GLOBAL__N_113IsPartialBlitEPKNS_7ContextEPKNS_21FramebufferAttachmentES6_iiiiiiii'/>
