<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='54' u='w' c='_ZN2gl9RectangleC1Ev'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='56' u='w' c='_ZN2gl9RectangleC1Eiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='59' u='r' c='_ZNK2gl9Rectangle2x0Ev'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='61' u='r' c='_ZNK2gl9Rectangle2x1Ev'/>
<dec f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.h' l='77' type='int'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.inc' l='14' u='r' c='_ZN2gleqERKNS_9RectangleES2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.inc' l='14' u='r' c='_ZN2gleqERKNS_9RectangleES2_'/>
<offset>0</offset>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/GLES1Renderer.cpp' l='135' u='r' c='_ZN2gl13GLES1Renderer14prepareForDrawENS_13PrimitiveModeEPNS_7ContextEPNS_5StateE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='387' u='w' c='_ZN2gl5State10initializeEPNS_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='414' u='w' c='_ZN2gl5State10initializeEPNS_7ContextE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='1074' u='r' c='_ZN2gl5State16setScissorParamsEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='1076' u='w' c='_ZN2gl5State16setScissorParamsEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='1448' u='r' c='_ZN2gl5State17setViewportParamsEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='1451' u='w' c='_ZN2gl5State17setViewportParamsEiiii'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='2625' u='r' c='_ZNK2gl5State11getIntegervEPKNS_7ContextEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/State.cpp' l='2631' u='r' c='_ZNK2gl5State11getIntegervEPKNS_7ContextEjPi'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1263' u='r' c='_ZN2gl7Texture9copyImageEPNS_7ContextENS_13TextureTargetEiRKNS_9RectangleEjPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1264' u='r' c='_ZN2gl7Texture9copyImageEPNS_7ContextENS_13TextureTargetEiRKNS_9RectangleEjPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1270' u='r' c='_ZN2gl7Texture9copyImageEPNS_7ContextENS_13TextureTargetEiRKNS_9RectangleEjPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1270' u='r' c='_ZN2gl7Texture9copyImageEPNS_7ContextENS_13TextureTargetEiRKNS_9RectangleEjPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1329' u='r' c='_ZN2gl7Texture12copySubImageEPNS_7ContextERKNS_10ImageIndexERKNS_6OffsetERKNS_9RectangleEPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/Texture.cpp' l='1329' u='r' c='_ZN2gl7Texture12copySubImageEPNS_7ContextERKNS_10ImageIndexERKNS_6OffsetERKNS_9RectangleEPNS_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='574' u='w' c='_ZNK2gl9Rectangle4flipEbb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='574' u='r' c='_ZNK2gl9Rectangle4flipEbb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='597' u='r' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='611' u='r' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='614' u='r' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='628' u='r' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='644' u='w' c='_ZN2gl13ClipRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='658' u='r' c='_ZN2gl21GetEnclosingRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='660' u='r' c='_ZN2gl21GetEnclosingRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='691' u='w' c='_ZN2gl21GetEnclosingRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='703' u='r' c='_ZN2gl15ExtendRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='705' u='r' c='_ZN2gl15ExtendRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/angletypes.cpp' l='757' u='w' c='_ZN2gl15ExtendRectangleERKNS_9RectangleES2_PS0_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/frame_capture_utils.cpp' l='232' u='r' c='_ZN5angle12_GLOBAL__N_118SerializeRectangleEPN2gl18BinaryOutputStreamERKNS1_9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/queryutils.cpp' l='334' c='_ZN2gl12_GLOBAL__N_121QueryTexParameterBaseEPKNS_7ContextEPKNS_7TextureEjPT1_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='323' u='r' c='_ZN2rx6BlitGL35copySubImageToLUMAWorkaroundTextureEPKN2gl7ContextEjNS1_11TextureTypeENS1_13TextureTargetEjmRKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='493' u='r' c='_ZN2rx6BlitGL25blitColorBufferWithShaderEPKN2gl7ContextEPKNS1_11FramebufferEjRKNS1_9RectangleESA_jb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='497' u='w' c='_ZN2rx6BlitGL25blitColorBufferWithShaderEPKN2gl7ContextEPKNS1_11FramebufferEjRKNS1_9RectangleESA_jb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='497' u='r' c='_ZN2rx6BlitGL25blitColorBufferWithShaderEPKN2gl7ContextEPKNS1_11FramebufferEjRKNS1_9RectangleESA_jb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='509' u='r' c='_ZN2rx6BlitGL25blitColorBufferWithShaderEPKN2gl7ContextEPKNS1_11FramebufferEjRKNS1_9RectangleESA_jb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='634' u='r' c='_ZN2rx6BlitGL14copySubTextureEPKN2gl7ContextEPNS_9TextureGLEmjjNS1_13TextureTargetEmjRKNS1_7ExtentsERKNS1_9RectangleERKNS1_6OffsetEbjbbbPb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='745' u='w' c='_ZN2rx6BlitGL25copySubTextureCPUReadbackEPKN2gl7ContextEPNS_9TextureGLEmjS6_NS1_13TextureTargetEmjjRKNS1_7ExtentsERKNS1_9RectangleERKNS1_6OffsetEbjbbb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='784' u='r' c='_ZN2rx6BlitGL25copySubTextureCPUReadbackEPKN2gl7ContextEPNS_9TextureGLEmjS6_NS1_13TextureTargetEmjjRKNS1_7ExtentsERKNS1_9RectangleERKNS1_6OffsetEbjbbb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/BlitGL.cpp' l='843' u='r' c='_ZN2rx6BlitGL15copyTexSubImageEPKN2gl7ContextEPNS_9TextureGLEmS6_NS1_13TextureTargetEmRKNS1_9RectangleERKNS1_6OffsetEPb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='473' u='r' c='_ZN2rx13FramebufferGL13invalidateSubEPKN2gl7ContextEmPKjRKNS1_9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='659' u='r' c='_ZN2rx13FramebufferGL10readPixelsEPKN2gl7ContextERKNS1_9RectangleEjjRKNS1_14PixelPackStateEPNS1_6BufferEPv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='659' u='r' c='_ZN2rx13FramebufferGL10readPixelsEPKN2gl7ContextERKNS1_9RectangleEjjRKNS1_14PixelPackStateEPNS1_6BufferEPv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='825' u='r' c='_ZN2rx13FramebufferGL4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='826' u='r' c='_ZN2rx13FramebufferGL4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='862' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='893' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='904' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='930' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='958' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='986' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1017' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1028' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1054' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1084' u='r' c='_ZN2rx13FramebufferGL18adjustSrcDstRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1124' u='r' c='_ZN2rx13FramebufferGL13clipSrcRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1124' u='r' c='_ZN2rx13FramebufferGL13clipSrcRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1148' u='r' c='_ZN2rx13FramebufferGL13clipSrcRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1153' u='r' c='_ZN2rx13FramebufferGL13clipSrcRegionEPKN2gl7ContextERKNS1_9RectangleES7_PS5_S8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1481' u='r' c='_ZNK2rx13FramebufferGL18readPixelsRowByRowEPKN2gl7ContextERKNS1_9RectangleEjjjRKNS1_14PixelPackStateEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1531' u='r' c='_ZNK2rx13FramebufferGL19readPixelsAllAtOnceEPKN2gl7ContextERKNS1_9RectangleEjjjRKNS1_14PixelPackStateEPhb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/FramebufferGL.cpp' l='1543' u='r' c='_ZNK2rx13FramebufferGL19readPixelsAllAtOnceEPKN2gl7ContextERKNS1_9RectangleEjjjRKNS1_14PixelPackStateEPhb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='1030' u='r' c='_ZN2rx14StateManagerGL10setScissorERKN2gl9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/StateManagerGL.cpp' l='1041' u='r' c='_ZN2rx14StateManagerGL11setViewportERKN2gl9RectangleE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='651' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='652' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='713' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='713' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='751' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='759' u='r' c='_ZN2rx9TextureGL9copyImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_9RectangleEjPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='796' u='r' c='_ZN2rx9TextureGL12copySubImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='796' u='r' c='_ZN2rx9TextureGL12copySubImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='830' u='r' c='_ZN2rx9TextureGL12copySubImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/gl/TextureGL.cpp' l='839' u='r' c='_ZN2rx9TextureGL12copySubImageEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleEPNS1_11FramebufferE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ContextMtl.mm' l='2315' u='r' c='_ZN2rx10ContextMtl25handleDirtyDriverUniformsEPKN2gl7ContextEij'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='240' u='r' c='_ZN2rx14FramebufferMtl10readPixelsEPKN2gl7ContextERKNS1_9RectangleEjjRKNS1_14PixelPackStateEPNS1_6BufferEPv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='240' u='r' c='_ZN2rx14FramebufferMtl10readPixelsEPKN2gl7ContextERKNS1_9RectangleEjjRKNS1_14PixelPackStateEPNS1_6BufferEPv'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='328' u='r' c='_ZN2rx14FramebufferMtl4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='328' u='r' c='_ZN2rx14FramebufferMtl4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='345' u='w' c='_ZN2rx14FramebufferMtl4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='350' u='r' c='_ZN2rx14FramebufferMtl4blitEPKN2gl7ContextERKNS1_9RectangleES7_jj'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='913' u='r' c='_ZN2rx14FramebufferMtl30getReadableViewForRenderTargetEPKN2gl7ContextERKNS_15RenderTargetMtlERKNS1_9RectangleEPNSt3__110shared_ptrINS_3mtl7TextureEEESG_PjSH_PS8_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1373' u='r' c='_ZNK2rx14FramebufferMtl14readPixelsImplEPKN2gl7ContextERKNS1_9RectangleERKNS_16PackPixelsParamsEPKNS_15RenderTargetMtlEPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/FrameBufferMtl.mm' l='1503' u='r' c='_ZNK2rx14FramebufferMtl18readPixelsToBufferEPKN2gl7ContextERKNS1_9RectangleEPKNS_15RenderTargetMtlEbRKN5angle6FormatEjjPKNSt3__110shared_ptrINS_3mtl6BufferEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/TextureMtl.mm' l='2104' u='r' c='_ZN2rx10TextureMtl16copySubImageImplEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleERKNS1_14InternalFormatEPKNS_14FramebufferMtlEPKNS_15RenderTargetMtlE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/TextureMtl.mm' l='2104' u='r' c='_ZN2rx10TextureMtl16copySubImageImplEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleERKNS1_14InternalFormatEPKNS_14FramebufferMtlEPKNS_15RenderTargetMtlE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/TextureMtl.mm' l='2172' u='r' c='_ZN2rx10TextureMtl15copySubImageCPUEPKN2gl7ContextERKNS1_10ImageIndexERKNS1_6OffsetERKNS1_9RectangleERKNS1_14InternalFormatEPKNS_14FramebufferMtlEPKNS_15RenderTargetMtlE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_render_utils.mm' l='2783' u='r' c='_ZN2rx3mtl15CopyPixelsUtils29packPixelsFromTextureToBufferEPNS_10ContextMtlERKN5angle6FormatERKNS0_24CopyPixelsToBufferParamsE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='374' u='r' c='_ZN2rx3mtl24ReadTexturePerSliceBytesEPKN2gl7ContextERKNSt3__110shared_ptrINS0_7TextureEEEmRKNS1_9RectangleERKNS1_17LevelIndexWrapperIjEEjPh'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='408' u='r' c='_ZN2rx3mtl32ReadTexturePerSliceBytesToBufferEPKN2gl7ContextERKNSt3__110shared_ptrINS0_7TextureEEEmRKNS1_9RectangleERKNS1_17LevelIndexWrapperIjEEjjRKNS6_INS0_6BufferEEE'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='422' u='r' c='_ZN2rx3mtl11GetViewportERKN2gl9RectangleEdd'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='439' u='r' c='_ZN2rx3mtl16GetViewportFlipYERKN2gl9RectangleEmdd'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/mtl_utils.mm' l='467' u='r' c='_ZN2rx3mtl14GetScissorRectERKN2gl9RectangleEmb'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='223' u='w' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='223' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='230' u='w' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='231' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='231' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='237' u='w' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='237' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='244' u='w' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='245' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/renderer/renderer_utils.cpp' l='245' u='r' c='_ZN2rx15RotateRectangleENS_15SurfaceRotationEbiiRKN2gl9RectangleEPS2_'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp' l='63' u='r' c='_ZN2gl12_GLOBAL__N_113IsPartialBlitEPKNS_7ContextEPKNS_21FramebufferAttachmentES6_iiiiiiii'/>
