<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/usrsctp/usrsctplib/usrsctplib/netinet/sctp_structs.h' l='269' type='uint32_t'/>
<offset>384</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/usrsctp/usrsctplib/usrsctplib/netinet/sctp_cc_functions.c' l='2024' u='w' c='measure_achieved_throughput'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/usrsctp/usrsctplib/usrsctplib/netinet/sctp_cc_functions.c' l='2026' u='w' c='measure_achieved_throughput'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/usrsctp/usrsctplib/usrsctplib/netinet/sctp_cc_functions.c' l='2026' u='r' c='measure_achieved_throughput'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/usrsctp/usrsctplib/usrsctplib/netinet/sctp_cc_functions.c' l='2027' u='r' c='measure_achieved_throughput'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/usrsctp/usrsctplib/usrsctplib/netinet/sctp_cc_functions.c' l='2028' u='r' c='measure_achieved_throughput'/>
