<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3027' ll='3074'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3031' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3033' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3044' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder12setProgramIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3051' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder14setProgramTypeENS1_11ProgramTypeE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3058' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder11setCanvasIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3084' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3086' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram6createEv'/>
<mbr r='Inspector::Protocol::Canvas::ShaderProgram::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder12setProgramIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder14setProgramTypeENS1_11ProgramTypeE'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder11setCanvasIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3027' ll='3074'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3031' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3033' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3044' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder12setProgramIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3051' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder14setProgramTypeENS1_11ProgramTypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3058' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder11setCanvasIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3084' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3086' c='_ZN9Inspector8Protocol6Canvas13ShaderProgram6createEv'/>
<mbr r='Inspector::Protocol::Canvas::ShaderProgram::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder12setProgramIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder14setProgramTypeENS1_11ProgramTypeE'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder11setCanvasIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol6Canvas13ShaderProgram7Builder7releaseEv'/>
