<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='6580' ll='6620'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='6584' c='_ZN9Inspector8Protocol6Memory12CategoryData7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='6586' c='_ZN9Inspector8Protocol6Memory12CategoryData7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='6597' c='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='6604' c='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7setSizeEd'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='6629' c='_ZN9Inspector8Protocol6Memory12CategoryData6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='6631' c='_ZN9Inspector8Protocol6Memory12CategoryData6createEv'/>
<mbr r='Inspector::Protocol::Memory::CategoryData::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7setSizeEd'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='6580' ll='6620'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='6584' c='_ZN9Inspector8Protocol6Memory12CategoryData7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='6586' c='_ZN9Inspector8Protocol6Memory12CategoryData7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='6597' c='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='6604' c='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7setSizeEd'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='6629' c='_ZN9Inspector8Protocol6Memory12CategoryData6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='6631' c='_ZN9Inspector8Protocol6Memory12CategoryData6createEv'/>
<mbr r='Inspector::Protocol::Memory::CategoryData::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7setSizeEd'/>
<fun r='_ZN9Inspector8Protocol6Memory12CategoryData7Builder7releaseEv'/>
