<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1912' ll='1952'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1916' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1918' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1929' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1936' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder8setRulesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_7CSSRuleEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1961' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='1963' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyleSheetBody::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder8setRulesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_7CSSRuleEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1912' ll='1952'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1916' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1918' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1929' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1936' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder8setRulesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_7CSSRuleEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1961' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='1963' c='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyleSheetBody::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder8setRulesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_7CSSRuleEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleSheetBody7Builder7releaseEv'/>
