<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3547' ll='3608'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3551' c='_ZN9Inspector8Protocol3DOM4Node7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3553' c='_ZN9Inspector8Protocol3DOM4Node7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3564' c='_ZN9Inspector8Protocol3DOM4Node7Builder9setNodeIdEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3571' c='_ZN9Inspector8Protocol3DOM4Node7Builder11setNodeTypeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3578' c='_ZN9Inspector8Protocol3DOM4Node7Builder11setNodeNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3585' c='_ZN9Inspector8Protocol3DOM4Node7Builder12setLocalNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3592' c='_ZN9Inspector8Protocol3DOM4Node7Builder12setNodeValueERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3620' c='_ZN9Inspector8Protocol3DOM4Node6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3622' c='_ZN9Inspector8Protocol3DOM4Node6createEv'/>
<mbr r='Inspector::Protocol::DOM::Node::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder9setNodeIdEi'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder11setNodeTypeEi'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder11setNodeNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder12setLocalNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder12setNodeValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3547' ll='3608'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3551' c='_ZN9Inspector8Protocol3DOM4Node7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3553' c='_ZN9Inspector8Protocol3DOM4Node7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3564' c='_ZN9Inspector8Protocol3DOM4Node7Builder9setNodeIdEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3571' c='_ZN9Inspector8Protocol3DOM4Node7Builder11setNodeTypeEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3578' c='_ZN9Inspector8Protocol3DOM4Node7Builder11setNodeNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3585' c='_ZN9Inspector8Protocol3DOM4Node7Builder12setLocalNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3592' c='_ZN9Inspector8Protocol3DOM4Node7Builder12setNodeValueERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3620' c='_ZN9Inspector8Protocol3DOM4Node6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3622' c='_ZN9Inspector8Protocol3DOM4Node6createEv'/>
<mbr r='Inspector::Protocol::DOM::Node::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder9setNodeIdEi'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder11setNodeTypeEi'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder11setNodeNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder12setLocalNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder12setNodeValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM4Node7Builder7releaseEv'/>
