<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9945' ll='9985'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9949' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9951' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9962' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder12setTimestampEd'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9969' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder14setStackFramesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_10StackFrameEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9994' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9996' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::StackTrace::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder12setTimestampEd'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder14setStackFramesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_10StackFrameEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9945' ll='9985'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9949' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9951' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9962' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder12setTimestampEd'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9969' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder14setStackFramesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_10StackFrameEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9994' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9996' c='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::StackTrace::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder12setTimestampEd'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder14setStackFramesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_10StackFrameEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackTrace7Builder7releaseEv'/>
