<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2829' type='50'/>
<dec f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2829' type='50'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.cpp' l='505' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/inspector/InspectorShaderProgram.cpp' l='121' c='_ZN7WebCoreL13shaderForTypeERNS_12WebGLProgramEN9Inspector8Protocol6Canvas10ShaderTypeE'/>
<use f='webkit/Source/WebCore/inspector/InspectorShaderProgram.cpp' l='134' c='_ZN7WebCoreL13shaderForTypeERNS_14WebGPUPipelineEN9Inspector8Protocol6Canvas10ShaderTypeE'/>
