<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7177' ll='7210'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7181' c='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7183' c='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7194' c='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7218' c='_ZN9Inspector8Protocol7Network16WebSocketRequest6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7220' c='_ZN9Inspector8Protocol7Network16WebSocketRequest6createEv'/>
<mbr r='Inspector::Protocol::Network::WebSocketRequest::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network16WebSocketRequest7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7177' ll='7210'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7181' c='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7183' c='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7194' c='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7218' c='_ZN9Inspector8Protocol7Network16WebSocketRequest6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7220' c='_ZN9Inspector8Protocol7Network16WebSocketRequest6createEv'/>
<mbr r='Inspector::Protocol::Network::WebSocketRequest::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network16WebSocketRequest7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network16WebSocketRequest7Builder7releaseEv'/>
