<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8138' ll='8164'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8142' c='_ZN9Inspector8Protocol9Recording12InitialState7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8144' c='_ZN9Inspector8Protocol9Recording12InitialState7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8171' c='_ZN9Inspector8Protocol9Recording12InitialState6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8173' c='_ZN9Inspector8Protocol9Recording12InitialState6createEv'/>
<mbr r='Inspector::Protocol::Recording::InitialState::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Recording12InitialState7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Recording12InitialState7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording12InitialState7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8138' ll='8164'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8142' c='_ZN9Inspector8Protocol9Recording12InitialState7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8144' c='_ZN9Inspector8Protocol9Recording12InitialState7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8171' c='_ZN9Inspector8Protocol9Recording12InitialState6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8173' c='_ZN9Inspector8Protocol9Recording12InitialState6createEv'/>
<mbr r='Inspector::Protocol::Recording::InitialState::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Recording12InitialState7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Recording12InitialState7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording12InitialState7Builder7releaseEv'/>
