<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2229' ll='2262'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2233' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2235' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2246' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2270' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='2272' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSPropertyInfo::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2229' ll='2262'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2233' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2235' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2246' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2270' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='2272' c='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSPropertyInfo::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS15CSSPropertyInfo7Builder7releaseEv'/>
