<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5862' ll='5902'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5866' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5868' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5879' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder12setLowerOpenEb'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5886' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder12setUpperOpenEb'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5911' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='5913' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::KeyRange::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder12setLowerOpenEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder12setUpperOpenEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5862' ll='5902'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5866' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5868' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5879' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder12setLowerOpenEb'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5886' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder12setUpperOpenEb'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5911' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='5913' c='_ZN9Inspector8Protocol9IndexedDB8KeyRange6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::KeyRange::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder12setLowerOpenEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder12setUpperOpenEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB8KeyRange7Builder7releaseEv'/>
