<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='899' ll='925'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='903' c='_ZN9Inspector8Protocol10Automation15InteractionStep7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='905' c='_ZN9Inspector8Protocol10Automation15InteractionStep7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='932' c='_ZN9Inspector8Protocol10Automation15InteractionStep6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='934' c='_ZN9Inspector8Protocol10Automation15InteractionStep6createEv'/>
<mbr r='Inspector::Protocol::Automation::InteractionStep::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation15InteractionStep7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation15InteractionStep7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation15InteractionStep7Builder7releaseEv'/>
