<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='760' ll='800'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='764' c='_ZN9Inspector8Protocol10Automation21SessionPermissionData7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='766' c='_ZN9Inspector8Protocol10Automation21SessionPermissionData7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='777' c='_ZN9Inspector8Protocol10Automation21SessionPermissionData7Builder13setPermissionENS1_17SessionPermissionE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='784' c='_ZN9Inspector8Protocol10Automation21SessionPermissionData7Builder8setValueEb'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='809' c='_ZN9Inspector8Protocol10Automation21SessionPermissionData6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='811' c='_ZN9Inspector8Protocol10Automation21SessionPermissionData6createEv'/>
<mbr r='Inspector::Protocol::Automation::SessionPermissionData::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation21SessionPermissionData7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation21SessionPermissionData7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation21SessionPermissionData7Builder13setPermissionENS1_17SessionPermissionE'/>
<fun r='_ZN9Inspector8Protocol10Automation21SessionPermissionData7Builder8setValueEb'/>
<fun r='_ZN9Inspector8Protocol10Automation21SessionPermissionData7Builder7releaseEv'/>
