<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='835' ll='875'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='839' c='_ZN9Inspector8Protocol10Automation11InputSource7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='841' c='_ZN9Inspector8Protocol10Automation11InputSource7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='852' c='_ZN9Inspector8Protocol10Automation11InputSource7Builder11setSourceIdERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='859' c='_ZN9Inspector8Protocol10Automation11InputSource7Builder13setSourceTypeENS1_15InputSourceTypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='884' c='_ZN9Inspector8Protocol10Automation11InputSource6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='886' c='_ZN9Inspector8Protocol10Automation11InputSource6createEv'/>
<mbr r='Inspector::Protocol::Automation::InputSource::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation11InputSource7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation11InputSource7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation11InputSource7Builder11setSourceIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10Automation11InputSource7Builder13setSourceTypeENS1_15InputSourceTypeE'/>
<fun r='_ZN9Inspector8Protocol10Automation11InputSource7Builder7releaseEv'/>
