<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9851' ll='9912'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9855' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9857' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9868' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder11setSourceIDERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9875' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9882' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7setLineEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9889' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9setColumnEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9896' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder6setUrlERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9924' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9926' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::StackFrame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder11setSourceIDERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7setLineEi'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9setColumnEi'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9851' ll='9912'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9855' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9857' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9868' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder11setSourceIDERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9875' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9882' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7setLineEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9889' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9setColumnEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9896' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder6setUrlERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9924' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9926' c='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::StackFrame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder11setSourceIDERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7setLineEi'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder9setColumnEi'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler10StackFrame7Builder7releaseEv'/>
