<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='4536' ll='4576'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='4540' c='_ZN9Inspector8Protocol8Database5Error7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='4542' c='_ZN9Inspector8Protocol8Database5Error7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='4553' c='_ZN9Inspector8Protocol8Database5Error7Builder10setMessageERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='4560' c='_ZN9Inspector8Protocol8Database5Error7Builder7setCodeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='4585' c='_ZN9Inspector8Protocol8Database5Error6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='4587' c='_ZN9Inspector8Protocol8Database5Error6createEv'/>
<mbr r='Inspector::Protocol::Database::Error::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7Builder10setMessageERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7Builder7setCodeEi'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='4536' ll='4576'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='4540' c='_ZN9Inspector8Protocol8Database5Error7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='4542' c='_ZN9Inspector8Protocol8Database5Error7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='4553' c='_ZN9Inspector8Protocol8Database5Error7Builder10setMessageERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='4560' c='_ZN9Inspector8Protocol8Database5Error7Builder7setCodeEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='4585' c='_ZN9Inspector8Protocol8Database5Error6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='4587' c='_ZN9Inspector8Protocol8Database5Error6createEv'/>
<mbr r='Inspector::Protocol::Database::Error::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7Builder10setMessageERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7Builder7setCodeEi'/>
<fun r='_ZN9Inspector8Protocol8Database5Error7Builder7releaseEv'/>
