<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3139' ll='3179'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3143' c='_ZN9Inspector8Protocol7Console7Channel7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3145' c='_ZN9Inspector8Protocol7Console7Channel7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3156' c='_ZN9Inspector8Protocol7Console7Channel7Builder9setSourceENS1_13ChannelSourceE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3163' c='_ZN9Inspector8Protocol7Console7Channel7Builder8setLevelENS1_12ChannelLevelE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3188' c='_ZN9Inspector8Protocol7Console7Channel6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='3190' c='_ZN9Inspector8Protocol7Console7Channel6createEv'/>
<mbr r='Inspector::Protocol::Console::Channel::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7Builder9setSourceENS1_13ChannelSourceE'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7Builder8setLevelENS1_12ChannelLevelE'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3139' ll='3179'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3143' c='_ZN9Inspector8Protocol7Console7Channel7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3145' c='_ZN9Inspector8Protocol7Console7Channel7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3156' c='_ZN9Inspector8Protocol7Console7Channel7Builder9setSourceENS1_13ChannelSourceE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3163' c='_ZN9Inspector8Protocol7Console7Channel7Builder8setLevelENS1_12ChannelLevelE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3188' c='_ZN9Inspector8Protocol7Console7Channel6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='3190' c='_ZN9Inspector8Protocol7Console7Channel6createEv'/>
<mbr r='Inspector::Protocol::Console::Channel::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7Builder9setSourceENS1_13ChannelSourceE'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7Builder8setLevelENS1_12ChannelLevelE'/>
<fun r='_ZN9Inspector8Protocol7Console7Channel7Builder7releaseEv'/>
