<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='626' ll='722'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='630' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='632' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='643' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder7setNameERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='650' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder8setValueERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='657' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder9setDomainERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='664' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder7setPathERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='671' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder10setExpiresEd'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='678' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder7setSizeEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='685' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder11setHttpOnlyEb'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='692' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder9setSecureEb'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='699' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder10setSessionEb'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='706' c='_ZN9Inspector8Protocol10Automation6Cookie7Builder11setSameSiteENS1_20CookieSameSitePolicyE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='739' c='_ZN9Inspector8Protocol10Automation6Cookie6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='741' c='_ZN9Inspector8Protocol10Automation6Cookie6createEv'/>
<mbr r='Inspector::Protocol::Automation::Cookie::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder9setDomainERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder7setPathERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder10setExpiresEd'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder7setSizeEi'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder11setHttpOnlyEb'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder9setSecureEb'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder10setSessionEb'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder11setSameSiteENS1_20CookieSameSitePolicyE'/>
<fun r='_ZN9Inspector8Protocol10Automation6Cookie7Builder7releaseEv'/>
