<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='7474' type='159'/>
<dec f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='7474' type='159'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.cpp' l='915' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/inspector/agents/InspectorNetworkAgent.cpp' l='747' u='r' c='_ZN7WebCore21InspectorNetworkAgent20buildInitiatorObjectEPNS_8DocumentEPKNS_15ResourceRequestE'/>
