<dec f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='464' type='45'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.cpp' l='298' u='r' c='_ZN9Inspector8Protocol17AutomationHelpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='webkit/Source/WebKit/UIProcess/Automation/cocoa/WebAutomationSessionCocoa.mm' l='91' c='_ZNK6WebKit20WebAutomationSession21charCodeForVirtualKeyEN9Inspector8Protocol10Automation10VirtualKeyE'/>
<use f='webkit/Source/WebKit/UIProcess/Automation/mac/WebAutomationSessionMac.mm' l='263' c='_ZN6WebKitL27virtualKeyHasStickyModifierEN9Inspector8Protocol10Automation10VirtualKeyE'/>
<use f='webkit/Source/WebKit/UIProcess/Automation/mac/WebAutomationSessionMac.mm' l='429' c='_ZN6WebKitL20keyCodeForVirtualKeyEN9Inspector8Protocol10Automation10VirtualKeyE'/>
<use f='webkit/Source/WebKit/UIProcess/Automation/mac/WebAutomationSessionMac.mm' l='571' c='_ZN6WebKitL31eventModifierFlagsForVirtualKeyEN9Inspector8Protocol10Automation10VirtualKeyE'/>
