<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8395' ll='8428'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8399' c='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8401' c='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8412' c='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8436' c='_ZN9Inspector8Protocol7Runtime12RemoteObject6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='8438' c='_ZN9Inspector8Protocol7Runtime12RemoteObject6createEv'/>
<mbr r='Inspector::Protocol::Runtime::RemoteObject::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime12RemoteObject7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8395' ll='8428'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8399' c='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8401' c='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8412' c='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder7setTypeENS2_4TypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8436' c='_ZN9Inspector8Protocol7Runtime12RemoteObject6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='8438' c='_ZN9Inspector8Protocol7Runtime12RemoteObject6createEv'/>
<mbr r='Inspector::Protocol::Runtime::RemoteObject::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime12RemoteObject7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12RemoteObject7Builder7releaseEv'/>
