<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='349' ll='410'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='353' c='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='355' c='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='366' c='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder9setHandleERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='373' c='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder9setActiveEb'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='380' c='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder6setUrlERKN3WTF6StringE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='387' c='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder13setWindowSizeEON3WTF3RefINS1_4SizeENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='394' c='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder15setWindowOriginEON3WTF3RefINS1_5PointENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='422' c='_ZN9Inspector8Protocol10Automation15BrowsingContext6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='424' c='_ZN9Inspector8Protocol10Automation15BrowsingContext6createEv'/>
<mbr r='Inspector::Protocol::Automation::BrowsingContext::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation15BrowsingContext7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder9setHandleERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder9setActiveEb'/>
<fun r='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder13setWindowSizeEON3WTF3RefINS1_4SizeENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder15setWindowOriginEON3WTF3RefINS1_5PointENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation15BrowsingContext7Builder7releaseEv'/>
