<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9783' ll='9823'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9787' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9789' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9800' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder7setLineEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9807' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9setColumnEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9832' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation6createEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/InspectorProtocolObjects.h' l='9834' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::ExpressionLocation::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder7setLineEi'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9setColumnEi'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder7releaseEv'/>
<def f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9783' ll='9823'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9787' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9789' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9800' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder7setLineEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9807' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9setColumnEi'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9832' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/JavaScriptCore/inspector/InspectorProtocolObjects.h' l='9834' c='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::ExpressionLocation::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder7setLineEi'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder9setColumnEi'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler18ExpressionLocation7Builder7releaseEv'/>
