<def f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='544' ll='577'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='548' c='_ZN9Inspector8Protocol10Automation19KeyboardInteraction7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='550' c='_ZN9Inspector8Protocol10Automation19KeyboardInteraction7Builder9castStateEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='561' c='_ZN9Inspector8Protocol10Automation19KeyboardInteraction7Builder7setTypeENS1_23KeyboardInteractionTypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='585' c='_ZN9Inspector8Protocol10Automation19KeyboardInteraction6createEv'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebKit2/AutomationProtocolObjects.h' l='587' c='_ZN9Inspector8Protocol10Automation19KeyboardInteraction6createEv'/>
<mbr r='Inspector::Protocol::Automation::KeyboardInteraction::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10Automation19KeyboardInteraction7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10Automation19KeyboardInteraction7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10Automation19KeyboardInteraction7Builder7setTypeENS1_23KeyboardInteractionTypeE'/>
<fun r='_ZN9Inspector8Protocol10Automation19KeyboardInteraction7Builder7releaseEv'/>
