<dec f='webkit/Source/JavaScriptCore/wasm/WasmFormat.h' l='344' type='0'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmFormat.h' l='353' c='_ZN3JSC4Wasm15isValidNameTypeET_'/>
<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/WasmFormat.h' l='344' type='0'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/WasmFormat.h' l='353' c='_ZN3JSC4Wasm15isValidNameTypeET_'/>
