<dec f='webkit/Source/JavaScriptCore/runtime/JSGenerator.h' l='58' type='0'/>
<use f='webkit/Source/JavaScriptCore/runtime/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='webkit/Source/JavaScriptCore/runtime/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/JSGenerator.h' l='58' type='0'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
