<dec f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='315' type='1'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='976' u='c' c='_ZN3JSC14ARM64Assembler3cmnENS_14ARM64Registers10RegisterIDENS_6UInt12Ei'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='982' u='c' c='_ZN3JSC14ARM64Assembler3cmnENS_14ARM64Registers10RegisterIDES2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='988' u='c' c='_ZN3JSC14ARM64Assembler3cmnENS_14ARM64Registers10RegisterIDES2_NS0_10ExtendTypeEi'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='994' u='c' c='_ZN3JSC14ARM64Assembler3cmnENS_14ARM64Registers10RegisterIDES2_NS0_9ShiftTypeEi'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1000' u='c' c='_ZN3JSC14ARM64Assembler3cmpENS_14ARM64Registers10RegisterIDENS_6UInt12Ei'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1006' u='c' c='_ZN3JSC14ARM64Assembler3cmpENS_14ARM64Registers10RegisterIDES2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1012' u='c' c='_ZN3JSC14ARM64Assembler3cmpENS_14ARM64Registers10RegisterIDES2_NS0_10ExtendTypeEi'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='1018' u='c' c='_ZN3JSC14ARM64Assembler3cmpENS_14ARM64Registers10RegisterIDES2_NS0_9ShiftTypeEi'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='2035' u='c' c='_ZN3JSC14ARM64Assembler3tstENS_14ARM64Registers10RegisterIDES2_'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='2041' u='c' c='_ZN3JSC14ARM64Assembler3tstENS_14ARM64Registers10RegisterIDES2_NS0_9ShiftTypeEi'/>
<use f='webkit/Source/JavaScriptCore/assembler/ARM64Assembler.h' l='2047' u='c' c='_ZN3JSC14ARM64Assembler3tstENS_14ARM64Registers10RegisterIDENS_21ARM64LogicalImmediateE'/>
<use f='webkit/Source/JavaScriptCore/assembler/MacroAssemblerARM64.h' l='57'/>
<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='315' type='1'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='976' u='c' c='_ZN3JSC14ARM64Assembler3cmnENS_14ARM64Registers10RegisterIDENS_6UInt12Ei'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='982' u='c' c='_ZN3JSC14ARM64Assembler3cmnENS_14ARM64Registers10RegisterIDES2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='988' u='c' c='_ZN3JSC14ARM64Assembler3cmnENS_14ARM64Registers10RegisterIDES2_NS0_10ExtendTypeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='994' u='c' c='_ZN3JSC14ARM64Assembler3cmnENS_14ARM64Registers10RegisterIDES2_NS0_9ShiftTypeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1000' u='c' c='_ZN3JSC14ARM64Assembler3cmpENS_14ARM64Registers10RegisterIDENS_6UInt12Ei'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1006' u='c' c='_ZN3JSC14ARM64Assembler3cmpENS_14ARM64Registers10RegisterIDES2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1012' u='c' c='_ZN3JSC14ARM64Assembler3cmpENS_14ARM64Registers10RegisterIDES2_NS0_10ExtendTypeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='1018' u='c' c='_ZN3JSC14ARM64Assembler3cmpENS_14ARM64Registers10RegisterIDES2_NS0_9ShiftTypeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='2035' u='c' c='_ZN3JSC14ARM64Assembler3tstENS_14ARM64Registers10RegisterIDES2_'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='2041' u='c' c='_ZN3JSC14ARM64Assembler3tstENS_14ARM64Registers10RegisterIDES2_NS0_9ShiftTypeEi'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/ARM64Assembler.h' l='2047' u='c' c='_ZN3JSC14ARM64Assembler3tstENS_14ARM64Registers10RegisterIDENS_21ARM64LogicalImmediateE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/MacroAssemblerARM64.h' l='57'/>
