<dec f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='37' type='1'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='46' c='_ZN3JSC2B311forEachBankERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='61' u='r' c='_ZN3JSC2B311bankForTypeENS0_4TypeE'/>
<use f='webkit/Source/JavaScriptCore/b3/B3Bank.h' l='69' u='r' c='_ZN3JSC2B310bankForRegENS_3RegE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirTmp.h' l='83' u='r' c='_ZN3JSC2B33Air3Tmp11tmpForIndexENS0_4BankEj'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirTmp.h' l='102' u='r' c='_ZNK3JSC2B33Air3Tmp4bankEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirTmp.h' l='156' u='r' c='_ZNK3JSC2B33Air3Tmp8tmpIndexENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirArg.h' l='1092' u='r' c='_ZNK3JSC2B33Air3Arg4bankEv'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirArg.h' l='1100' c='_ZNK3JSC2B33Air3Arg6isBankENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCode.h' l='92' c='_ZNK3JSC2B33Air4Code19regsInPriorityOrderENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCode.h' l='127' c='_ZN3JSC2B33Air4Code6newTmpENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCode.h' l='138' c='_ZN3JSC2B33Air4Code7numTmpsENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCode.h' l='378' c='_ZN3JSC2B33Air4Code23regsInPriorityOrderImplENS0_4BankE'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirCustom.h' l='211' u='r' c='_ZN3JSC2B33Air13ShuffleCustom10forEachArgERNS1_4InstERKT_'/>
<use f='webkit/Source/JavaScriptCore/b3/air/AirInstInlines.h' l='88' u='r' c='_ZN3JSC2B33Air4Inst32forEachDefWithExtraClobberedRegsEPS2_S3_RKT0_'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='96'/>
<use f='webkit/Source/JavaScriptCore/b3/B3NativeTraits.h' l='103'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='404' c='_ZN3JSC4Wasm14AirIRGenerator6newTmpENS_2B34BankE'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='417' u='r' c='_ZN3JSC4Wasm14AirIRGenerator3f32Ev'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='418' u='r' c='_ZN3JSC4Wasm14AirIRGenerator3f64Ev'/>
