<dec f='webkit/Source/JavaScriptCore/dfg/DFGNodeType.h' l='182' type='80'/>
<use f='webkit/Source/JavaScriptCore/dfg/DFGNodeType.h' l='182' c='_ZN3JSC3DFG12defaultFlagsENS0_8NodeTypeE'/>
<use f='webkit/Source/JavaScriptCore/dfg/DFGAbstractInterpreterInlines.h' l='995' c='_ZN3JSC3DFG19AbstractInterpreter14executeEffectsEjPNS0_4NodeE'/>
<use f='webkit/Source/JavaScriptCore/dfg/DFGClobberize.h' l='752' c='_ZN3JSC3DFG10clobberizeERNS0_5GraphEPNS0_4NodeERKT_RKT0_RKT1_RKT2_'/>
<use f='webkit/Source/JavaScriptCore/dfg/DFGSpeculativeJIT.cpp' l='5539' u='r' c='_ZN3JSC3DFG14SpeculativeJIT15compileIncOrDecEPNS0_4NodeE'/>
<use f='webkit/Source/JavaScriptCore/dfg/DFGSpeculativeJIT64.cpp' l='2281' c='_ZN3JSC3DFG14SpeculativeJIT7compileEPNS0_4NodeE'/>
<use f='webkit/Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp' l='786' c='_ZN3JSC3FTL12_GLOBAL__N_112LowerDFGToB311compileNodeEj'/>
<use f='webkit/Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp' l='3348' u='r' c='_ZN3JSC3FTL12_GLOBAL__N_112LowerDFGToB315compileIncOrDecEv'/>
