<dec f='webkit/Source/JavaScriptCore/jit/JITCompilationMode.h' l='36' type='3'/>
<use f='webkit/Source/JavaScriptCore/jit/JITCompilationMode.h' l='43' c='_ZN3JSC5isFTLENS_18JITCompilationModeE'/>
<use f='webkit/Source/JavaScriptCore/ftl/FTLState.h' l='55' u='r' c='_ZN3JSC3FTL25verboseCompilationEnabledEv'/>
<use f='webkit/Source/JavaScriptCore/ftl/FTLState.h' l='60' u='r' c='_ZN3JSC3FTL21shouldDumpDisassemblyEv'/>
<dec f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/JITCompilationMode.h' l='36' type='3'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/JITCompilationMode.h' l='43' c='_ZN3JSC5isFTLENS_18JITCompilationModeE'/>
