<inh f='webkit/WebKitBuild/Debug/usr/local/include/wtf/ThreadSafeRefCounted.h' l='109' c='WTF::ThreadSafeRefCounted'/>
<def f='webkit/Source/JavaScriptCore/wasm/WasmModule.h' l='45' ll='77'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmModule.h' l='45'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmModule.h' l='47'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmModule.h' l='54' c='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmModule.h' l='56' c='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmInstance.h' l='57' c='_ZN3JSC4Wasm8Instance6createEPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEPPNS_10EntryFrameEPPvONS4_8FunctionIFvSE_EEE'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmInstance.h' l='74' c='_ZN3JSC4Wasm8Instance6moduleEv'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmInstance.h' l='214' c='_ZN3JSC4Wasm8InstanceC1EPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEPPNS_10EntryFrameEPPvONS4_8FunctionIFvSE_EEE'/>
<use f='webkit/Source/JavaScriptCore/wasm/WasmInstance.h' l='224'/>
<size>64</size>
<fun r='_ZN3JSC4Wasm6Module12validateSyncEPNS0_7ContextEON3WTF6VectorIhLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEE'/>
<fun r='_ZN3JSC4Wasm6Module13validateAsyncEPNS0_7ContextEON3WTF6VectorIhLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEEONS4_6RefPtrINS4_10SharedTaskIFvONSt2553828'/>
<fun r='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<fun r='_ZNK3JSC4Wasm6Module36signatureIndexFromFunctionIndexSpaceEj'/>
<fun r='_ZNK3JSC4Wasm6Module17moduleInformationEv'/>
<fun r='_ZN3JSC4Wasm6Module11compileSyncEPNS0_7ContextENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6Module12compileAsyncEPNS0_7ContextENS0_10MemoryModeEON3WTF6RefPtrINS5_10SharedTaskIFvONS5_3RefINS0_9CodeBlockENS5_12RawPtrTraitsIS9_EEEEE7203082'/>
<fun r='_ZN3JSC4Wasm6ModuleD1Ev'/>
<fun r='_ZN3JSC4Wasm6Module12codeBlockForENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6Module20getOrCreateCodeBlockEPNS0_7ContextENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6ModuleC1ERNS0_9LLIntPlanE'/>
<mbr r='JSC::Wasm::Module::m_moduleInformation' o='64' t='Ref&lt;JSC::Wasm::ModuleInformation&gt;'/>
<mbr r='JSC::Wasm::Module::m_codeBlocks' o='128' t='RefPtr&lt;JSC::Wasm::CodeBlock&gt; [2]'/>
<mbr r='JSC::Wasm::Module::m_llintCallees' o='256' t='RefPtr&lt;JSC::Wasm::LLIntCallees&gt;'/>
<mbr r='JSC::Wasm::Module::m_llintEntryThunks' o='320' t='MacroAssemblerCodeRef&lt;JITCompilationPtrTag&gt;'/>
<mbr r='JSC::Wasm::Module::m_lock' o='448' t='WTF::Lock'/>
<use f='webkit/Source/JavaScriptCore/wasm/js/JSWebAssemblyInstance.h' l='64' c='_ZN3JSC21JSWebAssemblyInstance9tryCreateERNS_2VMEPNS_14JSGlobalObjectERKNS_10IdentifierEPNS_19JSWebAssemblyModuleEPNS_8JSObjectEPNS_9StructureEON3WTF311460615'/>
<size>64</size>
<use f='webkit/Source/WebCore/bindings/js/SerializedScriptValue.h' l='65'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/SerializedScriptValue.h' l='65'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/JSWebAssemblyModule.h' l='66' c='_ZN3JSC19JSWebAssemblyModule10createStubERNS_2VMEPNS_14JSGlobalObjectEPNS_9StructureEONSt12experimental15fundamentals_v38expectedIN3WTF6RefPtrINS_4Was758355'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/JSWebAssemblyModule.h' l='76' c='_ZN3JSC19JSWebAssemblyModule6moduleEv'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/JSWebAssemblyModule.h' l='81' c='_ZN3JSC19JSWebAssemblyModuleC1ERNS_2VMEPNS_9StructureEON3WTF3RefINS_4Wasm6ModuleENS5_12RawPtrTraitsIS8_EEEE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/JSWebAssemblyModule.h' l='85'/>
<inh f='webkit/WebKitBuild/Debug/usr/local/include/wtf/ThreadSafeRefCounted.h' l='109' c='WTF::ThreadSafeRefCounted'/>
<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/WasmModule.h' l='45' ll='77'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/WasmModule.h' l='45'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/WasmModule.h' l='47'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/WasmModule.h' l='54' c='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<use f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/WasmModule.h' l='56' c='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<size>64</size>
<fun r='_ZN3JSC4Wasm6Module12validateSyncEPNS0_7ContextEON3WTF6VectorIhLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEE'/>
<fun r='_ZN3JSC4Wasm6Module13validateAsyncEPNS0_7ContextEON3WTF6VectorIhLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEEONS4_6RefPtrINS4_10SharedTaskIFvONSt2553828'/>
<fun r='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<fun r='_ZNK3JSC4Wasm6Module36signatureIndexFromFunctionIndexSpaceEj'/>
<fun r='_ZNK3JSC4Wasm6Module17moduleInformationEv'/>
<fun r='_ZN3JSC4Wasm6Module11compileSyncEPNS0_7ContextENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6Module12compileAsyncEPNS0_7ContextENS0_10MemoryModeEON3WTF6RefPtrINS5_10SharedTaskIFvONS5_3RefINS0_9CodeBlockENS5_12RawPtrTraitsIS9_EEEEE7203082'/>
<fun r='_ZN3JSC4Wasm6ModuleD1Ev'/>
<fun r='_ZN3JSC4Wasm6Module12codeBlockForENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6Module20getOrCreateCodeBlockEPNS0_7ContextENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6ModuleC1ERNS0_9LLIntPlanE'/>
<mbr r='JSC::Wasm::Module::m_moduleInformation' o='64' t='Ref&lt;JSC::Wasm::ModuleInformation&gt;'/>
<mbr r='JSC::Wasm::Module::m_codeBlocks' o='128' t='RefPtr&lt;JSC::Wasm::CodeBlock&gt; [2]'/>
<mbr r='JSC::Wasm::Module::m_llintCallees' o='256' t='RefPtr&lt;JSC::Wasm::LLIntCallees&gt;'/>
<mbr r='JSC::Wasm::Module::m_llintEntryThunks' o='320' t='MacroAssemblerCodeRef&lt;JITCompilationPtrTag&gt;'/>
<mbr r='JSC::Wasm::Module::m_lock' o='448' t='WTF::Lock'/>
