<dec f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/Layout.cpp' l='25' type='1'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/Layout.cpp' l='91' c='_ZL14ScalarLayoutOfRKN2sh5TTypeE8Language'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/Layout.cpp' l='295' u='r' c='_ZL18CommonGlslLayoutOfRKN2sh5TTypeENS_19TLayoutBlockStorageENS_20TLayoutMatrixPackingEbm'/>
