<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/md4.h' l='98' type='uint32_t'/>
<offset>128</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/digest/md32_common.h' l='146' u='r' c='MD4_Update'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/digest/md32_common.h' l='147' u='r' c='MD4_Update'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/digest/md32_common.h' l='152' u='w' c='MD4_Update'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/fipsmodule/digest/md32_common.h' l='215' u='r' c='MD4_Final'/>
