<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='59' type='opus_int32'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='139' u='w' c='opus_decoder_init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='140' u='r' c='opus_decoder_init'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='255' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='265' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='265' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='375' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='375' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='562' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='572' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='582' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='591' u='r' c='opus_decode_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='640' u='r' c='opus_decode_native'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='662' u='r' c='opus_decode_native'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='877' u='r' c='opus_decoder_ctl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='887' u='r' c='opus_decoder_ctl'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='1031' u='r' c='opus_decoder_get_nb_samples'/>
<offset>96</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/opus/src/src/opus_decoder.c' l='59'>/** Sampling rate (at the API level) */</doc>
