<def f='webkit/Source/WebCore/platform/xr/PlatformXR.h' l='56' ll='60'/>
<use f='webkit/Source/WebCore/platform/xr/PlatformXR.h' l='235'/>
<use f='webkit/Source/WebCore/platform/xr/PlatformXR.h' l='247'/>
<use f='webkit/Source/WebCore/Modules/webxr/XREye.h' l='34'/>
<def f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/PlatformXR.h' l='56' ll='60'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/PlatformXR.h' l='235'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/PlatformXR.h' l='247'/>
