<dec f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/ProgramPrelude.h' l='25' type='3'/>
<use f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect.cpp' l='923' u='r' c='_ZN2shL23metalShaderTypeFromGLSLEj'/>
<doc f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/ProgramPrelude.h' l='25'>// Unused currently</doc>
<use f='webkit/Source/ThirdParty/ANGLE/src/compiler/translator/TranslatorMetalDirect/ProgramPrelude.cpp' l='54' c='_ZN12_GLOBAL__N_114ProgramPreludeC1ERN2sh13TInfoSinkBaseERKNS1_20ProgramPreludeConfigE'/>
