<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/sha.h' l='116' type='uint32_t'/>
<offset>160</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/cipher_extra/tls_cbc.c' l='187' u='r' c='EVP_sha1_final_with_secret_suffix'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/cipher_extra/tls_cbc.c' l='188' u='r' c='EVP_sha1_final_with_secret_suffix'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/cipher_extra/tls_cbc.c' l='204' u='r' c='EVP_sha1_final_with_secret_suffix'/>
