<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/crypto/include/auth.h' l='128' type='srtp_auth_compute_func'/>
<offset>192</offset>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/crypto/hash/auth.c' l='128' macro='1' u='r' c='srtp_auth_type_test'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/srtp/srtp.c' l='2342' macro='1' u='r' c='srtp_protect_mki'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/srtp/srtp.c' l='2611' macro='1' u='r' c='srtp_unprotect_mki'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/srtp/srtp.c' l='4070' macro='1' u='r' c='srtp_protect_rtcp_mki'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libsrtp/srtp/srtp.c' l='4310' macro='1' u='r' c='srtp_unprotect_rtcp_mki'/>
