<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.h' l='22' type='VP9Decoder *'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='60' u='r' c='decoder_destroy'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='61' u='r' c='decoder_destroy'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='205' u='r' c='init_buffer_callbacks'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='262' u='w' c='init_decoder'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='263' u='r' c='init_decoder'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='267' u='r' c='init_decoder'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='268' u='r' c='init_decoder'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='271' u='r' c='init_decoder'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='274' u='r' c='init_decoder'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='316' u='r' c='decode_one'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='317' u='r' c='decode_one'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='319' u='r' c='decode_one'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='320' u='r' c='decode_one'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='321' u='r' c='decode_one'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='323' u='r' c='decode_one'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='326' u='r' c='decode_one'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='349' u='r' c='decoder_decode'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='407' u='r' c='decoder_get_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='411' u='r' c='decoder_get_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='412' u='r' c='decoder_get_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='414' u='r' c='decoder_get_frame'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='430' u='r' c='decoder_set_fb_fn'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='451' u='r' c='ctrl_set_reference'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='465' u='r' c='ctrl_copy_reference'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='477' u='r' c='ctrl_get_reference'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='478' u='r' c='ctrl_get_reference'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='479' u='r' c='ctrl_get_reference'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='513' u='r' c='ctrl_get_quantizer'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='514' u='r' c='ctrl_get_quantizer'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='523' u='r' c='ctrl_get_last_ref_updates'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='524' u='r' c='ctrl_get_last_ref_updates'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='539' u='r' c='ctrl_get_frame_corrupted'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='540' u='r' c='ctrl_get_frame_corrupted'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='541' u='r' c='ctrl_get_frame_corrupted'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='558' u='r' c='ctrl_get_frame_size'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='559' u='r' c='ctrl_get_frame_size'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='576' u='r' c='ctrl_get_render_size'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='577' u='r' c='ctrl_get_render_size'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='594' u='r' c='ctrl_get_bit_depth'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='595' u='r' c='ctrl_get_bit_depth'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='634' u='r' c='ctrl_set_byte_alignment'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='635' u='r' c='ctrl_set_byte_alignment'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='644' u='r' c='ctrl_set_skip_loop_filter'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/vp9_dx_iface.c' l='645' u='r' c='ctrl_set_skip_loop_filter'/>
<offset>1984</offset>
