<def f='webkit/Source/WebCore/dom/StaticRange.h' l='44' ll='49'/>
<use f='webkit/Source/WebCore/dom/StaticRange.h' l='51' c='_ZN7WebCore11StaticRange6createEONS0_4InitE'/>
<size>32</size>
<mbr r='WebCore::StaticRange::Init::startContainer' o='0' t='RefPtr&lt;WebCore::Node&gt;'/>
<mbr r='WebCore::StaticRange::Init::startOffset' o='64' t='unsigned int'/>
<mbr r='WebCore::StaticRange::Init::endContainer' o='128' t='RefPtr&lt;WebCore::Node&gt;'/>
<mbr r='WebCore::StaticRange::Init::endOffset' o='192' t='unsigned int'/>
<def f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/StaticRange.h' l='44' ll='49'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/StaticRange.h' l='51' c='_ZN7WebCore11StaticRange6createEONS0_4InitE'/>
<size>32</size>
<mbr r='WebCore::StaticRange::Init::startContainer' o='0' t='RefPtr&lt;WebCore::Node&gt;'/>
<mbr r='WebCore::StaticRange::Init::startOffset' o='64' t='unsigned int'/>
<mbr r='WebCore::StaticRange::Init::endContainer' o='128' t='RefPtr&lt;WebCore::Node&gt;'/>
<mbr r='WebCore::StaticRange::Init::endOffset' o='192' t='unsigned int'/>
<use f='webkit/Source/WebCore/dom/StaticRange.cpp' l='70' c='_ZN7WebCore11StaticRange6createEONS0_4InitE'/>
<size>32</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSStaticRange.h' l='84' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSStaticRange.h' l='84' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSStaticRange.cpp' l='49' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSStaticRange.cpp' l='49' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSStaticRange.cpp' l='59' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSStaticRange.cpp' l='168' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>32</size>
