<def f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='218' type='const WebCore::GLfloatColor'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='320' u='r' c='_ZN7WebCoreL43YCbCrToRGBMatrixForRangeAndTransferFunctionENS_10PixelRangeENS_18TransferFunctionCVE'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='329' u='r' c='_ZN7WebCoreL43YCbCrToRGBMatrixForRangeAndTransferFunctionENS_10PixelRangeENS_18TransferFunctionCVE'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='343' u='r' c='_ZN7WebCoreL43YCbCrToRGBMatrixForRangeAndTransferFunctionENS_10PixelRangeENS_18TransferFunctionCVE'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='352' u='r' c='_ZN7WebCoreL43YCbCrToRGBMatrixForRangeAndTransferFunctionENS_10PixelRangeENS_18TransferFunctionCVE'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='366' u='r' c='_ZN7WebCoreL43YCbCrToRGBMatrixForRangeAndTransferFunctionENS_10PixelRangeENS_18TransferFunctionCVE'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='375' u='r' c='_ZN7WebCoreL43YCbCrToRGBMatrixForRangeAndTransferFunctionENS_10PixelRangeENS_18TransferFunctionCVE'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='389' u='r' c='_ZN7WebCoreL43YCbCrToRGBMatrixForRangeAndTransferFunctionENS_10PixelRangeENS_18TransferFunctionCVE'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='398' u='r' c='_ZN7WebCoreL43YCbCrToRGBMatrixForRangeAndTransferFunctionENS_10PixelRangeENS_18TransferFunctionCVE'/>
