<dec f='webkit/Source/WebCore/rendering/style/RenderStyleConstants.h' l='868' type='12'/>
<doc f='webkit/Source/WebCore/rendering/style/RenderStyleConstants.h' l='867'>// Copy</doc>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/RenderStyleConstants.h' l='868' type='12'/>
<doc f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/RenderStyleConstants.h' l='867'>// Copy</doc>
<use f='webkit/Source/WebCore/css/CSSPrimitiveValueMappings.h' l='1215' c='_ZN7WebCore17CSSPrimitiveValueC1ET_'/>
<use f='webkit/Source/WebCore/page/EventHandler.cpp' l='1558' c='_ZN7WebCore12EventHandler12selectCursorERKNS_13HitTestResultEb'/>
<use f='webkit/Source/WebCore/rendering/style/RenderStyleConstants.cpp' l='394' c='_ZN7WebCorelsERN3WTF10TextStreamENS_10CursorTypeE'/>
