<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/mediastream/RTCDTMFToneChangeEvent.h' l='42' ll='44'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCDTMFToneChangeEvent.h' l='46' c='_ZN7WebCore22RTCDTMFToneChangeEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCDTMFToneChangeEvent.h' l='54' c='_ZN7WebCore22RTCDTMFToneChangeEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDTMFToneChangeEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDTMFToneChangeEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDTMFToneChangeEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDTMFToneChangeEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDTMFToneChangeEvent.cpp' l='65' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCDTMFToneChangeEvent.cpp' l='171' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<mbr r='WebCore::RTCDTMFToneChangeEvent::Init::tone' o='64' t='WTF::String'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCDTMFToneChangeEvent.cpp' l='43' c='_ZN7WebCore22RTCDTMFToneChangeEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCDTMFToneChangeEvent.cpp' l='54' c='_ZN7WebCore22RTCDTMFToneChangeEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
