<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/mediastream/OverconstrainedErrorEvent.h' l='49' ll='51'/>
<use f='webkit/Source/WebCore/Modules/mediastream/OverconstrainedErrorEvent.h' l='53' c='_ZN7WebCore25OverconstrainedErrorEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediastream/OverconstrainedErrorEvent.h' l='67' c='_ZN7WebCore25OverconstrainedErrorEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSOverconstrainedErrorEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSOverconstrainedErrorEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSOverconstrainedErrorEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSOverconstrainedErrorEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSOverconstrainedErrorEvent.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSOverconstrainedErrorEvent.cpp' l='171' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<mbr r='WebCore::OverconstrainedErrorEvent::Init::error' o='64' t='RefPtr&lt;WebCore::OverconstrainedError&gt;'/>
