<use f='webkit/Source/WebCore/platform/network/cocoa/RangeResponseGenerator.mm' l='46' u='w' c='_ZN7WebCore22RangeResponseGenerator4DataC1ERKNS_16ResourceResponseERNS_21PlatformMediaResourceE'/>
<dec f='webkit/Source/WebCore/platform/network/cocoa/RangeResponseGenerator.mm' l='63' type='RefPtr&lt;WebCore::PlatformMediaResource&gt;'/>
<use f='webkit/Source/WebCore/platform/network/cocoa/RangeResponseGenerator.mm' l='273' u='w' c='_ZN7WebCore22RangeResponseGenerator19MediaResourceClient12loadFinishedERNS_21PlatformMediaResourceERKNS_18NetworkLoadMetricsE'/>
<offset>2304</offset>
