<dec f='webkit/Source/WebCore/Modules/webgpu/WebGPUBindGroupBinding.h' l='41' type='WebCore::WebGPUBindingResource'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSWebGPUBindGroupBinding.cpp' l='75' u='w' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<offset>64</offset>
<use f='webkit/Source/WebCore/Modules/webgpu/WebGPUBindGroupDescriptor.cpp' l='120' u='r' c='_ZNK7WebCore25WebGPUBindGroupDescriptor31tryCreateGPUBindGroupDescriptorEv'/>
