<def f='webkit/Source/WebCore/page/PageSerializer.h' l='54' ll='58'/>
<use f='webkit/Source/WebCore/page/PageSerializer.h' l='60' c='_ZN7WebCore14PageSerializerC1ERN3WTF6VectorINS0_8ResourceELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='webkit/Source/WebCore/page/PageSerializer.h' l='82'/>
<use f='webkit/Source/WebCore/page/PageSerializer.cpp' l='164' c='_ZN7WebCore14PageSerializerC1ERN3WTF6VectorINS0_8ResourceELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<size>56</size>
<mbr r='WebCore::PageSerializer::Resource::url' o='0' t='WTF::URL'/>
<mbr r='WebCore::PageSerializer::Resource::mimeType' o='320' t='WTF::String'/>
<mbr r='WebCore::PageSerializer::Resource::data' o='384' t='RefPtr&lt;WebCore::SharedBuffer&gt;'/>
