<dec f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.h' l='117' type='69'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='176' c='_ZN7WebCore5WHLSL5Token8typeNameENS1_4TypeE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLLexer.cpp' l='1510' u='r' c='_ZN7WebCore5WHLSL5Lexer22consumeTokenFromStreamEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='462' u='m' c='_ZN7WebCore5WHLSL6Parser26parseTypeSuffixAbbreviatedEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='480' u='m' c='_ZN7WebCore5WHLSL6Parser29parseTypeSuffixNonAbbreviatedEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='549' c='_ZN7WebCore5WHLSL6Parser9parseTypeEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='564' u='r' c='_ZN7WebCore5WHLSL6Parser9parseTypeEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='580' c='_ZN7WebCore5WHLSL6Parser9parseTypeEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='592' u='r' c='_ZN7WebCore5WHLSL6Parser9parseTypeEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1355' c='_ZN7WebCore5WHLSL6Parser14parseStatementEv'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1863' u='m' c='_ZN7WebCore5WHLSL6Parser24completePossibleMultiplyEON3WTF9UniqueRefINS0_3AST10ExpressionEEE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1875' c='_ZN7WebCore5WHLSL6Parser24completePossibleMultiplyEON3WTF9UniqueRefINS0_3AST10ExpressionEEE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1905' u='m' c='_ZN7WebCore5WHLSL6Parser19parsePossiblePrefixEPb'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLParser.cpp' l='1957' u='r' c='_ZN7WebCore5WHLSL6Parser19parsePossiblePrefixEPb'/>
