<dec f='webkit/Source/WebCore/dom/FocusOptions.h' l='35' type='1'/>
<use f='webkit/Source/WebCore/dom/Document.h' l='761' u='r' c='_ZNK7WebCore8Document19wasLastFocusByClickEv'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/FocusOptions.h' l='35' type='1'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/Document.h' l='761' u='r' c='_ZNK7WebCore8Document19wasLastFocusByClickEv'/>
<use f='webkit/Source/WebCore/page/EventHandler.cpp' l='2758' u='r' c='_ZN7WebCore12EventHandler18dispatchMouseEventERKN3WTF10AtomStringEPNS_4NodeEiRKNS_18PlatformMouseEventENS0_16FireMouseOverOutE'/>
