<dec f='webkit/Source/WebCore/loader/FetchOptions.h' l='39' type='19'/>
<use f='webkit/Source/WebCore/loader/FetchOptions.h' l='127'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/FetchOptions.h' l='39' type='19'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/FetchOptions.h' l='127'/>
<use f='webkit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='816' u='r' c='_ZN7WebCoreL18destinationForTypeENS_14CachedResource4TypeE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSFetchRequest.cpp' l='119' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_12FetchOptions11DestinationE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSFetchRequest.cpp' l='171' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/Source/WebKit/NetworkProcess/NetworkLoadChecker.cpp' l='286' c='_ZN6WebKit18NetworkLoadChecker32isAllowedByContentSecurityPolicyERKN7WebCore15ResourceRequestEPNS1_27ContentSecurityPolicyClientE'/>
<use f='webkit/Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp' l='423' c='_ZN6WebKit21NetworkResourceLoader16resourceLoadInfoEv'/>
