<def f='webkit/Source/WebCore/Modules/fetch/FetchResponse.h' l='54' ll='58'/>
<use f='webkit/Source/WebCore/Modules/fetch/FetchResponse.h' l='62' c='_ZN7WebCore13FetchResponse6createERNS_22ScriptExecutionContextEONSt3__18optionalIN3WTF7VariantIJNS5_6RefPtrINS_4BlobENS5_12RawPtrTraitsIS8_EENS5_21Def12901240'/>
<size>48</size>
<mbr r='WebCore::FetchResponse::Init::status' o='0' t='unsigned short'/>
<mbr r='WebCore::FetchResponse::Init::statusText' o='64' t='WTF::String'/>
<mbr r='WebCore::FetchResponse::Init::headers' o='128' t='std::optional&lt;FetchHeaders::Init&gt;'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSFetchResponse.h' l='100' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSFetchResponse.h' l='100' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>48</size>
<use f='webkit/Source/WebCore/Modules/fetch/FetchResponse.cpp' l='66' c='_ZN7WebCore13FetchResponse6createERNS_22ScriptExecutionContextEONSt3__18optionalIN3WTF7VariantIJNS5_6RefPtrINS_4BlobENS5_12RawPtrTraitsIS8_EENS5_21Def12901240'/>
<size>48</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSFetchResponse.cpp' l='121' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSFetchResponse.cpp' l='121' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSFetchResponse.cpp' l='131' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSFetchResponse.cpp' l='243' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>48</size>
