<dec f='webkit/Source/WebCore/page/DragActions.h' l='83' type='16'/>
<use f='webkit/Source/WebCore/page/DragActions.h' l='89' u='r' c='_ZN7WebCore16anyDragOperationEv'/>
<use f='webkit/Source/WebCore/page/DragActions.h' l='129'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/DragActions.h' l='83' type='16'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/DragActions.h' l='89' u='r' c='_ZN7WebCore16anyDragOperationEv'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/DragActions.h' l='129'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='622' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='626' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='628' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='636' u='r' c='_ZN7WebCoreL14IEOpFromDragOpEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='638' u='r' c='_ZN7WebCoreL14IEOpFromDragOpEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='665' u='r' c='_ZNK7WebCore12DataTransfer24destinationOperationMaskEv'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='665' u='r' c='_ZNK7WebCore12DataTransfer24destinationOperationMaskEv'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='677' u='r' c='_ZN7WebCore12DataTransfer27setDestinationOperationMaskEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='webkit/Source/WebCore/dom/DataTransfer.cpp' l='677' u='r' c='_ZN7WebCore12DataTransfer27setDestinationOperationMaskEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='webkit/Source/WebCore/page/DragController.cpp' l='187' u='r' c='_ZN7WebCore14DragController28platformGenericDragOperationEv'/>
<use f='webkit/Source/WebCore/page/DragController.cpp' l='450' u='a' c='_ZN7WebCore14DragController15tryDocumentDragERKNS_8DragDataEN3WTF9OptionSetINS_21DragDestinationActionEEERNSt3__18optionalINS_13DragOperationEEE'/>
<use f='webkit/Source/WebCore/page/DragController.cpp' l='700' u='r' c='_ZN7WebCoreL23defaultOperationForDragEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='webkit/Source/WebCore/page/DragController.cpp' l='704' u='r' c='_ZN7WebCoreL23defaultOperationForDragEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='webkit/Source/WebCore/page/DragController.cpp' l='705' u='a' c='_ZN7WebCoreL23defaultOperationForDragEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='webkit/Source/WebCore/page/EventHandler.cpp' l='2303' u='a' c='_ZN7WebCoreL39convertDropZoneOperationToDragOperationERKN3WTF6StringE'/>
<use f='webkit/Source/WebCore/page/EventHandler.cpp' l='2313' c='_ZN7WebCoreL39convertDragOperationToDropZoneOperationENSt3__18optionalINS_13DragOperationEEE'/>
<use f='webkit/Source/WebKit/Shared/API/Cocoa/_WKDragActionsInternal.h' l='56' u='r' c='_ZN6WebKit21coreDragOperationMaskEm'/>
<use f='webkit/Source/WebKit/UIProcess/Cocoa/WebViewImpl.mm' l='4202' c='_ZN6WebKitL3kitENSt3__18optionalIN7WebCore13DragOperationEEE'/>
<use f='webkit/Source/WebKitLegacy/mac/WebView/WebHTMLView.mm' l='4266' u='r' c='_ZL3kitN3WTF9OptionSetIN7WebCore13DragOperationEEE'/>
<use f='webkit/Source/WebKitLegacy/mac/WebView/WebView.mm' l='631' u='r' c='_Z21coreDragOperationMaskm'/>
<use f='webkit/Source/WebKitLegacy/mac/WebView/WebView.mm' l='659' c='_ZL3kitNSt3__18optionalIN7WebCore13DragOperationEEE'/>
