<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/webxr/XRInputSourcesChangeEvent.h' l='42' ll='46'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRInputSourcesChangeEvent.h' l='48' c='_ZN7WebCore25XRInputSourcesChangeEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRInputSourcesChangeEvent.h' l='58' c='_ZN7WebCore25XRInputSourcesChangeEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/WebXRInputSourceArray.cpp' l='90' c='_ZN7WebCore21WebXRInputSourceArray6updateEdRKN3WTF6VectorIN10PlatformXR6Device9FrameData11InputSourceELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<size>48</size>
<mbr r='WebCore::XRInputSourcesChangeEvent::Init::session' o='64' t='RefPtr&lt;WebCore::WebXRSession&gt;'/>
<mbr r='WebCore::XRInputSourcesChangeEvent::Init::added' o='128' t='Vector&lt;RefPtr&lt;WebCore::WebXRInputSource&gt;&gt;'/>
<mbr r='WebCore::XRInputSourcesChangeEvent::Init::removed' o='256' t='Vector&lt;RefPtr&lt;WebCore::WebXRInputSource&gt;&gt;'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRInputSourcesChangeEvent.cpp' l='39' c='_ZN7WebCore25XRInputSourcesChangeEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRInputSourcesChangeEvent.cpp' l='44' c='_ZN7WebCore25XRInputSourcesChangeEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>48</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourcesChangeEvent.h' l='87' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourcesChangeEvent.h' l='87' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourcesChangeEvent.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourcesChangeEvent.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourcesChangeEvent.cpp' l='70' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourcesChangeEvent.cpp' l='209' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>48</size>
