<def f='webkit/Source/WebCore/page/PerformanceObserver.h' l='43' ll='47'/>
<use f='webkit/Source/WebCore/page/PerformanceObserver.h' l='58' c='_ZN7WebCore19PerformanceObserver7observeEONS0_4InitE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPerformanceObserver.h' l='97' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPerformanceObserver.h' l='97' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPerformanceObserver.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPerformanceObserver.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPerformanceObserver.cpp' l='70' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPerformanceObserver.cpp' l='311' c='_ZN7WebCoreL50jsPerformanceObserverPrototypeFunction_observeBodyEPN3JSC14JSGlobalObjectEPNS0_9CallFrameEPNS_21JSPerformanceObserverE'/>
<size>48</size>
<mbr r='WebCore::PerformanceObserver::Init::entryTypes' o='0' t='std::optional&lt;Vector&lt;String&gt;&gt;'/>
<mbr r='WebCore::PerformanceObserver::Init::type' o='192' t='std::optional&lt;String&gt;'/>
<mbr r='WebCore::PerformanceObserver::Init::buffered' o='320' t='bool'/>
<use f='webkit/Source/WebCore/page/PerformanceObserver.cpp' l='59' c='_ZN7WebCore19PerformanceObserver7observeEONS0_4InitE'/>
<size>48</size>
