<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/paymentrequest/MerchantValidationEvent.h' l='41' ll='44'/>
<use f='webkit/Source/WebCore/Modules/paymentrequest/MerchantValidationEvent.h' l='47' c='_ZN7WebCore23MerchantValidationEvent6createERNS_8DocumentERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='webkit/Source/WebCore/Modules/paymentrequest/MerchantValidationEvent.h' l='55' c='_ZN7WebCore23MerchantValidationEventC1ERKN3WTF10AtomStringEONS1_6StringEONS1_3URLEONS0_4InitE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMerchantValidationEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMerchantValidationEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMerchantValidationEvent.cpp' l='62' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMerchantValidationEvent.cpp' l='62' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMerchantValidationEvent.cpp' l='72' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMerchantValidationEvent.cpp' l='201' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
<mbr r='WebCore::MerchantValidationEvent::Init::methodName' o='64' t='WTF::String'/>
<mbr r='WebCore::MerchantValidationEvent::Init::validationURL' o='128' t='WTF::String'/>
<use f='webkit/Source/WebCore/Modules/paymentrequest/MerchantValidationEvent.cpp' l='44' c='_ZN7WebCore23MerchantValidationEvent6createERNS_8DocumentERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='webkit/Source/WebCore/Modules/paymentrequest/MerchantValidationEvent.cpp' l='69' c='_ZN7WebCore23MerchantValidationEventC1ERKN3WTF10AtomStringEONS1_6StringEONS1_3URLEONS0_4InitE'/>
<size>24</size>
