<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/mediarecorder/BlobEvent.h' l='38' ll='41'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/BlobEvent.h' l='43' c='_ZN7WebCore9BlobEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/BlobEvent.h' l='49' c='_ZN7WebCore9BlobEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBlobEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBlobEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>24</size>
<mbr r='WebCore::BlobEvent::Init::data' o='64' t='RefPtr&lt;WebCore::Blob&gt;'/>
<mbr r='WebCore::BlobEvent::Init::timecode' o='128' t='double'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/BlobEvent.cpp' l='38' c='_ZN7WebCore9BlobEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/BlobEvent.cpp' l='43' c='_ZN7WebCore9BlobEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/MediaRecorder.cpp' l='202' c='_ZN7WebCoreL24createDataAvailableEventEPNS_22ScriptExecutionContextEON3WTF6RefPtrINS_12SharedBufferENS2_12RawPtrTraitsIS4_EENS2_21DefaultRefDerefTrait10081154'/>
<size>24</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBlobEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBlobEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBlobEvent.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBlobEvent.cpp' l='185' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
