<dec f='webkit/Source/WebCore/accessibility/AccessibilityObjectInterface.h' l='572' type='10'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/AccessibilityObjectInterface.h' l='572' type='10'/>
<use f='webkit/Source/WebCore/accessibility/mac/AccessibilityObjectBase.mm' l='69' c='_ZN7WebCoreL13isVisibleTextENS_23AccessibilityTextSourceE'/>
<use f='webkit/Source/WebCore/accessibility/mac/AccessibilityObjectBase.mm' l='88' c='_ZN7WebCoreL17isDescriptiveTextENS_23AccessibilityTextSourceE'/>
<use f='webkit/Source/WebCore/accessibility/mac/AccessibilityObjectBase.mm' l='123' c='_ZNK7WebCore19AccessibilityObject25descriptionAttributeValueEv'/>
<use f='webkit/Source/WebCore/accessibility/AccessibilityAttachment.cpp' l='98' u='r' c='_ZNK7WebCore23AccessibilityAttachment17accessibilityTextERN3WTF6VectorINS_17AccessibilityTextELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
