<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/mediastream/RTCPeerConnectionIceEvent.h' l='40' ll='43'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCPeerConnectionIceEvent.h' l='45' c='_ZN7WebCore25RTCPeerConnectionIceEvent6createERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceEvent.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCPeerConnectionIceEvent.cpp' l='182' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
<mbr r='WebCore::RTCPeerConnectionIceEvent::Init::candidate' o='64' t='RefPtr&lt;WebCore::RTCIceCandidate&gt;'/>
<mbr r='WebCore::RTCPeerConnectionIceEvent::Init::url' o='128' t='WTF::String'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCPeerConnectionIceEvent.cpp' l='43' c='_ZN7WebCore25RTCPeerConnectionIceEvent6createERKN3WTF10AtomStringEONS0_4InitE'/>
<size>24</size>
