<dec f='webkit/Source/WebCore/Modules/webgpu/GPUShaderStage.h' l='42' type='4'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUBindGroupLayoutMetal.mm' l='157' u='r' c='_ZN7WebCore18GPUBindGroupLayout9tryCreateERKNS_9GPUDeviceERKNS_28GPUBindGroupLayoutDescriptorE'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUBindGroupMetal.mm' l='163' u='r' c='_ZN7WebCore12GPUBindGroup9tryCreateERKNS_22GPUBindGroupDescriptorERNS_21GPUBindGroupAllocatorE'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUPipelineMetalConvertLayout.cpp' l='43' u='r' c='_ZN7WebCoreL23convertShaderStageFlagsEj'/>
