<def f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.h' l='559' type='const GCGLenum'/>
<def f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/GraphicsContextGL.h' l='559' type='const GCGLenum'/>
<use f='webkit/Source/WebCore/html/canvas/WebGL2RenderingContext.cpp' l='3150' u='r' c='_ZN7WebCore22WebGL2RenderingContext36baseInternalFormatFromInternalFormatEj'/>
<use f='webkit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='411'/>
<use f='webkit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5508' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='53' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='89' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='187' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='218' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='webkit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='579' u='r' c='_ZN7WebCore17GraphicsContextGL30computeFormatAndTypeParametersEjjPjS1_'/>
<use f='webkit/Source/WebCore/platform/graphics/cv/GraphicsContextGLCVANGLE.cpp' l='640' u='r' c='_ZN7WebCore24GraphicsContextGLCVANGLE24copyPixelBufferToTextureEP10__CVBufferjijjjNS_17GraphicsContextGL5FlipYE'/>
