<dec f='webkit/Source/WebCore/testing/MockWebAuthenticationConfiguration.h' l='43' type='1'/>
<use f='webkit/Source/WebCore/testing/MockWebAuthenticationConfiguration.h' l='279'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMockWebAuthenticationConfiguration.cpp' l='147' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_34MockWebAuthenticationConfiguration11HidSubStageE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMockWebAuthenticationConfiguration.cpp' l='163' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/MockWebAuthenticationConfiguration.h' l='43' type='1'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/MockWebAuthenticationConfiguration.h' l='279'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.cpp' l='140' u='r' c='_ZN6WebKit17MockHidConnection12parseRequestEv'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.cpp' l='144' u='r' c='_ZN6WebKit17MockHidConnection12parseRequestEv'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.cpp' l='146' u='r' c='_ZN6WebKit17MockHidConnection12parseRequestEv'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.cpp' l='226' u='r' c='_ZN6WebKit17MockHidConnection11feedReportsEv'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Mock/MockHidConnection.cpp' l='251' u='r' c='_ZN6WebKit17MockHidConnection11feedReportsEv'/>
