<inh f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/EventModifierInit.h' l='32' c='WebCore::EventModifierInit'/>
<def f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/KeyboardEvent.h' l='50' ll='63'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/KeyboardEvent.h' l='65' c='_ZN7WebCore13KeyboardEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/KeyboardEvent.h' l='100' c='_ZN7WebCore13KeyboardEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>88</size>
<mbr r='WebCore::KeyboardEvent::Init::key' o='256' t='WTF::String'/>
<mbr r='WebCore::KeyboardEvent::Init::code' o='320' t='WTF::String'/>
<mbr r='WebCore::KeyboardEvent::Init::location' o='384' t='unsigned int'/>
<mbr r='WebCore::KeyboardEvent::Init::repeat' o='416' t='bool'/>
<mbr r='WebCore::KeyboardEvent::Init::isComposing' o='424' t='bool'/>
<mbr r='WebCore::KeyboardEvent::Init::keyIdentifier' o='448' t='WTF::String'/>
<mbr r='WebCore::KeyboardEvent::Init::keyLocation' o='512' t='std::optional&lt;unsigned int&gt;'/>
<mbr r='WebCore::KeyboardEvent::Init::charCode' o='576' t='unsigned int'/>
<mbr r='WebCore::KeyboardEvent::Init::keyCode' o='608' t='unsigned int'/>
<mbr r='WebCore::KeyboardEvent::Init::which' o='640' t='unsigned int'/>
<inh f='webkit/Source/WebCore/dom/EventModifierInit.h' l='32' c='WebCore::EventModifierInit'/>
<def f='webkit/Source/WebCore/dom/KeyboardEvent.h' l='50' ll='63'/>
<use f='webkit/Source/WebCore/dom/KeyboardEvent.h' l='65' c='_ZN7WebCore13KeyboardEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/dom/KeyboardEvent.h' l='100' c='_ZN7WebCore13KeyboardEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSKeyboardEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSKeyboardEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSKeyboardEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSKeyboardEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSKeyboardEvent.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSKeyboardEvent.cpp' l='393' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>88</size>
<mbr r='WebCore::KeyboardEvent::Init::key' o='256' t='WTF::String'/>
<mbr r='WebCore::KeyboardEvent::Init::code' o='320' t='WTF::String'/>
<mbr r='WebCore::KeyboardEvent::Init::location' o='384' t='unsigned int'/>
<mbr r='WebCore::KeyboardEvent::Init::repeat' o='416' t='bool'/>
<mbr r='WebCore::KeyboardEvent::Init::isComposing' o='424' t='bool'/>
<mbr r='WebCore::KeyboardEvent::Init::keyIdentifier' o='448' t='WTF::String'/>
<mbr r='WebCore::KeyboardEvent::Init::keyLocation' o='512' t='std::optional&lt;unsigned int&gt;'/>
<mbr r='WebCore::KeyboardEvent::Init::charCode' o='576' t='unsigned int'/>
<mbr r='WebCore::KeyboardEvent::Init::keyCode' o='608' t='unsigned int'/>
<mbr r='WebCore::KeyboardEvent::Init::which' o='640' t='unsigned int'/>
<use f='webkit/Source/WebCore/dom/KeyboardEvent.cpp' l='124' c='_ZN7WebCore13KeyboardEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/dom/KeyboardEvent.cpp' l='150' c='_ZN7WebCore13KeyboardEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>88</size>
<use f='webkit/Source/WebCore/accessibility/AccessibilityNodeObject.cpp' l='1099' c='_ZN7WebCoreL36dispatchSimulatedKeyboardUpDownEventEPNS_19AccessibilityObjectERKNS_13KeyboardEvent4InitE'/>
<use f='webkit/Source/WebCore/accessibility/AccessibilityNodeObject.cpp' l='1120' c='_ZN7WebCoreL33InitializeLegacyKeyInitPropertiesERNS_13KeyboardEvent4InitERKNS_19AccessibilityObjectE'/>
<use f='webkit/Source/WebCore/accessibility/AccessibilityNodeObject.cpp' l='1133' c='_ZN7WebCore23AccessibilityNodeObject20performDismissActionEv'/>
<use f='webkit/Source/WebCore/accessibility/AccessibilityNodeObject.cpp' l='1145' c='_ZN7WebCore23AccessibilityNodeObject30postKeyboardKeysForValueChangeEb'/>
<size>88</size>
