<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/pictureinpicture/EnterPictureInPictureEvent.h' l='40' ll='42'/>
<use f='webkit/Source/WebCore/Modules/pictureinpicture/EnterPictureInPictureEvent.h' l='44' c='_ZN7WebCore26EnterPictureInPictureEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/pictureinpicture/EnterPictureInPictureEvent.h' l='51' c='_ZN7WebCore26EnterPictureInPictureEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEnterPictureInPictureEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEnterPictureInPictureEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>16</size>
<mbr r='WebCore::EnterPictureInPictureEvent::Init::pictureInPictureWindow' o='64' t='RefPtr&lt;WebCore::PictureInPictureWindow&gt;'/>
<use f='webkit/Source/WebCore/Modules/pictureinpicture/EnterPictureInPictureEvent.cpp' l='39' c='_ZN7WebCore26EnterPictureInPictureEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/pictureinpicture/EnterPictureInPictureEvent.cpp' l='44' c='_ZN7WebCore26EnterPictureInPictureEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
<use f='webkit/Source/WebCore/Modules/pictureinpicture/HTMLVideoElementPictureInPicture.cpp' l='161' c='_ZN7WebCore32HTMLVideoElementPictureInPicture24didEnterPictureInPictureERKNS_7IntSizeE'/>
<size>16</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEnterPictureInPictureEvent.cpp' l='57' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEnterPictureInPictureEvent.cpp' l='57' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEnterPictureInPictureEvent.cpp' l='67' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSEnterPictureInPictureEvent.cpp' l='176' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
