<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/mediastream/RTCTrackEvent.h' l='52' ll='57'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCTrackEvent.h' l='58' c='_ZN7WebCore13RTCTrackEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCTrackEvent.h' l='69' c='_ZN7WebCore13RTCTrackEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCTrackEvent.h' l='84' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCTrackEvent.h' l='84' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCTrackEvent.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCTrackEvent.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCTrackEvent.cpp' l='70' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSRTCTrackEvent.cpp' l='220' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>48</size>
<mbr r='WebCore::RTCTrackEvent::Init::receiver' o='64' t='RefPtr&lt;WebCore::RTCRtpReceiver&gt;'/>
<mbr r='WebCore::RTCTrackEvent::Init::track' o='128' t='RefPtr&lt;WebCore::MediaStreamTrack&gt;'/>
<mbr r='WebCore::RTCTrackEvent::Init::streams' o='192' t='WebCore::MediaStreamArray'/>
<mbr r='WebCore::RTCTrackEvent::Init::transceiver' o='320' t='RefPtr&lt;WebCore::RTCRtpTransceiver&gt;'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCTrackEvent.cpp' l='50' c='_ZN7WebCore13RTCTrackEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediastream/RTCTrackEvent.cpp' l='64' c='_ZN7WebCore13RTCTrackEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>48</size>
