<dec f='webkit/Source/WebCore/Modules/webauthn/PublicKeyCredentialCreationOptions.h' l='61' type='int64_t'/>
<use f='webkit/Source/WebCore/Modules/webauthn/PublicKeyCredentialCreationOptions.h' l='97' c='_ZNK7WebCore34PublicKeyCredentialCreationOptions10Parameters6encodeERT_'/>
<use f='webkit/Source/WebCore/Modules/webauthn/PublicKeyCredentialCreationOptions.h' l='106' c='_ZN7WebCore34PublicKeyCredentialCreationOptions10Parameters6decodeERT_'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPublicKeyCredentialCreationOptions.cpp' l='368' u='w' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<offset>64</offset>
<use f='webkit/Source/WebCore/Modules/webauthn/fido/DeviceRequestConverter.cpp' l='76' u='r' c='_ZN4fidoL23convertParametersToCBORERKN3WTF6VectorIN7WebCore34PublicKeyCredentialCreationOptions10ParametersELm0ENS0_15CrashOnOverflowELm16ENS0_10FastMallocEEE'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/PublicKeyCredentialCreationOptions.h' l='61' type='int64_t'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/PublicKeyCredentialCreationOptions.h' l='97' c='_ZNK7WebCore34PublicKeyCredentialCreationOptions10Parameters6encodeERT_'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/PublicKeyCredentialCreationOptions.h' l='106' c='_ZN7WebCore34PublicKeyCredentialCreationOptions10Parameters6decodeERT_'/>
<offset>64</offset>
