<dec f='webkit/Source/WebCore/platform/Cursor.h' l='115' type='29'/>
<use f='webkit/Source/WebCore/platform/Cursor.h' l='267'/>
<use f='webkit/Source/WebCore/platform/mac/CursorMac.mm' l='266' c='_ZNK7WebCore6Cursor20ensurePlatformCursorEv'/>
<use f='webkit/Source/WebCore/testing/Internals.cpp' l='3730' c='_ZN7WebCoreL18cursorTypeToStringENS_6Cursor4TypeE'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/Cursor.h' l='115' type='29'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/Cursor.h' l='267'/>
<use f='webkit/Source/WebCore/platform/Cursor.cpp' l='117' c='_ZN7WebCore6Cursor8fromTypeENS0_4TypeE'/>
<use f='webkit/Source/WebCore/platform/Cursor.cpp' l='203' u='a' c='_ZN7WebCore10moveCursorEv'/>
