<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/webxr/XRInputSourceEvent.h' l='41' ll='44'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRInputSourceEvent.h' l='46' c='_ZN7WebCore18XRInputSourceEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRInputSourceEvent.h' l='56' c='_ZN7WebCore18XRInputSourceEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/WebXRInputSource.cpp' l='114' c='_ZN7WebCore16WebXRInputSource10pollEventsERN3WTF6VectorINS1_3RefINS_18XRInputSourceEventENS1_12RawPtrTraitsIS4_EEEELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<size>24</size>
<mbr r='WebCore::XRInputSourceEvent::Init::frame' o='64' t='RefPtr&lt;WebCore::WebXRFrame&gt;'/>
<mbr r='WebCore::XRInputSourceEvent::Init::inputSource' o='128' t='RefPtr&lt;WebCore::WebXRInputSource&gt;'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRInputSourceEvent.cpp' l='39' c='_ZN7WebCore18XRInputSourceEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/webxr/XRInputSourceEvent.cpp' l='44' c='_ZN7WebCore18XRInputSourceEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>24</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourceEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourceEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourceEvent.cpp' l='58' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourceEvent.cpp' l='58' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourceEvent.cpp' l='68' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSXRInputSourceEvent.cpp' l='192' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
