<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/dom/BeforeLoadEvent.h' l='42' ll='44'/>
<use f='webkit/Source/WebCore/dom/BeforeLoadEvent.h' l='46' c='_ZN7WebCore15BeforeLoadEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/dom/BeforeLoadEvent.h' l='62' c='_ZN7WebCore15BeforeLoadEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
<mbr r='WebCore::BeforeLoadEvent::Init::url' o='64' t='WTF::String'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBeforeLoadEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBeforeLoadEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>16</size>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBeforeLoadEvent.cpp' l='50' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBeforeLoadEvent.cpp' l='50' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBeforeLoadEvent.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSBeforeLoadEvent.cpp' l='165' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
