<def f='webkit/Source/WebCore/layout/integration/LayoutIntegrationRun.h' l='41' ll='98'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationInlineContent.h' l='53'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationInlineContent.h' l='62' c='_ZNK7WebCore17LayoutIntegration13InlineContent10lineForRunERKNS0_3RunE'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationInlineContent.h' l='63' c='_ZNK7WebCore17LayoutIntegration13InlineContent11runsForRectERKNS_10LayoutRectE'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationRunIteratorModernPath.h' l='240' c='_ZNK7WebCore17LayoutIntegration21RunIteratorModernPath3runEv'/>
<size>128</size>
<fun r='_ZN7WebCore17LayoutIntegration3RunC1EmRKNS_6Layout3BoxERKNS_9FloatRectES8_NS1_9ExpansionENSt3__18optionalINS1_11TextContentEEE'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run4rectEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run11inkOverflowEv'/>
<fun r='_ZN7WebCore17LayoutIntegration3Run11textContentEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run11textContentEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run11isLineBreakEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run9expansionEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run5imageEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run19hasUnderlyingLayoutEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run9layoutBoxEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run5styleEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run9lineIndexEv'/>
<mbr r='WebCore::LayoutIntegration::Run::m_lineIndex' o='0' t='const size_t'/>
<mbr r='WebCore::LayoutIntegration::Run::m_layoutBox' o='64' t='WeakPtr&lt;const Layout::Box&gt;'/>
<mbr r='WebCore::LayoutIntegration::Run::m_cachedImage' o='192' t='WebCore::CachedImage *'/>
<mbr r='WebCore::LayoutIntegration::Run::m_rect' o='256' t='WebCore::FloatRect'/>
<mbr r='WebCore::LayoutIntegration::Run::m_inkOverflow' o='416' t='WebCore::FloatRect'/>
<mbr r='WebCore::LayoutIntegration::Run::m_expansion' o='576' t='WebCore::LayoutIntegration::Run::Expansion'/>
<mbr r='WebCore::LayoutIntegration::Run::m_textContent' o='640' t='std::optional&lt;TextContent&gt;'/>
<fun r='_ZN7WebCore17LayoutIntegration3RunC1EmRKNS_6Layout3BoxERKNS_9FloatRectES8_NS1_9ExpansionENSt3__18optionalINS1_11TextContentEEE'/>
<def f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/LayoutIntegrationRun.h' l='41' ll='98'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/LayoutIntegrationInlineContent.h' l='53'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/LayoutIntegrationInlineContent.h' l='62' c='_ZNK7WebCore17LayoutIntegration13InlineContent10lineForRunERKNS0_3RunE'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/LayoutIntegrationInlineContent.h' l='63' c='_ZNK7WebCore17LayoutIntegration13InlineContent11runsForRectERKNS_10LayoutRectE'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/LayoutIntegrationRunIteratorModernPath.h' l='240' c='_ZNK7WebCore17LayoutIntegration21RunIteratorModernPath3runEv'/>
<size>128</size>
<fun r='_ZN7WebCore17LayoutIntegration3RunC1EmRKNS_6Layout3BoxERKNS_9FloatRectES8_NS1_9ExpansionENSt3__18optionalINS1_11TextContentEEE'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run4rectEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run11inkOverflowEv'/>
<fun r='_ZN7WebCore17LayoutIntegration3Run11textContentEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run11textContentEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run11isLineBreakEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run9expansionEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run5imageEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run19hasUnderlyingLayoutEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run9layoutBoxEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run5styleEv'/>
<fun r='_ZNK7WebCore17LayoutIntegration3Run9lineIndexEv'/>
<mbr r='WebCore::LayoutIntegration::Run::m_lineIndex' o='0' t='const size_t'/>
<mbr r='WebCore::LayoutIntegration::Run::m_layoutBox' o='64' t='WeakPtr&lt;const Layout::Box&gt;'/>
<mbr r='WebCore::LayoutIntegration::Run::m_cachedImage' o='192' t='WebCore::CachedImage *'/>
<mbr r='WebCore::LayoutIntegration::Run::m_rect' o='256' t='WebCore::FloatRect'/>
<mbr r='WebCore::LayoutIntegration::Run::m_inkOverflow' o='416' t='WebCore::FloatRect'/>
<mbr r='WebCore::LayoutIntegration::Run::m_expansion' o='576' t='WebCore::LayoutIntegration::Run::Expansion'/>
<mbr r='WebCore::LayoutIntegration::Run::m_textContent' o='640' t='std::optional&lt;TextContent&gt;'/>
<fun r='_ZN7WebCore17LayoutIntegration3RunC1EmRKNS_6Layout3BoxERKNS_9FloatRectES8_NS1_9ExpansionENSt3__18optionalINS1_11TextContentEEE'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationInlineContent.cpp' l='43' c='_ZNK7WebCore17LayoutIntegration13InlineContent11runsForRectERKNS_10LayoutRectE'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationInlineContentBuilder.cpp' l='310' c='_ZNK7WebCore17LayoutIntegration20InlineContentBuilder21createDisplayLineRunsERKNS_6Layout21InlineFormattingStateERNS0_13InlineContentERKN3WTF6VectorIN5440806'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationPagination.cpp' l='143' c='_ZN7WebCore17LayoutIntegrationL19makeAdjustedContentERKNS0_13InlineContentEN3WTF6VectorIfLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEE'/>
<use f='webkit/Source/WebCore/layout/integration/LayoutIntegrationPagination.cpp' l='145' c='_ZN7WebCore17LayoutIntegrationL19makeAdjustedContentERKNS0_13InlineContentEN3WTF6VectorIfLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEE'/>
<size>128</size>
