<dec f='webkit/Source/WebCore/testing/Internals.h' l='1133' type='0'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInternals.cpp' l='556' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_9Internals19ContentSizeCategoryE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSInternals.cpp' l='571' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
