<inh f='webkit/Source/WebCore/Modules/paymentrequest/PaymentRequestUpdateEventInit.h' l='34' c='WebCore::PaymentRequestUpdateEventInit'/>
<def f='webkit/Source/WebCore/Modules/paymentrequest/PaymentMethodChangeEvent.h' l='60' ll='63'/>
<use f='webkit/Source/WebCore/Modules/paymentrequest/PaymentMethodChangeEvent.h' l='66' c='_ZN7WebCore24PaymentMethodChangeEventC1ERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPaymentMethodChangeEvent.h' l='90' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPaymentMethodChangeEvent.h' l='90' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPaymentMethodChangeEvent.cpp' l='57' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPaymentMethodChangeEvent.cpp' l='57' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPaymentMethodChangeEvent.cpp' l='67' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSPaymentMethodChangeEvent.cpp' l='186' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
<mbr r='WebCore::PaymentMethodChangeEvent::Init::methodName' o='64' t='WTF::String'/>
<mbr r='WebCore::PaymentMethodChangeEvent::Init::methodDetails' o='128' t='JSC::Strong&lt;JSC::JSObject&gt;'/>
<use f='webkit/Source/WebCore/Modules/paymentrequest/PaymentMethodChangeEvent.cpp' l='42' c='_ZN7WebCore24PaymentMethodChangeEventC1ERKN3WTF10AtomStringEONS0_4InitE'/>
<size>24</size>
