<inh f='webkit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='webkit/Source/WebCore/Modules/mediarecorder/MediaRecorderErrorEvent.h' l='37' ll='39'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/MediaRecorderErrorEvent.h' l='41' c='_ZN7WebCore23MediaRecorderErrorEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/MediaRecorderErrorEvent.h' l='47' c='_ZN7WebCore23MediaRecorderErrorEventC1ERKN3WTF10AtomStringEONS0_4InitEONS1_3RefINS_12DOMExceptionENS1_12RawPtrTraitsIS8_EEEENS_5Event9IsTrustedE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaRecorderErrorEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaRecorderErrorEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaRecorderErrorEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaRecorderErrorEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaRecorderErrorEvent.cpp' l='65' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSMediaRecorderErrorEvent.cpp' l='172' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<mbr r='WebCore::MediaRecorderErrorEvent::Init::error' o='64' t='RefPtr&lt;WebCore::DOMException&gt;'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/MediaRecorderErrorEvent.cpp' l='43' c='_ZN7WebCore23MediaRecorderErrorEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='webkit/Source/WebCore/Modules/mediarecorder/MediaRecorderErrorEvent.cpp' l='49' c='_ZN7WebCore23MediaRecorderErrorEventC1ERKN3WTF10AtomStringEONS0_4InitEONS1_3RefINS_12DOMExceptionENS1_12RawPtrTraitsIS8_EEEENS_5Event9IsTrustedE'/>
<size>16</size>
