<dec f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLPipelineDescriptor.h' l='105' type='4'/>
<use f='webkit/Source/WebCore/platform/graphics/gpu/cocoa/GPUPipelineMetalConvertLayout.cpp' l='44' u='r' c='_ZN7WebCoreL23convertShaderStageFlagsEj'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/WHLSLSemanticMatcher.cpp' l='325' u='r' c='_ZN7WebCore5WHLSL14matchSemanticsERNS0_7ProgramERNS0_25ComputePipelineDescriptorE'/>
<use f='webkit/Source/WebCore/Modules/webgpu/WHLSL/Metal/WHLSLEntryPointScaffolding.cpp' l='600' u='r' c='_ZN7WebCore5WHLSL5Metal28ComputeEntryPointScaffolding15emitHelperTypesERN3WTF13StringBuilderENS3_11IndentationILj4EEE'/>
