<dec f='webkit/Source/WebCore/platform/mediacapabilities/TransferFunction.h' l='32' type='1'/>
<use f='webkit/Source/WebCore/platform/mediacapabilities/TransferFunction.h' l='44'/>
<use f='webkit/Source/WebCore/platform/graphics/cocoa/VP9UtilitiesCocoa.mm' l='242' u='r' c='_ZN7WebCore20validateVPParametersERKNS_26VPCodecConfigurationRecordERKNS_18VideoConfigurationE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSTransferFunction.cpp' l='40' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_16TransferFunctionE'/>
<use f='webkit/WebKitBuild/Debug/DerivedSources/WebCore/JSTransferFunction.cpp' l='57' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<dec f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/TransferFunction.h' l='32' type='1'/>
<use f='webkit/WebKitBuild/Debug/WebCore.framework/Versions/A/PrivateHeaders/TransferFunction.h' l='44'/>
