<dec f='webkit/Source/WebKit/UIProcess/WebAuthentication/Cocoa/LocalAuthenticator.h' l='44' type='0'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Cocoa/LocalAuthenticator.h' l='76'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Cocoa/LocalAuthenticator.mm' l='206' u='r' c='_ZN6WebKit18LocalAuthenticator14makeCredentialEv'/>
<use f='webkit/Source/WebKit/UIProcess/WebAuthentication/Cocoa/LocalAuthenticator.mm' l='480' u='r' c='_ZN6WebKit18LocalAuthenticator12getAssertionEv'/>
