<dec f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/rtp_parameters.h' l='49' type='0'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/api/rtp_parameters.h' l='378'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/pc/rtp_parameters_conversion.cc' l='412' u='a' c='_ZN6webrtc17ToRtpCapabilitiesERKNSt3__16vectorIT_NS0_9allocatorIS2_EEEERKNS1_INS_12RtpExtensionENS3_IS8_EEEE'/>
<dec f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/rtp_parameters.h' l='49' type='0'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/api/rtp_parameters.h' l='378'/>
