<def f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/include/module.h' l='20' ll='60'/>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/remote_bitrate_estimator/include/remote_bitrate_estimator.h' l='44' c='webrtc::RemoteBitrateEstimator'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/remote_bitrate_estimator/include/remote_bitrate_estimator.h' l='44'/>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtp_rtcp_impl2.h' l='50' c='webrtc::ModuleRtpRtcpImpl2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtp_rtcp_impl2.h' l='51'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/include/process_thread.h' l='47' c='_ZN6webrtc13ProcessThread6WakeUpEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/include/process_thread.h' l='51' c='_ZN6webrtc13ProcessThread14RegisterModuleEPNS_6ModuleERKN3rtc8LocationE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/include/process_thread.h' l='55' c='_ZN6webrtc13ProcessThread16DeRegisterModuleEPNS_6ModuleE'/>
<size>8</size>
<fun r='_ZN6webrtc6Module20TimeUntilNextProcessEv'/>
<fun r='_ZN6webrtc6Module7ProcessEv'/>
<fun r='_ZN6webrtc6Module21ProcessThreadAttachedEPNS_13ProcessThreadE'/>
<fun r='_ZN6webrtc6ModuleD1Ev'/>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/pacing/paced_sender.h' l='44' c='webrtc::PacedSender'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/pacing/paced_sender.h' l='44'/>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/pacing/paced_sender.h' l='144' c='webrtc::PacedSender::ModuleProxy'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/pacing/paced_sender.h' l='144'/>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/congestion_controller/include/receive_side_congestion_controller.h' l='35' c='webrtc::ReceiveSideCongestionController'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/congestion_controller/include/receive_side_congestion_controller.h' l='36'/>
<size>8</size>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/include/rtp_rtcp.h' l='23' c='webrtc::RtpRtcp'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/include/rtp_rtcp.h' l='23'/>
<size>8</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='39' c='_ZN6webrtc17ProcessThreadImpl6WakeUpEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='44' c='_ZN6webrtc17ProcessThreadImpl14RegisterModuleEPNS_6ModuleERKN3rtc8LocationE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='45' c='_ZN6webrtc17ProcessThreadImpl16DeRegisterModuleEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='55' c='_ZN6webrtc17ProcessThreadImpl14ModuleCallbackC1EPNS_6ModuleERKN3rtc8LocationE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='61'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='89' c='_ZN6webrtc17ProcessThreadImpl13WakeUpNoLocksEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.h' l='90' c='_ZN6webrtc17ProcessThreadImpl14WakeUpInternalEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='29' c='_ZN6webrtc12_GLOBAL__N_119GetNextCallbackTimeEPNS_6ModuleEx'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='119' c='_ZN6webrtc17ProcessThreadImpl6WakeUpEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='139' c='_ZN6webrtc17ProcessThreadImpl13WakeUpNoLocksEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='145' c='_ZN6webrtc17ProcessThreadImpl14WakeUpInternalEPNS_6ModuleE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='181' c='_ZN6webrtc17ProcessThreadImpl14RegisterModuleEPNS_6ModuleERKN3rtc8LocationE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/utility/source/process_thread_impl.cc' l='217' c='_ZN6webrtc17ProcessThreadImpl16DeRegisterModuleEPNS_6ModuleE'/>
<size>8</size>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/video_coding/include/video_coding.h' l='28' c='webrtc::VideoCodingModule'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/video_coding/include/video_coding.h' l='28'/>
<size>8</size>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/video_coding/deprecated/nack_module.h' l='32' c='webrtc::DEPRECATED_NackModule'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/video_coding/deprecated/nack_module.h' l='32'/>
<size>8</size>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/video_coding/video_coding_impl.h' l='57' c='webrtc::vcm::VideoReceiver'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/video_coding/video_coding_impl.h' l='57'/>
<size>8</size>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/video/call_stats.h' l='30' c='webrtc::CallStats'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/video/call_stats.h' l='30'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/video/call_stats.cc' l='71' c='_ZN6webrtc12_GLOBAL__N_123TemporaryDeregistrationC1EPNS_6ModuleEPNS_13ProcessThreadEb'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/video/call_stats.cc' l='86'/>
<size>8</size>
<ovr f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/video/rtp_streams_synchronizer.h' l='29' c='webrtc::RtpStreamsSynchronizer'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/video/rtp_streams_synchronizer.h' l='29'/>
<size>8</size>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/utility/include/process_thread.h' l='47' c='_ZN6webrtc13ProcessThread6WakeUpEPNS_6ModuleE'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/utility/include/process_thread.h' l='51' c='_ZN6webrtc13ProcessThread14RegisterModuleEPNS_6ModuleERKN3rtc8LocationE'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/modules/utility/include/process_thread.h' l='55' c='_ZN6webrtc13ProcessThread16DeRegisterModuleEPNS_6ModuleE'/>
