<inh f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/psfb.h' l='25' c='webrtc::rtcp::Psfb'/>
<def f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/fir.h' l='22' ll='59'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/fir.h' l='33' c='_ZN6webrtc4rtcp3FirC1ERKS1_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/logging/rtc_event_log/logged_events.h' l='189'/>
<size>40</size>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/fir.h' l='21'>// Full intra request (FIR) (RFC 5104).</doc>
<smbr r='webrtc::rtcp::Fir::kFeedbackMessageType' t='const uint8_t'/>
<fun r='_ZN6webrtc4rtcp3FirC1Ev'/>
<fun r='_ZN6webrtc4rtcp3FirC1ERKS1_'/>
<fun r='_ZN6webrtc4rtcp3FirD1Ev'/>
<fun r='_ZN6webrtc4rtcp3Fir5ParseERKNS0_12CommonHeaderE'/>
<fun r='_ZN6webrtc4rtcp3Fir12AddRequestToEjh'/>
<fun r='_ZNK6webrtc4rtcp3Fir8requestsEv'/>
<fun r='_ZNK6webrtc4rtcp3Fir11BlockLengthEv'/>
<fun r='_ZNK6webrtc4rtcp3Fir6CreateEPhPmmN3rtc12FunctionViewIFvNS4_9ArrayViewIKhLln4711EEEEEE'/>
<smbr r='webrtc::rtcp::Fir::kFciLength' t='const size_t'/>
<fun r='_ZN6webrtc4rtcp3Fir12SetMediaSsrcEj'/>
<fun r='_ZNK6webrtc4rtcp3Fir10media_ssrcEv'/>
<mbr r='webrtc::rtcp::Fir::items_' o='128' t='std::vector&lt;Request&gt;'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_packet/fir.cc' l='49' c='_ZN6webrtc4rtcp3FirC1ERKS1_'/>
<size>40</size>
<smbr r='webrtc::rtcp::Fir::kFeedbackMessageType' t='const uint8_t'/>
<fun r='_ZN6webrtc4rtcp3FirC1Ev'/>
<fun r='_ZN6webrtc4rtcp3FirC1ERKS1_'/>
<fun r='_ZN6webrtc4rtcp3FirD1Ev'/>
<fun r='_ZN6webrtc4rtcp3Fir5ParseERKNS0_12CommonHeaderE'/>
<fun r='_ZNK6webrtc4rtcp3Fir11BlockLengthEv'/>
<fun r='_ZNK6webrtc4rtcp3Fir6CreateEPhPmmN3rtc12FunctionViewIFvNS4_9ArrayViewIKhLln4711EEEEEE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_receiver.cc' l='943' c='_ZN6webrtc12RTCPReceiver9HandleFirERKNS_4rtcp12CommonHeaderEPNS0_17PacketInformationE'/>
<size>40</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_sender.cc' l='457' c='_ZN6webrtc10RTCPSender8BuildFIRERKNS0_11RtcpContextERNS0_12PacketSenderE'/>
<size>40</size>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/rtp_rtcp/source/rtcp_transceiver_impl.cc' l='218' c='_ZN6webrtc19RtcpTransceiverImpl20SendFullIntraRequestEN3rtc9ArrayViewIKjLln4711EEEb'/>
<size>40</size>
