<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='21' u='w' c='_ZN6webrtc14ThresholdCurve5PointC1Eff'/>
<dec f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='22' type='float'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='50' u='r' c='_ZN6webrtc14ThresholdCurveC1ERKNS0_5PointES3_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='50' u='r' c='_ZN6webrtc14ThresholdCurveC1ERKNS0_5PointES3_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='50' u='r' c='_ZN6webrtc14ThresholdCurveC1ERKNS0_5PointES3_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='50' u='r' c='_ZN6webrtc14ThresholdCurveC1ERKNS0_5PointES3_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='51' u='r' c='_ZN6webrtc14ThresholdCurveC1ERKNS0_5PointES3_'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='60' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='60' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='62' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='62' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='66' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='66' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='66' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='66' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='67' u='r' c='_ZNK6webrtc14ThresholdCurve12IsBelowCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='75' u='r' c='_ZNK6webrtc14ThresholdCurve12IsAboveCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='75' u='r' c='_ZNK6webrtc14ThresholdCurve12IsAboveCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='77' u='r' c='_ZNK6webrtc14ThresholdCurve12IsAboveCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='77' u='r' c='_ZNK6webrtc14ThresholdCurve12IsAboveCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='77' u='r' c='_ZNK6webrtc14ThresholdCurve12IsAboveCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='77' u='r' c='_ZNK6webrtc14ThresholdCurve12IsAboveCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='78' u='r' c='_ZNK6webrtc14ThresholdCurve12IsAboveCurveERKNS0_5PointE'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='95' u='r' c='_ZN6webrtc14ThresholdCurve8GetPointERKNS0_5PointES3_b'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='95' u='r' c='_ZN6webrtc14ThresholdCurve8GetPointERKNS0_5PointES3_b'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='95' u='r' c='_ZN6webrtc14ThresholdCurve8GetPointERKNS0_5PointES3_b'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='95' u='r' c='_ZN6webrtc14ThresholdCurve8GetPointERKNS0_5PointES3_b'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='100' u='r' c='_ZN6webrtc14ThresholdCurve8GetPointERKNS0_5PointES3_b'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/modules/audio_coding/audio_network_adaptor/util/threshold_curve.h' l='100' u='r' c='_ZN6webrtc14ThresholdCurve8GetPointERKNS0_5PointES3_b'/>
<offset>0</offset>
