<def f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/common_video/generic_frame_descriptor/generic_frame_info.h' l='47' ll='59'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/common_video/generic_frame_descriptor/generic_frame_info.h' l='53' c='_ZN6webrtc16GenericFrameInfo7Builder1TEi'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/common_video/generic_frame_descriptor/generic_frame_info.h' l='54' c='_ZN6webrtc16GenericFrameInfo7Builder1SEi'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/common_video/generic_frame_descriptor/generic_frame_info.h' l='55' c='_ZN6webrtc16GenericFrameInfo7Builder4DtisENSt3__117basic_string_viewIcNS2_11char_traitsIcEEEE'/>
<size>208</size>
<fun r='_ZN6webrtc16GenericFrameInfo7BuilderC1Ev'/>
<fun r='_ZN6webrtc16GenericFrameInfo7BuilderD1Ev'/>
<fun r='_ZNK6webrtc16GenericFrameInfo7Builder5BuildEv'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder1TEi'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder1SEi'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder4DtisENSt3__117basic_string_viewIcNS2_11char_traitsIcEEEE'/>
<mbr r='webrtc::GenericFrameInfo::Builder::info_' o='0' t='webrtc::GenericFrameInfo'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/common_video/generic_frame_descriptor/generic_frame_info.cc' l='29' c='_ZN6webrtc16GenericFrameInfo7Builder1TEi'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/common_video/generic_frame_descriptor/generic_frame_info.cc' l='34' c='_ZN6webrtc16GenericFrameInfo7Builder1SEi'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/webrtc/common_video/generic_frame_descriptor/generic_frame_info.cc' l='39' c='_ZN6webrtc16GenericFrameInfo7Builder4DtisENSt3__117basic_string_viewIcNS2_11char_traitsIcEEEE'/>
<size>208</size>
<fun r='_ZN6webrtc16GenericFrameInfo7BuilderC1Ev'/>
<fun r='_ZN6webrtc16GenericFrameInfo7BuilderD1Ev'/>
<fun r='_ZNK6webrtc16GenericFrameInfo7Builder5BuildEv'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder1TEi'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder1SEi'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder4DtisENSt3__117basic_string_viewIcNS2_11char_traitsIcEEEE'/>
<def f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/common_video/generic_frame_descriptor/generic_frame_info.h' l='47' ll='59'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/common_video/generic_frame_descriptor/generic_frame_info.h' l='53' c='_ZN6webrtc16GenericFrameInfo7Builder1TEi'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/common_video/generic_frame_descriptor/generic_frame_info.h' l='54' c='_ZN6webrtc16GenericFrameInfo7Builder1SEi'/>
<use f='webkit/WebKitBuild/Debug/usr/local/include/webrtc/common_video/generic_frame_descriptor/generic_frame_info.h' l='55' c='_ZN6webrtc16GenericFrameInfo7Builder4DtisENSt3__117basic_string_viewIcNS2_11char_traitsIcEEEE'/>
<size>208</size>
<fun r='_ZN6webrtc16GenericFrameInfo7BuilderC1Ev'/>
<fun r='_ZN6webrtc16GenericFrameInfo7BuilderD1Ev'/>
<fun r='_ZNK6webrtc16GenericFrameInfo7Builder5BuildEv'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder1TEi'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder1SEi'/>
<fun r='_ZN6webrtc16GenericFrameInfo7Builder4DtisENSt3__117basic_string_viewIcNS2_11char_traitsIcEEEE'/>
<mbr r='webrtc::GenericFrameInfo::Builder::info_' o='0' t='webrtc::GenericFrameInfo'/>
