<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/x509_vfy.h' l='217' type='int'/>
<offset>0</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/include/openssl/x509_vfy.h' l='217'>/* have we been started */</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/x509/x509_lu.c' l='76' u='w' c='X509_LOOKUP_new'/>
