<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/objfmt.h' l='39' type='const struct yasm_objfmt_module *'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='448' u='r' c='do_assemble'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='546' macro='1' u='r' c='do_assemble'/>
<offset>0</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/objfmt.h' l='38'>/** #yasm_objfmt_module implementation for this object format. */</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/gas-token.c' l='319' u='r' c='gas_parser_lex'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/section.c' l='155' macro='1' u='r' c='dir_section'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/section.c' l='255' u='r' c='yasm_object_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/section.c' l='258' macro='1' u='r' c='yasm_object_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/section.c' l='290' u='r' c='yasm_object_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/section.c' l='353' macro='1' u='r' c='yasm_object_get_general'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/section.c' l='462' macro='1' u='r' c='yasm_object_destroy'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/objfmts/macho/macho-objfmt.c' l='346' u='w' c='macho_objfmt_create_common'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/objfmts/macho/macho-objfmt.c' l='386' u='w' c='macho_objfmt_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/objfmts/macho/macho-objfmt.c' l='388' u='w' c='macho_objfmt_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/parsers/gas/gas-parse.c' l='1478' macro='1' u='r' c='parse_expr2'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/parsers/gas/gas-parse.c' l='1562' macro='1' u='r' c='gas_get_section'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/parsers/nasm/nasm-parse.c' l='1455' macro='1' u='r' c='parse_expr6'/>
