<dec f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/dbgfmt.h' l='39' type='const struct yasm_dbgfmt_module *'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/frontends/yasm/yasm.c' l='533' macro='1' u='r' c='do_assemble'/>
<offset>0</offset>
<doc f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/dbgfmt.h' l='38'>/** #yasm_dbgfmt_module implementation for this debug format. */</doc>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/section.c' l='292' u='r' c='yasm_object_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/libyasm/section.c' l='464' macro='1' u='r' c='yasm_object_destroy'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/dbgfmts/codeview/cv-dbgfmt.c' l='42' u='w' c='cv_dbgfmt_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/dbgfmts/dwarf2/dwarf2-dbgfmt.c' l='84' u='w' c='dwarf2_dbgfmt_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/dbgfmts/null/null-dbgfmt.c' l='39' u='w' c='null_dbgfmt_create'/>
<use f='webkit/Source/ThirdParty/libwebrtc/Source/third_party/yasm/modules/dbgfmts/stabs/stabs-dbgfmt.c' l='166' u='w' c='stabs_dbgfmt_create'/>
